### ISSUE TITLE
Add a blacklist of too-common passwords

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#111]
Per https://github.com/mozilla/fxa-auth-server/issues/222#issuecomment-29769332

> 2) Maintain a blacklist of common passwords and prevent users from using dumb stuff like "password" or "12345", etc. This may be slow and regex heavy as we may have to search passwords against common patterns like /password/i or /^\d+$/ as well as a dictionary.

**Comment by rfk** [comment]
@TDA I hear you may be working on some parts of this, if so can you please triage it into an appropriate state on waffle and/or split off bits of the work into sub-issues?

**Comment by TDA** [comment]
@rfk will do! sorry about not updating this!

**Comment by rfk** [comment]
@TDA thanks for taking it on :-)  This will be very valuable stuff

**Comment by TDA** [comment]
@rfk I have done a Proof of Concept for this one, which can be checked out at https://github.com/TDA/bloomFilter
Right now, we have a list of 545K passwords that are too common despite containing special characters and such, we are also preventing a ton of simple *and* common passwords with some client side JS.
Sample Screenie:
https://www.dropbox.com/s/urh63flwfvrp6jy/Screenshot%202015-07-15%2015.47.56.png?dl=0

**Comment by pdehaan** [comment]
Re: https://github.com/TDA/bloomFilter/blob/master/common_passwords.txt,

Wow, 554 / 10000 of those passwords are numeric-only. `/^\d+$/`
And only 2086 of the passwords are 8 or more chars. `/^.{8,}$/`

**Comment by TDA** [comment]
@pdehaan Wrong file :P look at the crackpasswords file with 545K passwords, thats the processed one, with those passwords removed :D

**Comment by pdehaan** [comment]
Yeah, I was looking at that **5,784 kB** file (or was trying to, it has put my Sublime Text 3 into a shame spiral and it's crashing like crazy now -- which is odd because 6MB isn't _that_ big).

**Comment by TDA** [comment]
@pdehaan https://github.com/TDA/bloomFilter/blob/master/crackstation-human-alpha-num-spec.txt --> This one might crash your ST3 forever.

**Comment by rfk** [comment]
@TDA nice POC, I like the approach.

Do we need any nuance in how we deal with false positives?  Even if the false-positive rate is at 0.01%, that's still several users a day who can expect a false-positive match at current signup rates.  They'll probably be very confused if we false-positively suggest that `Xj%g3fiPt` is a common password.

@ryanfeeley are you still happy with the proposed UX in https://github.com/mozilla/fxa-content-server/issues/111#issuecomment-45238269 as a starting point?

**Comment by rfk** [comment]
Also, this issue makes me miss @warner and his obsession with finding an excuse to put bloom filters into everything...

**Comment by warner** [comment]
Yay bloom filters! This is an *awesome* place to jam them in :)

I might suggest changing the language to say "This password *might* be guessable", to soften the confusion for the inevitable false positives. And maybe display a suggested password (correct-horse-battery-staple is still my favorite style) right in the popup instead of making them click through to some suggestion wizard. Oh, and check the suggestion against the bloom filter before presenting it, since sometimes it'll fail too, and that'd be super annoying.

Rejecting all-numeric passwords seems reasonable, but I'm not a fan of requiring mixed-character-class (like rejecting all-alpha passwords). It's too easy to just add "1" to get around that, and it prevents the correcthorsebatterystaple style.

You need 10 bits per element to get a 1% false-positive rate, about 15 bits to get 0.1%, and 20 for 0.01%. Given a fixed size budget (say 100kB), it might be better to allocate the bits towards reducing the false-positives. E.g. choose a 53K-entry 0.1% filter over an 80K-entry 1% filter.

As for how many passwords to scan, you might pretend that the purpose of this filter is to exclude passwords which could be effectively guessed by an online attack. Then you could estimate how quickly the rate-limiting or "hey somebody's guessing an awful lot of passwords today" security monitoring would kick in, and size the filter to be like 2x or 10x that size.

As always, the purpose of any sort of password filter is to provoke the user into using a higher-entropy process for selecting a password. Since the attackers know you're excluding these passwords, they'll start with the next-most-likely ones on their even-larger password lists. The hope here is that the min-entropy of the remaining passwords is higher than what you started with, so their chance-of-success-per-guess is lower (you're starting the distribution further into the long tail).

Of course, this bloom filter must be shipped to the client side, and evaluated there. You might get fancy and ship differently sized lists depending upon bandwidth estimates, and maybe language-specific lists if they exist. Also you might want to defer shipping the (large) filter object until the create-account dialog was opened, to speed up the more common cases where it's not needed.

**Comment by TDA** [comment]
@rfk So, @vladikoff and @ckarlof have suggested that we first do some user testing without the UX changes, and see how many people actually have weak passwords(in chris's words, or atleast passwords that are considered weak by the tool :D) We would be proceeding with that approach today.

@warner whoooaa :O :O someones done their research :D ill keep all that in mind, esp the part about 0.1% 50k list >>> 1% 80k list :) The all-alphabets check is going to be only if the password is 8-12 characters long. Anything longer than that will be allowed; zxcvbn from dropbox does that same thing, more memorable and high entropy passwords. Thank you for the ideas!

**Comment by TDA** [comment]
@rfk and @warner 
@shane-tomlinson @vladikoff  @ckarlof 

NO OF PASSWORDS: 545120
File Size: 3.45Mb (1.8mb gzipped)
False Positive rate: 0.003% ; 20 bits 

File Size: 2.6Mb (1.1mb Gzipped)
False Positive rate: 0.07% ; 15 bits

File Size: 1.79Mb , (870kb Gzipped)
False Positive rate: 0.8% ; 10 bits

File Size: 877Kb , (380kb Gzipped)
False Positive rate: 9% ; 5 bits

NO OF PASSWORDS: 100,000
File Size: 650k (308k gzipped)
False Positive rate: 0.003% ; 20 bits 

File Size: 497k (238k Gzipped)
False Positive rate: 0.07% ; 15 bits

File Size:  336k, (161k Gzipped)
False Positive rate: 0.8% ; 10 bits

File Size: 161Kb , (72kb Gzipped)
False Positive rate: 9% ; 5 bits


NO OF PASSWORDS: 50,000
File Size: 325k (155k gzipped)
False Positive rate: 0.003% ; 20 bits 

File Size: 249k (120k Gzipped)
False Positive rate: 0.07% ; 15 bits

File Size:  168k, (81k Gzipped)
False Positive rate: 0.8% ; 10 bits

File Size: 80Kb , (37kb Gzipped)
False Positive rate: 9% ; 5 bits


I will be back with another set of benchmarks.

**Comment by TDA** [comment]
Okay, so I removed all the passwords which had atleast two 'different' types of special characters (eg: -231casd+, !@dhgkv etc). which leaves 53251 passwords, and stats for that:

#### NO OF PASSWORDS: 53,251

| FILE SIZE | GZIPPED | FALSE POSITIVE RATE | BITS |
|----:|----:|----:|----:|
| 182k | 87k | 0.8% | 10


---

**Comment by vladikoff** [comment]
Initial work on this is complete via https://github.com/mozilla/fxa-content-server/pull/2983 

We will continue to refine it in new issues after we get some metrics results
