### ISSUE TITLE
Unable to upload GIF image for avatar pic

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1728]
Found in https://accounts.stage.mozaws.net/ver.json (commit 7ff9e196311cef2e9e5a1726aa49081f2c0167a5)

```json
{
  "version": "0.22.0",
  "commit": "7ff9e196311cef2e9e5a1726aa49081f2c0167a5",
  "l10n": "9c6f728ea6",
  "tosPp": "2becbeea57"
}
```

---

### Steps to reproduce:
1. Go to https://accounts.stage.mozaws.net/settings/avatar
2. Create an account and sign in/up.
2. Click "Change".
3. Click "Upload".
4. Try and upload a GIF.

### Actual results:
I seemingly can't select OR upload a GIF, which is mildly confusing since I thought I did once, and it animated but then after uploading it converts it to a static image.

Not every GIF is animated, and there isn't a solid reason why it couldn't be a valid avatar image.

### Expected results:
GIFS RULE EVERYTHING AROUND ME!
![cat-toast-face-gif](https://cloud.githubusercontent.com/assets/557895/4481290/9b9b4754-499e-11e4-8e1e-b2110bc04d32.gif)

**Comment by ryanfeeley** [comment]
@zaach @pdehaan I was able to upload a GIF (single frame and animated, which only showed a single frame) but I had remove the "All supported filetypes" filters in the file dialog (and just selected "All files")

**Comment by rfk** [comment]
profile-server claims to only allow PNG and JPEG uploads:

  `allow: ['image/png', 'image/jpeg']`
  https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/avatar/upload.js#L72

If we can successfully upload .gif files, either this is not working as intended, or we're converting them to pngs client-side.

**Comment by zaach** [comment]
> If we can successfully upload .gif files, either this is not working as intended, or we're converting them to pngs client-side.

canvas exports them as jpeg.

**Comment by ckarlof** [comment]
Sorry, @pdehaan, I don't think we're going to support animated GIFs for the same reasons [gravatar doesn't](http://blog.gravatar.com/2008/09/02/better-image-detection/#comment-5615). Granted, the only person currently inflicted with an animated GIF is the person who uploaded it, but that could change in the future, and we probably don't want our properties to turn into seizure inducing nightmares because everyone chooses to use this clip from [Dennō Senshi Porygon](https://en.wikipedia.org/wiki/Denn%C5%8D_Senshi_Porygon) as their avatar.

![unnamed 1](https://cloud.githubusercontent.com/assets/2365255/9230296/54f6b196-40d6-11e5-82ad-95997274f696.gif)

**Comment by rfk** [comment]
@ckarlof I am constantly amazed at how many excuses you find to drop that gif into conversation....
