### ISSUE TITLE
invalid input red border turns blue if user clicks "submit"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1865]
The red border used for invalid input elements stays red if the user submits via the "enter" key, but turns blue if the user clicks the submit button.

### STR
1) Open the /signup page
2) Enter a valid email
3) Enter a 7 character password
4) Click the "sign up" button or press "enter"
5) Press "Enter" and see that the input field border remains red.
6) Click the "sign up" button again
7) The password field's border is now blue

### Expected
The password field's border remains red

### Actual
The password field's border turns blue.

![invalid-input-coloring](https://cloud.githubusercontent.com/assets/848085/5011097/24a9dd28-6a72-11e4-837a-61f07a0089b8.gif)

**Comment by shane-tomlinson** [comment]
Let's check to see if this still happens with @johngruen's refactor.

**Comment by pdehaan** [comment]
I can confirm it still happens on latest.dev.lcip.org w/
```json
{"version": "0.34.0",
"commit": "8cf5c9356bc7d8735bed5c1dd851e3b5d6b65fe0",
"l10n": "a8c9d0d24d",
"tosPp": "61b90cfa29"}
```

**Comment by npestana** [comment]
After some debugging, it looks like the tooltip onDestroy event (https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/form.js#L438) is triggered after the addClass('invalid') (https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/form.js#L448) when "Sign up" button is clicked, so the invalid class is immediately removed. This only happens when clicking the button, when doing enter on keyboard it does it right and triggers the event before the add.

The problem happens in both email and password (first invalid).
