### ISSUE TITLE
customizeSync element of the login data is always false

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-content-server#2013]
I've adjusted my prefs to point at latest.dev.lcip.org, so about:accounts is using that.  I haven't verified if this problem also currently exists on the "real" server.  What I'm doing is:

* Open about:accounts?customizeSync=true, select "get started", note that "Choose what to sync" is correctly checked.
* Create an account

The notification we get back from the server has all login data, but always seems to have customizeSync=false - it should be true when that button was checked.

Sadly, the only good way of verifying this is to change aboutaccounts.js, find the "log" function and uncomment the dump() statement.  If you do this you will see in the console:

> Received: 'login'. Data:{"email":"skippy.hammond+...","uid":"7d2...","sessionToken":"8df...","sessionTokenContext":"fx_desktop_v1","unwrapBKey":"045...","keyFetchToken":"64a...","customizeSync":false,"verifiedCanLinkAccount":true}

Note the customizeSync value - it should be true.

**Comment by ckarlof** [comment]
I only seems to see this on `latest`, so there may have been a regression introduced recently. I get the customize dialog on prod, FWIW. Good catch, @mhammond. Thanks.

**Comment by ckarlof** [comment]
This blocks the Jan 5 train (train-28).

**Comment by ckarlof** [comment]
Typo introduced here: https://github.com/mozilla/fxa-content-server/commit/4326cb34c092d63c270926eb018da70a94b24dc0#diff-a74f50cdf368ca0e8f24665d7488f14dR278

Now investigating why test coverage didn't catch this.

**Comment by ckarlof** [comment]
> Now investigating why test coverage didn't catch this.

Answer: because it's non-trivial to test without mocked components, which we only added somewhat recently.

Having a functional test for this seems challenging, but I think that we can extend the tests in https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/views/sign_up.js that already use the mocked `fxa-client` and `broker` to make sure the `customizeSync` flag is preserved and passed to the broker. Likewise, the Desktop broker should probably have a similar test (if it doesn't already) that verifies it forwards on the necessary information to the Desktop Channel.
