### ISSUE TITLE
Refreshing on the ToS/PN pages breaks layout/back button

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2044]
Noticed this while fixing #2037

**Comment by pdehaan** [comment]
Yeah, if I go from the /signup page (on https://latest.dev.lcip.org/legal/privacy) to the privacy page it looks great. Once i refresh, it gets confused.

At the wider width, the HTML seems to be `<div id="main-content-legal">...</div>`. After a refresh, it seems to revert to `<div id="main-content">...</div>`.
I think this is due to this line: [/server/templates/pages/src/privacy.html:28](https://github.com/mozilla/fxa-content-server/blob/f60b92ddf39de716ff0d09e8a0ed82cb9609c959/server/templates/pages/src/privacy.html#L28) and [/server/templates/pages/src/terms.html:28](https://github.com/mozilla/fxa-content-server/blob/f60b92ddf39de716ff0d09e8a0ed82cb9609c959/server/templates/pages/src/terms.html#L28). Those both probably need to be changed from `"main-content"` to `"main-content-legal"`.

**Comment by ckarlof** [comment]
We should raise this in priority.

**Comment by shane-tomlinson** [comment]
> We should raise this in priority.

I'm on the "meh" side of things. Are there reports of this happening in the wild?

**Comment by shane-tomlinson** [comment]
>  I think this is due to this line: /server/templates/pages/src/privacy.html:28 and /server/templates/pages/src/terms.html:28. Those both probably need to be changed from "main-content" to "main-content-legal".

The content width is an easy fix, the back button is not. 

The TOS/PP agreements are rendered by the server when the user visits directly, we made this choice so users could visit these pages without JavaScript. If the user browses to the TOS/PP agreement from within the app, a back button is displayed and the user goes back. If the user browses to the TOS/PP agreement directly, the server renders the page so JS is not required. From the server's P.O.V., a browser refresh on the TOS/PP page is the same as a direct browse.

To add a back button, we will require JS on the page when the user browses directly. The logic could work like this:

When a user visits the main app, we set a bit in sessionStorage that says "the user can go back.". The user visits the TOS/PP page, refreshes. We load up the optional JS, check sessionStorage for the expected bit. If the bit exists, display a back button. A click on the back button would have to go back 2 places in history. This approach has a corner case for users who browse to the main app, than an external site in the same tab, then load the tos/pp agreement in the same tab. Unlikely, but someone will find it.

Some past history:  #287, #436, #480, #933

**Comment by johngruen** [comment]
Guess what, this is fixed by #2172!

**Comment by shane-tomlinson** [comment]
Re-opening, this is still a problem.

**Comment by shane-tomlinson** [comment]
ref #1968, #2326, #2225
