### ISSUE TITLE
Document what web technologies (cookies, local storage, etc) are used to determine currently signed in user

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2067]
I am evaluating `fxa-content-server` for use in Firefox for iOS.  One thing I'm seeing is that my embedding `WKWebView` maintains browsing state across sessions, which results in some unexpected behaviour after a user has logged in once.  I think what is happening is that the content server is storing cookies and/or local storage data saying that a user is signed in.  I want to control that behaviour, so I need to know what I need to clear in order to get a fresh slate when I desire one.

**Comment by ckarlof** [comment]
What is unexpected? At the high level, we'd prefer if you interact with the FxA page through the API it provides and not try to manipulate it by "clearing" its storage mechanisms. If the API we provide doesn't meet your use case, let's talk about that and see if we can provide something that does.

In general, if a user has authenticated previously in a browser, we try to make it easier for her to authenticate again in the future. 

* If the user has logged in to Sync on a device, she isn't required to enter her password again for subsequent authentications until she disconnects from Sync.
* If the user has logged into other services (but not Sync), we remember her email address, but require a password for subsequent authentications.
* If the user clicks "Use another email", we clear the saved information.

At least in the OAuth flow, the [relier can control some of this](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#get-v1authorization). The Sync flow could use some similar documentation, but it's been deprioritized since we didn't expect anyone else to integrate with the iframed Sync flow (until now).

`email=blank` may give you the clean slate UX you want. It tells the page to ignore any cached email or credentials. You should also be able to control whether "signup" or "signin" loads. I think the Sync flow navigates to those pages directly, but it wouldn't be too hard support the `action` param in the Sync flow, too.

**Comment by ncalexan** [comment]
> email=blank may give you the clean slate UX you want. It tells the page
> to ignore any cached email or credentials. You should also be able to
> control whether "signup" or "signin" loads. I think the Sync flow navigates
> to those pages directly, but it wouldn't be too hard support the action
> param in the Sync flow, too.
>
Thanks, this should serve my purposes nicely.

**Comment by shane-tomlinson** [comment]
@ncalexan - It looks like the questions you had have been answered by @ckarlof. Closing.
