### ISSUE TITLE
clear '?email=somename@example.com' query string after force_auth signin completes

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2071]
Not sure if this is really a bug, or just some oddity, but ...
                                                                                                                                            
STR

1. Sign in as a known account 'somename@example.com'
2. Load the url /force_auth?email=somename@example.com and re-enter the password
                                                                                                                                            
Expected: after login url changes to '/settings'
                            
Actual: after login url changes to '/settings?somename@example.com'.

**Comment by shane-tomlinson** [comment]
@jrgm - this is currently the expected behavior, added in fa2fa71b2f52bc334f4fe8ab256efdb45710050b. Unfortunately, some views still pull in data from the query parameters instead of relying on the relier models (pun partially intended).

Even though this is *currently* the expected behavior, I'm keeping this open to foster discussion about moving away from having views import data from the query parameters and instead rely on separate models to do that sort of thing.

**Comment by pdehaan** [comment]
Ref: #2125

**Comment by shane-tomlinson** [comment]
With #2125, we can safely remove email from the query params

**Comment by shane-tomlinson** [comment]
z-later, will be happy to mentor if anyone wants to pick this up!
