### ISSUE TITLE
How to set up correct auth/content server url?

### ISSUE THREAD

**Issue by xi3** [mozilla/fxa-content-server#2077]
The topology of server are:
                                                                                                         -------- fxa_auth_server: 192.168.100.4
Internet ---(mydomain.com: 128.128.128.128)(Router)---(vlan:192.168.100.0/24) ----
                                                                                                   ------- fxa_content_server: 192.168.100.5

the traffic at router port 80 is forward to fxa_content_server(192.168.100.5:3030)

and there is a error when a signup request is submitted: cant submite request to 127.0.0.1:9000/v1/accounts/create...and something related to "Access-Control-Allow-Origin"

how shoud i config the router forward rules and the setting in server/config/*.json?
{
  "fxaccount_url": "http://mydomain.com"
}

**Comment by vladikoff** [comment]
You need to start the https://github.com/mozilla/fxa-auth-server on some port. Then you need to point the 
`fxaccount_url` to it. (example: https://github.com/mozilla/fxa-content-server/blob/master/server/config/awsbox.json#L2) Otherwise you will get "Access-Control-Allow-Origin" errors because the server is not accepting those requests.
