### ISSUE TITLE
Unify back navigation

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2139]
I'm seeing functional and visual differences around back navigation.  I'd like to see a clear paradigm for back navigation, and a unified visual style.

Functionally, we sometimes have no back navigation (sign in/sign up) and sometimes we have back navigation (forgot password).  Visually, back navigation is sometimes a button (legal agreements) and sometimes a link (forgot password, change password).

I could be convinced that the presence/absence of back navigation is in fact correct: perhaps there's some unifying model of a single page app that I'm missing.

**Comment by shane-tomlinson** [comment]
> some unifying model of a single page app that I'm missing.

@ncalexan - I've always found this a bit weird too. I believe the unifying model is the primary action should always be a button, the secondary action a link. In the case of the TOS/PP agreements, the primary action is to go back to the original page. In reset password, the primary action is to initiate the password reset, and back is the secondary action.

@ryanfeeley and @johngruen, your input please!

**Comment by johngruen** [comment]
@ncalexan 
Generally speaking, we use buttons to define primary actions.
- on sign in/sign up there's no reason to have a back button, since there's nowhere to go back to within the application.
- on the legal pages, going back is a primary action, and there's nothing else to do
- on change password and forgot password, going back is a secondary action
- there are some odd ideas around going back in settings, but we're currently working on a spec to completely overhaul the UI there. 

FWIW, uur overall strategy here isn't the most mobile friendly thing in the world, and I'd be happy to explore making some changes if it helps smooth implementation in 105 land.

**Comment by shane-tomlinson** [comment]
@johngruen - are you still exploring this? If not, do you want to? If not, close it down.

**Comment by johngruen** [comment]
Settings update obviates this issue.

**Comment by ryanfeeley** [comment]
(although I will say that the device controller UI has a few levels of depth to review, revoke and rename devices, so we're treading into these waters)

**Comment by johngruen** [comment]
@ryanfeeley that's cool. i think better to handle this on a case by case basis.
