### ISSUE TITLE
`can_link_account` times out very quickly

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2146]
I am trying to implement the `can_link_account` flow like Desktop Firefox does.  It appears that the `can_link_account` call expects a response from the front-end very quickly -- perhaps in 5 seconds.  I am showing an alert dialog (asynchronous) and the user may not proceed on *any* particular time frame.  I wonder if we're not seeing an issue here on Desktop because the page event loop is blocked at https://dxr.mozilla.org/mozilla-central/source/browser/base/content/aboutaccounts/aboutaccounts.js#83?

In addition, I see no way to discover that the call has timed out.  This means I have an alert dialog (asynchronous) left hanging while the page proceeds to sign in.

**Comment by ckarlof** [comment]
ewww, that seems like a bug we should fix.

**Comment by shane-tomlinson** [comment]
> ewww, that seems like a bug we should fix.

I'd like to dig deeper into the requirements. In FxDesktop, responses are either 1) immediate, or 2) blocked by a synchronous browser UI which makes responses appear to be immediate. 

The timeout exists because we did not expect significant delays in receiving a response. If a message is sent and does not receive a response in N seconds, we assume a problem has occurred and message the user so they aren't left sitting there cursing Mozilla with an unresponsive UI.

**Comment by ncalexan** [comment]
On Wed, Mar 4, 2015 at 1:55 AM, Shane Tomlinson <notifications@github.com>
wrote:

> ewww, that seems like a bug we should fix.
>
> I'd like to dig deeper into the requirements. In FxDesktop, responses are
> either 1) immediate, or 2) blocked by a synchronous browser UI which makes
> responses appear to be immediate.
>
I haven't found a way to block an iOS WKWebView, so I don't think we can do
that synchronous UI :(

>  The timeout exists because we did not expect significant delays in
> receiving a response. If a message is sent and does not receive a response
> in N seconds, we assume a problem has occurred and message the user so they
> aren't left sitting there cursing Mozilla with an unresponsive UI.
>
This is reasonable, but at some point we need to trust our clients to do
the right thing.  We could do a message ping-pong before waiting
indefinitely (or 90 seconds) to be sure that the message channel is
functional.  I wouldn't mind doing any "can't relink" handling in native
code after the "signin" message is received.

**Comment by shane-tomlinson** [comment]
I am digging in to the code to try to figure out what will occur if we remove the channel timeout. [this comment](https://github.com/mozilla/fxa-content-server/blob/20121dc793a7d7fe7a375d293d348c561d4447b8/app/scripts/models/auth_brokers/fx-desktop.js#L52-L55) makes me believe the current behavior is both intentional and desired if we are to maintain backward compatibility with Fx Desktop < 31.

If the channel timeout is removed, the error branch of the promise will not resolve, and Fx < 31 will wait for the "can_link_account" response into eternity.

Testing.

**Comment by shane-tomlinson** [comment]
> If the channel timeout is removed, the error branch of the promise will not resolve, and Fx < 31 will wait into eternity for the "can_link_account" response.
>
> Testing.

Fx 29 is the first version of Firefox with ["new sync" support](https://www.mozilla.org/en-US/firefox/29.0/releasenotes/). Tests on Fx 29 reveal exactly the opposite to what I postulated above, `can_link_account` is supported, and removing the channel timeout has no adverse effect. 

New theories: 

1. I'm not testing the right browser. Versions of Fx < 29 support new sync behind a config flag.
1. the linked to comment is incorrect, all "new sync" capable browsers respond to `can_link_account` when they are ready.

If all "new sync" capable browsers support `can_link_account`, there does not seem to be any danger of removing the channel timeout.

@ckarlof or @vladikoff - I could use some context.

ref #1262 to actually get the protocol documentation complete.

**Comment by shane-tomlinson** [comment]
I spoke with @ckarlof about `can_link_account` support in Fx 29. Support was initially scheduled for 31, but was uplifted to 29. All browsers that support "new sync" respond to the `can_link_account` message. The channel timeout is not strictly necessary.

Most likely plan:

1. Keep the timeout in place for informative purposes, set it to a much longer period like 90 seconds.
1. A timeout is no longer an error. Instead, if a response is expected, log an event so these can be tracked.

**Comment by ckarlof** [comment]
Sounds good, @shane-tomlinson.

**Comment by shane-tomlinson** [comment]
After working through this a bit more, I have realized there are two classes of messages:

1. Messages that do not expect a response, e.g., `loaded` and `login`.
1. Messages that expect a response. `can_link_account`, `ping` (for the iframe case, going to be renamed).

The first type of message we can "fire and forget". The second we "fire and wait" for a response to arrive "at some point." This is the type of message we want to log and notify relier developers when an expected response is not received.

Because of this, I propose changing channel semantics to have two types of `send` functions, to handle both of these cases.

Initial proposal:
* `send` is the "fire and forget" variant. Just fire the message, do not expect a response.
* `ask` is the "fire and wait for a response" variant.

**Comment by shane-tomlinson** [comment]
This is also necessary for the WebChannel based Sync flow.
