### ISSUE TITLE
Do not assume an iframed content server should use the iframe broker.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2150]
Fx OS uses an iframe to display Firefox Accounts. It does not use the iframe broker, but depends on its own custom implementation and redirects.

Link to https://bugzilla.mozilla.org/show_bug.cgi?id=1134466

**Comment by shane-tomlinson** [comment]
Link to #2151

**Comment by ckarlof** [comment]
@shane-tomlinson, I chatted with @andymckay, and the implementation that is currently failing on on Android (https://bugzilla.mozilla.org/show_bug.cgi?id=1134466) is "new" in the sense that this isn't evidence of a regression on FxOS. However, it does represent a bug going forward, so we of course need to address it.

**Comment by andymckay** [comment]
Based on Fernando's comments in https://bugzilla.mozilla.org/show_bug.cgi?id=1134466#c15, it sounds like this could indeed be the issue. Time to go read about this WebChannel flow...

**Comment by ckarlof** [comment]
@andymckay, the first action is for us to address the fact that our code assumes it's in the "iframe OAuth flow" just because it's in an iframe.

After we fix that, your current strategy (which I assume is to capture the redirect from the privileged outer frame) may work fine. The "WebChannel" flow might be a better alternative, though.

**Comment by andymckay** [comment]
Sweet, let us know if we can help.
