### ISSUE TITLE
Communicate to desktop if a user is already signed into their accounts in the desktop browser. 

### ISSUE THREAD

**Issue by habber** [mozilla/fxa-content-server#2197]
- In reference to this form https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v1

- The sign in form will show the signed-in user if they are already signed in. (like this: http://cl.ly/image/223r2a0R3e1N)

- Also, when the user signs up, it should be reflected in native browser chrome. (for example, signed in user is reflected in the menu http://cl.ly/image/3e0b0g3F2R39)

**Comment by shane-tomlinson** [comment]
@habber - can you provide a bit more context in the way of a bugzilla bug or more info here?

**Comment by habber** [comment]
@shane-tomlinson Sure! I thought this was the proper channel. What component should I post the bug under?

**Comment by ckarlof** [comment]
@habber what @shane-tomlinson is getting at is that users typically don't "sign in" and "sign up" without any other context. They "sign in for <service>" or "sign up for <service>" where <service> is something like "Marketplace", "Sync", or "Hello". We don't have a monolithic "you have to sign in to all the things or none of them" experience so e.g., when you sign in to Marketplace on the Web, that won't sign you in to the browser for Sync. 

Can you provide the STR of the experience that motivated this bug?

/cc @ryanfeeley

**Comment by habber** [comment]
@ckarlof @shane-tomlinson @ryanfeeley Sure. I understand that the sign-in experience is tied to the service/benefit. The end goal of the flow in question results in signing into Sync and this goal will be clearly stated to the user. 

The motivation for this is the same motivation for this issue https://github.com/mozilla/fxa-content-server/issues/2198  Pending outcomes from growth team testing, we would like to include a Sync sign-in flow from the /firstrun web page for Firefox 38 launch.

**Comment by ckarlof** [comment]
Can your bug be rephrased as "We'd like a way to sign in to Sync from the `/firstrun` Web page without loading `about:accounts`?

If not, I'm confused, because there is currently no way for `https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v1` to sign the user into Sync without being loaded in `about:accounts`.

**Comment by ryanfeeley** [comment]
@ckarlof @shane-tomlinson I should have filed this issue for @habber so I could translate it to our team’s language.

We are working together to increase the number of account sign-ups by surfacing registration into marketing content.

I believe what we're trying to discover is:
* Can a web page iframe the sync entry point registration? (i.e. form with "choose what to sync")
* Can this iframed registration form seed Firefox with the unverified state? (i.e. tell the user that they need to verify the account that was submitted)
* Can the iframed auth know if the browser is already logged in to Sync and/or Hello so that additional accounts are not created? (i.e. we will show http://cl.ly/image/223r2a0R3e1N )

**Comment by rfk** [comment]
I'm no expert on the subject, but there's a lot of legacy code and special magic in the sync sign-in process, so I won't be surprised if this is harder to implement than it appears.

Without wishing to commit to anything in particular, what's the timeframe for delivering this functionality with sufficient lead time for testing as part of Firefox 38 launch?

**Comment by rfk** [comment]
Aha, I see "launch on May 12th" in the related bug #2198 so I guess we can scope and schedule backwards from there.

**Comment by ckarlof** [comment]
It's actually not that bad. The `about:accounts` page loads an iframe [and installs an event listener](https://hg.mozilla.org/mozilla-central/annotate/6686aacf006f/browser/base/content/aboutaccounts/aboutaccounts.js#l121), which is used to implement a [pretty simple command channel](https://dxr.mozilla.org/mozilla-central/annotate/6686aacf006f/browser/base/content/aboutaccounts/aboutaccounts.js#221). I image we could port this to use WebChannels pretty easily so any accounts page could be used to log into Sync.

**Comment by shane-tomlinson** [comment]
Ref #2198

**Comment by shane-tomlinson** [comment]
Ref #2101

**Comment by issues-bouncer** [comment]
Hey @shane-tomlinson, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by shane-tomlinson** [comment]
I'm closing this for now, because I think the work needed for the firstrun flow is already complete. The firstrun flow is going to send users to `/`. If the user is already signed in to FxA in this browser, the user will be sent to `/signin`, if not, to `/signup`. Realistically, no new user that sees the firstrun flow should ever be signed in unless they somehow browse to the firstrun flow directly.
