### ISSUE TITLE
OAuth flow: verification dead-end

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2343]
> 
When I go through the sign-up process, I go through:
>
1) Start on the FxA Sign-up page
2) I enter in a new account
3) I am prompted to verify my email
4) I go into my email and click the verify link
5) The link opens in a new tab with a page that says something to the extent of "email verified"
>
The issue here is that the tab that I land on where it tells me that my email is verified has no button and does not redirect me to the destination. So as a user I was confused on where to go next or how to get to Pocket.
>
What happens is that the original tab (where it told me to go check my email - step #3) is the tab that is redirected to our redirect-url. This happens fairly invisibly to the user because it's a background tab. 
>
I would recommend that on the "you've verified your email!" page that it either has a button that says "Continue" that goes to the redirect url, or that it automatically redirects the user after a moment. That way we don't end up leaving the user in a dead-end.

**Comment by rfk** [comment]
/cc @ryanfeeley for advice here.

Is there any cleverness we can do if the verification page opens in a new tab in the same browser as the origin tab?  I'm sure we've explored this ground thoroughly in the past but I don't recall the details.

**Comment by zaach** [comment]
Yeah, there were some shuffling of how this was handled when we integrated Loop. @vladikoff may recall more details here.

**Comment by vladikoff** [comment]
@zaach when we added loop we added this change:
https://github.com/mozilla/fxa-content-server/blob/404752cf4901c0faf9632c6910ca85fb7cd2290f/app/scripts/views/ready.js#L54

WebChannel flows would not show the link.
Now now we don't show it at all https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/ready.js#L38

**Comment by ryanfeeley** [comment]
Isn't the service name optionally a link?

**Comment by vladikoff** [comment]
Also this template https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/templates/ready.mustache#L20

**Comment by shane-tomlinson** [comment]
> I would recommend that on the "you've verified your email!" page that it either has a button that says "Continue" that goes to the redirect url, or that it automatically redirects the user after a moment. That way we don't end up leaving the user in a dead-end.

This is intentional, and a Marketplace requirement. @ckarlof and I discussed this in #1723, https://github.com/mozilla/fxa-content-server/pull/1725#issuecomment-57560872, and #1942.

> Isn't the service name optionally a link?

@ryanfeeley - No, see the above context.

------------------------------------

I'd really like to avoid special casing individual reliers. I already find the situation uncomfortable, confusing, and [unsustainable](https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA/). Adding to the madness is a foot gun.

The preferred route forward is for Marketplace (@andymckay, @kumar303) to allow multiple redirects from the same browser, though I'm not sure of the feasibility of this. Barring this, perhaps a relier can specify an opt-in flag that allows the verification page to redirect back to the relier.

**Comment by vladikoff** [comment]
From irc:
```
[16:45:23]  <vladikoff>	zaach, what if they paste the email link into the same tab?
[16:46:29]  <zaach>	vladikoff: can we access the oauth state? if so, it should redirect also
[16:46:44]  <vladikoff>	zaach, but what to do with marketplace then
[16:47:12]  <zaach>	vladikoff: marketplace won't have the extra parameter?
[16:48:02]  <zaach>	vladikoff: the redirects are only for when the extra parameter is sent, right
[16:49:22]  <vladikoff>	zaach, how did you want to choose
[16:49:45]  <vladikoff>	zaach, i.e which clients use it and which do not
[16:51:11]  <zaach>	vladikoff: it'll be up to the relier. if they send the extra param to the oauth authentication endpoint it will forward it to the content-server
[16:52:44]  <zaach>	vladikoff: in the future we can decide if we want to include the option in the client's info stored with the oauth server
[16:52:57]  <zaach>	but for now a param is fine
```

**Comment by andymckay** [comment]
I'm not quite sure what the actual question for the marketplace is here. Best person to ask is probably @washort if you want marketplace to make any changes.

**Comment by ckarlof** [comment]
For Hello we didn't make the relier name a link because it had nowhere to go on the Web (it may now).
For Marketplace, we didn't make the relier name a link because their code didn't support the OAuth flow completing in a second tab.

With Pocket, now may be the time to consider making this a configurable option for each relier since Pocket seems to want the "continue from the verification landing page" experience.

**Comment by ryanfeeley** [comment]
Design for @zaach. I removed the link in the sentence to reduce confusion to user. https://www.dropbox.com/s/oram2kxiv1mv941/Account%20Verified.pdf?dl=0

**Comment by shane-tomlinson** [comment]
ref #2670
