### ISSUE TITLE
TOS/PP have an ugly scroll bar when loaded in an iframe

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2351]
When FxA is loaded in an iframe, the TOS/PP agreements cause an ugly scroll bar to be displayed:

![screen shot 2015-04-26 at 17 17 06](https://cloud.githubusercontent.com/assets/848085/7338084/443dc472-ec38-11e4-9d41-2dab63a9dfcf.png)

Possible work arounds:

* Expand the containing iframe to expand to the size of the contents.
* Open the TOS/PP agreements in a new tab.

cc @ryanfeeley and @johngruen - what should we do here?

Ref #1968, #2101, #2225, #2337

**Comment by johngruen** [comment]
@shane-tomlinson: in this case i think we should scroll internally to the content area. Is the iframe flow currently used in the wild anywhere?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson: in this case i think we should scroll internally to the content area. Is the iframe flow currently used in the wild anywhere?

It will be with the new first run flow.

**Comment by shane-tomlinson** [comment]
ref #1832

**Comment by shane-tomlinson** [comment]
The general consensus for the firstrun flow is to open the TOS/PP agreements in a new tab.

See designs at http://cl.ly/image/1N0L1F2F1N26

**Comment by TDA** [comment]
@shane-tomlinson: Wouldn't opening the TOS/PP in a new tab also require us to remove the back button or link it to the previous page(through referrer header maybe?)
Isn't changing the width of the iframe a simpler solution? It will atleast be restricted to the fxa-relier-client.js file instead of having to edit tos/pp/signup etc
