### ISSUE TITLE
Android: Make logging in to FxA reliers easier

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2353]
Firefox for Android team is requesting something like this:

**If a user is already logged in into FxA in Firefox for Android and wants to login to an OAuth property, then there should be a way to suggest a login**:

![image](https://cloud.githubusercontent.com/assets/128755/7353564/883ba202-ece2-11e4-8ff9-e6b2cd5a39c3.png)

I think the closest we have to this scenario is the oauth login when Sync is already setup in Fx Desktop.
(via https://github.com/mozilla/fxa-content-server/blob/c6b7b8737bd546f5b0716c5282ff4edeba244ca4/app/scripts/models/user.js#L107-L110 )

ping @shane-tomlinson @zaach @rfk 

Bugzilla Issues: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1158869
https://bugzilla.mozilla.org/show_bug.cgi?id=1158875

**Comment by ncalexan** [comment]
@vladikoff yeah, this is pretty much it.  We have an uber-powerful account on device, one that can produce Browser ID assertions and FxA OAuth tokens at will (providing it's healthy).  However, that account (and the underlying browser) have *no* knowledge of the web (accounts.firefox.com) at all.  

What I'm looking for is what's technically possible in order to have the user interact with accounts.firefox.com and other FxA-backed sites *without* having to sign-in fresh.

I can think of a few ways to do this:
* have a "secret back door" that lets a client with a native account context prepare the web context (sessionStorage, cookies, localStorage) without user intervention; or
* make every part of accounts.firefox.com speak a protocol that allows automatic authentication without regard to the web context;
* make accounts.firefox.com do something like X-Auto-Login, so that sign-in can be really smooth when the device has a native Firefox Account.

**Comment by ncalexan** [comment]
If we end up determining this isn't worth the effort, that's fine.  It will hurt to ask our users to provide their *email address* as well as their password, but we don't expect to require it too many times.  I do expect that we will want to cross this bridge if and when we move Firefox for Android to a web-based account flow.

**Comment by ncalexan** [comment]
@zaach: you and I talked about this, specifically point 2 of my earlier comment, today.

**Comment by vladikoff** [comment]
@rfk can we close this and sync up in the Aha card?

**Comment by rfk** [comment]
IIUC, we'll get a little bit of this for free when switching to the web-based login flow, and the rest of the ask is covered by our plans for "device handshake".  Closing this out and it'll come back through feature-planning of that feature.
