### ISSUE TITLE
Fx for iOS snippet needs to be updated

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2379]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1149685#c5:

> Jon: For 38.0.5, we need to remove the button for iOS as it is not ready.
> We have two options here:
> 1) Remove the iOS button and iOS variation of the snippet complete.
> 2) Keep the variations, and replace the button with a string that is already localized:
> Firefox is coming soon to iOS! <a href="{url}">Sign up to learn more</a>
> where the URL is https://www.mozilla.org/newsletter/ios/
> I like option 2:.
> Let's get feedback.

It sounds like the App Store link needs to be removed and replaced with "Sign up to learn more".

cc @jpetto

**Comment by jpetto** [comment]
Yeah, if we still have time (localization/push), we would like to update the snippet. Instead of the Apple App Store image, we'll need the strings "Firefox is coming soon to iOS!"\* and "Sign up to learn more".

I'm working on a branch/PR right now. Should have something ready by tomorrow.

\* Need to verify this string, but it's what we use [here](https://www.mozilla.org/en-US/newsletter/ios/), so I'm fairly confident.

**Comment by shane-tomlinson** [comment]
Closing as done.
