### ISSUE TITLE
"Invalid Scopes" error from oauth-server does not produce error UI

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2426]
I found this while testing the flip over of pocket relier credentials to `trusted: false` status, while they're still requesting full `profile` scope.  STR:

* Sign in through an untrusted relier
* Tweak the requested scope to something that's not allowed for untrusted reliers, like "profile".
* Enter password and click "Sign In"

Expected Results:

* An error indicator of some kind, e.g our little red box with the error message

Actual Results:

* The page appears to hang with the "Sign In" button greyed out and no indication that something has gone wrong.  Network view reveals a 400 error from oauth /authorization request.

**Comment by shane-tomlinson** [comment]
@rfk - I issued what I view as a partial fix in #2433. We now display an error message, but it could be displayed sooner to help relier developers.

POST /authorization must be called for the user to learn that the requested scopes are invalid. This is kinda crappy because /authorization is not called in the signin flow until after the user has clicked "proceed" on the permissions screen. On sign up, it's even worse. The user must verify their email before /authorization is called!

A nicer flow would be for the list of acceptable scopes to be returned in the call to `/v1/client/<client_id>`. If a requested scope does not match one in the list, `Invalid scopes` could be displayed to the user on startup.

**Comment by rfk** [comment]
Indeed.  This is very much a half-measure on the way to some better notion of what scopes are allowed for what clients.

> A nicer flow would be for the list of acceptable scopes to be returned in the call to /v1/client/<client_id>

You could infer this from the value of `trusted` in that response, but it would hard-code information we already have on the server.  An optional `allowed_scopes` field in this response seems like a good bit of developer ergonomics.

**Comment by rfk** [comment]
I filed https://github.com/mozilla/fxa-oauth-server/issues/257 to ensure we track the suggestion in the right place.

**Comment by shane-tomlinson** [comment]
Follow on issues opened, closing this.
