### ISSUE TITLE
Regression: I see the default profile image flash before I see my profile image

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2429]
This is a regression of #2105.

**Comment by zaach** [comment]
I wasn't able to reproduce after creating a fresh account and uploading a profile image or gravatar, but this might be from a case we forgot to handle. Namely, if you've set your profile image in a different browser or before clearing local storage then we won't have it cached and our heuristic fails. The fix is to cache it after fetching and not just when it's updated.
