### ISSUE TITLE
Blocking all cookies throws 500

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2480]
![image](https://cloud.githubusercontent.com/assets/128755/7841538/597eecb2-046b-11e5-9d38-b50321c11f49.png)

![image](https://cloud.githubusercontent.com/assets/128755/7841532/4d480d5c-046b-11e5-9d89-68ff6173b85f.png)

### Expected

Better messaging that cookies are disabled and the user should enable them?

**Comment by pdehaan** [comment]
@vladikoff Your images, they are broken.

**Comment by vladikoff** [comment]
uh dropbox :(

**Comment by vladikoff** [comment]
Updated! thanks @pdehaan !

**Comment by shane-tomlinson** [comment]
I just realized why this happens. In app-start.js, [initializeUuid](https://github.com/mozilla/fxa-content-server/blob/a29dbc519e1f60b19feb4751cf598fc34a87c7f1/app/scripts/lib/app-start.js#L130) occurs before the [cookie check](https://github.com/mozilla/fxa-content-server/blob/a29dbc519e1f60b19feb4751cf598fc34a87c7f1/app/scripts/lib/app-start.js#L641). Since initializeUuid accesses localStorage, an exception is thrown if cookies are disabled. A thrown exception causes the 500 page to be shown.

**Comment by shane-tomlinson** [comment]
Note, this same problem should manifest on *any* browser with cookies disabled.

**Comment by shane-tomlinson** [comment]
Just tested in Chrome and Firefox, both redirect to 500 with cookies disabled.

**Comment by shane-tomlinson** [comment]
ref #2677

**Comment by shane-tomlinson** [comment]
@philbooth - tag, your it.

**Comment by vladikoff** [comment]
@philbooth @shane-tomlinson this could be a 3 part fix

Part 1: provide better messaging when cookies are disabled
Part 2: provide better messaging when in iOS private mode
Part 3: have a way for verify_email work even without cookies and storage.

**Comment by vladikoff** [comment]
another related bug: https://github.com/mozilla/fxa-content-server/issues/1140

**Comment by philbooth** [comment]
@shame-tomlinson

There's a bigger problem here than just the UUID one I think. If that issue is addressed, an error is instead thrown from router.js [when we access `window.sessionStorage`](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/router.js#L143).

Of course, the router itself is used by `_selectStartPage`, which contains a condition that precludes performing the cookie check any earlier, giving us a nice chicken-and-egg problem.

It feels like the correct sequence should be something like:

1. If path is /cookies_disabled, stop everything.
2. "Mostly initialize" the router.
3. Perform the cookie check, redirecting to /cookies_disabled if necessary.
4. Finish initializing the router and initialize the UUID.

What do you think?

I'd also like to propose a couple of other changes while I'm at it:

1. Everywhere we refer to `areCookiesEnabled` yet I notice the [function itself](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/config-loader.js#L63-L87) doesn't even check cookies any more, it only checks local storage. So I think a more honest name for this function and all variable names based off it would be `isStorageEnabled`. Agree or disagree?

2. I think app-start.js is conceptually quite complex. It does a lot of stuff. In addition to actually doing that stuff, it also encodes the sequence that the stuff is done in and a bunch of state resulting from the stuff. I don't know what the perfect solution would look like, but it would be an improvement if the sequencing was encoded in data rather than in code I think. This is obviously a big-ish refactoring so I'm not suggesting I do it now, but I did want to mention it. Any thoughts?

**Comment by philbooth** [comment]
In case the preceding comment is unclear, this is my WIP branch containing the described sequence:

https://github.com/mozilla/fxa-content-server/compare/phil/wip-issue-2480

**Comment by philbooth** [comment]
Opened #2702 for the `areCookiesEnabled` point.

**Comment by philbooth** [comment]
@shane-tomlinson you mentioned there may already be a bug for the larger app-start.js refactor. I did a search but couldn't find it, any ideas?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson you mentioned there may already be a bug for the larger app-start.js refactor. I did a search but couldn't find it, any ideas?

File it! I couldn't find one in either the opened or closed list, so I probably filed it in my head only.

**Comment by vladikoff** [comment]
> It feels like the correct sequence should be something like:

> If path is /cookies_disabled, stop everything.
> "Mostly initialize" the router.
> Perform the cookie check, redirecting to /cookies_disabled if necessary.
> Finish initializing the router and initialize the UUID.

We must initialize the UUID before the cookie check because our js reporting + able depends on it. 
We can however only *store* the uuid after the cookie check.

**Comment by vladikoff** [comment]
@philbooth @shane-tomlinson first of all here here are the issues that I found with this error (mostly based on https://github.com/mozilla/fxa-content-server/issues/2677):

"
1. User has cookies disabled or in private mode in Safari iOS, installs Firefox for iOS, clicks 'Sign In in Firefox iOS', fills out FxA registration[1]
2. Gets an email in iOS Mail.app, clicks /verify_email. iOS Mail.app opens Safari
3. **Actual**: Safari throws 500 **Expected**: Safari verifies account
"

[1] no errors here because our embedded view is not Safari

Also here is a reddit thread where someone had issues with the 500 error view: http://www.reddit.com/r/firefox/comments/378nv1/firefox_sync_and_500_error/

**Comment by shane-tomlinson** [comment]
@vladikoff - if we use the nice storage abstractions that @zaach or you wrote, we can still store the uuid to a storage instance, it just might not be written to localStorage.

**Comment by vladikoff** [comment]
> There's a bigger problem here than just the UUID one I think. If that issue is addressed, an error is instead thrown from router.js when we access window.sessionStorage.

Can we just `try catch` that as well, just set the UUID in app-start but don't *store* the UUID if we want to show a nice message

**Comment by philbooth** [comment]
> Can we just try catch that as well, just set the UUID in app-start but don't store the UUID if we want to show a nice message

@vladikoff actually the `Storage` object pretty much takes care of that for us. PR incoming shortly, but you can disregard most of the discussion from earlier in this thread. Everything is simpler than I realised.

**Comment by vladikoff** [comment]
> Everything is simpler than I realised.

:+1: yeah I hoped so, I was worried that I was losing context a bit and could not address your concerns :smile:

**Comment by shane-tomlinson** [comment]
ref #2656, #2506
