### ISSUE TITLE
Measure number of accounts with display name set

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2505]
Ref: https://github.com/mozilla/fxa-content-server/issues/2294

**Comment by vladikoff** [comment]
@rfk we were trying to figure out what would be useful to keep track for the display name. @ryanfeeley suggestions the # of display names set. Do you think there is an easy way to determine that?

**Comment by rfk** [comment]
I think this is a useful thing to track.

We've traditionally taken "total count" type metrics by just counting in the production database; see for example the "number of users with multiple devices" metrics work in https://github.com/mozilla/fxa-auth-db-mysql/issues/72.  But this isn't a very sustainable approach, because doing long-running queries on the production database is scary, which is why things like https://github.com/mozilla/fxa-auth-db-mysql/issues/81 are blocked waiting on ops cycles.

As @jrgm mentioned in https://github.com/mozilla/fxa-auth-db-mysql/issues/72#issuecomment-131663970, a better approach is to run counting metrics queries against a replica of the prod db, but we don't have a suitable replica yet.

We could also try to synthesize the count somewhere downstream in the metrics pipeline, by tracking individual adds/removes of display_name.  But I'm not sure how to keep that accurate.

> Do you think there is an easy way to determine that?

Which I guess is a lot of words to say "no, but we should find one"...

**Comment by vladikoff** [comment]
Moved to https://github.com/mozilla/fxa-profile-server/issues/152
