### ISSUE TITLE
malformed WebChannelMessageToContent event

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2518]
### Steps to reproduce
1. go to https://accounts.firefox.com/settings/avatar (sign up and verify if needed)
2. Upload an image.
3. Go back and delete the image.

### Actual results
I get the following error message after steps 2 and 3:
```
"malformed WebChannelMessageToContent event" "{"id":"account_updates"}"
```

![manage_account](https://cloud.githubusercontent.com/assets/557895/7972476/9c7eee68-0a01-11e5-8ec0-4f30a226e961.png)

### Expected results:
nothin' in my console.

**Comment by shane-tomlinson** [comment]
@pdehaan - which version of Fx are you using?

**Comment by shane-tomlinson** [comment]
> @pdehaan - which version of Fx are you using?

Reproducible on Fx 38.05 and Fx 39. 
Not reproducible on Fx 40, which contains my WebChannel updates.

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa-content-server/issues/1513

Revenge of channel errors.

The `account_updates` WebChannel is not registered on startup in Fx 39.05 an Fx 40.

**Comment by shane-tomlinson** [comment]
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1173830

Since the `account_updates` WebChannel is not registered on startup in Fx 39.0.5 and Fx 40, the browser is supposed to send back an WebChannel message with an `error` field in the event. The error field is being filtered out incorrectly before being sent, so we receive an event with neither `message` nor `error`. 

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1173830
