### ISSUE TITLE
decide whether 'use strict' is appropriate for node code

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2558]
From https://github.com/mozilla/fxa-content-server/pull/2537#issuecomment-110495101
Do we have to use 'const' and other 'strict mode'  incompatible syntax in our node code?

**Comment by pdehaan** [comment]
Ref: [./grunttasks/l10n-create-json.js:7-9](https://github.com/mozilla/fxa-content-server/blob/f812ac6e064320135b47c6c03cc3c9eafb2656a3/grunttasks/l10n-create-json.js#L7-L9)

```js
const mkdirp         = require('mkdirp');
const fs             = require('fs');
const path           = require('path');
const jsonOutputPath = path.join(__dirname, '..', 'app', 'i18n');

module.exports = function (grunt) {
  'use strict';

  // ...
};
```

If we change this to global strict w/ `const` it kind of barfs with the following warning:

> ### SyntaxError: Use of const in strict mode.

```js
'use strict';

const mkdirp         = require('mkdirp');
const fs             = require('fs');
const path           = require('path');
const jsonOutputPath = path.join(__dirname, '..', 'app', 'i18n');

module.exports = function (grunt) {
  // ...
};
```

```
$ grunt jshint

/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/grunttasks/l10n-create-json.js:9
const mkdirp         = require('mkdirp');
^^^^^
Loading "l10n-create-json.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.

Running "jshint:grunt" (jshint) task

✔ No problems


Running "jshint:app" (jshint) task

✔ No problems


Running "jshint:tests" (jshint) task

✔ No problems


Running "jshint:server" (jshint) task

✔ No problems


Done, without errors.
```

**Comment by shane-tomlinson** [comment]
I've updated the title to more closely reflect what I was thinking. 

The debate we had on IRC last night was whether we want to 'use strict' in node based files, prohibiting us from using new syntax like `const`, or whether we want to rely on our linters to catch the type of errors that 'use strict' does.

So that @TDA was unblocked on his PR, I proposed we just change the `const` in the node files to `var`, leave the `use strict` statements, and debate here.

I would personally rather ditch use strict and rely on the linters to catch the sorts of errors, most importantly, assignments to undeclared variables that end up polluting the global namespace.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Comment by pdehaan** [comment]
FWIW, if we do switch to ESLint (see #2550), then we can just set the "env" to "es6" and we can use `"use strict"` and `const`.

**Comment by zaach** [comment]
> I would personally rather ditch use strict and rely on the linters to catch the sorts of errors, most importantly, assignments to undeclared variables that end up polluting the global namespace.

:+1:

`use-strict` is so ES5.

**Comment by pdehaan** [comment]
When are we going to discuss writing full server ES6 style w/ something like [Babel](https://babeljs.io/)?

**Comment by vladikoff** [comment]
from meeting:
  let's not `use_strict` with node code
