### ISSUE TITLE
Create an improved snippet for iOS Firefox

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2590]
Android has a nice graphical snippet that appears upon verification. Why shouldn't iOS?

Android examples:
![android-snippet-1](https://cloud.githubusercontent.com/assets/68213/8137441/73ac2750-1111-11e5-9b22-af056f171f70.png)
![android-snippet-2](https://cloud.githubusercontent.com/assets/68213/8137442/73b4f006-1111-11e5-8fae-1ad1cc904e85.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - We haven't actually released the iOS snippet to the wild since Fx for iOS isn't released. A Fx for Android snippet with a link to the play store should be.

When released, the Android and iOS material can be on the same snippet, both of these only show app store icons.

cc @habber - can you work with @ryanfeeley on this?

**Comment by ryanfeeley** [comment]
I think there is a "iOS is coming soon" snippet, no? We should improve it, if it looks like I remember it looks like.

**Comment by vladikoff** [comment]
I agree that we need a cool new iOS snippet, but nothing actionable in this issue. We can reopen this but I suggest opening a new issue once Firefox iOS is closer to release and we have the proposed design + a link for the snippet.
