### ISSUE TITLE
Unable to verify emails from "protonmail" service

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2653]
From support:

  https://support.mozilla.org/en-US/questions/1049856

Several users have reported problems verifying their email with an @protonmail.ch account.  Clicking the link from the email produces a "you need javascript enabled" error, but copy-pasting the link into the URL bar works fine.

**Comment by pdehaan** [comment]
Looks like you can sign up and reserve a username, but they're throttling account creations at the moment.

> Due to high demand, we have hit our capacity limit. We are adding servers constantly and will send you an invitation as soon as possible.
> ...
> You've successfully reserved your username. We'll notify you when space becomes available in our public beta.

**Comment by pdehaan** [comment]
Assigning to myself for investigation, but there isn't anything "actionable" for me to do until I can get a @protonmail.(ch|com) email address.

**Comment by jasonstockman** [comment]
This is because Javascript is disabled in sandboxed iframes, which is great. 

However there is a bug with both Mozilla and with Chromium/Chrom where links in these sandboxed iframes will spawn new tabs that also have their Javascript disabled.

https://bugzilla.mozilla.org/show_bug.cgi?id=1071660#c1

We are fixing this in an upcoming release by completely redoing our entire application to get rid of iframes, but this won't be ready for another few weeks.

Here is a quick video showing the issue. The first tab is normal. Then you see me click a link to the same site within a sandboxed iframe and you see all JS functionality is missing.

https://www.dropbox.com/s/2aoq8khicx3br65/sandbox-bug.mov?dl=0

I suspect the activation link for Mozilla accounts uses Javascript and that's why the complaints are coming in. For now ProtonMail users must wait for us to finish and deploy our latest build in a few weeks and or Mozilla can patch this issue.

Feel free to tweet us @protonmail or email me for a faster response. Our support email can be backed up. jason@protonmail.ch

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/8536859/d39a626e-2424-11e5-9d34-2a85064ce2b0.png)

@rfk I hope we have enough info for SUMO to provide an answer. Otherwise we should wait for protonmail to fix their app or ask to prioritize https://bugzilla.mozilla.org/show_bug.cgi?id=1071660

Closing because we cannot anything here, except maybe have a way for `no-js` to verify their email somehow.

**Comment by shane-tomlinson** [comment]
ref #2677 about verifying with JavaScript disabled should still work.

**Comment by vladikoff** [comment]
> ref #2677 about verifying with JavaScript disabled should still work.

just to clarify that is not what that issue says. no cookies and no localstorage does not mean no javascript.

**Comment by shane-tomlinson** [comment]
> just to clarify that is not what that issue says. no cookies and no localstorage does not mean no javascript.

You are right, I was confused. You aren't supposed to be online today.
