### ISSUE TITLE
Figure out a way to protect against broken html in l10n files

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2659]
As a follow on to #2628. We should check localizations for broken HTML

**Comment by shane-tomlinson** [comment]
From @pdehaan in https://github.com/mozilla/fxa-content-server/issues/2628#issuecomment-117818241

-----------------

IIRC, this breakage probably could have been caught by some cryptic HTMLLint sorcery.
https://github.com/mozilla/fxa-content-server-l10n/commit/a8702dbd9df4a5ba8267744a87eabdfbc29e4602#diff-5a1899d8f96c5acaca370fea22db7d0cL674

It looks like it was just somebody accidentally removing the opening `<` in a `</a>` tag, which makes things go wrong real fast.

But yeah, I think it'd be down to us grabbing the files from fxa-content-server-l10n via bower, compiling them all per-language (so, `grunt build`), then running grunt-htmllint on the 950+ generated files in _/server/templates/pages/dist/\*\*/\*.html_ (and then hope we don't get a ton of false warnings).

**Comment by pdehaan** [comment]
Some fun HTMLLint conversation and GIF-splosions over in https://github.com/mozilla/fxa-content-server/pull/1446

**Comment by ckarlof** [comment]
@zaach, we need to have some short term mitigation for this ASAP -- probably sanity check the translated strings in some way. Longer term, it would be great if we can migrate away from this (i.e., just escape all translated strings).

**Comment by philbooth** [comment]
...or store the strings in markdown and compile them to HTML on import?

**Comment by zaach** [comment]
For reference, here's the markup we're dealing with:

```
locale/templates/LC_MESSAGES/client.pot
111:msgid "Unknown account. <a href=\"/signup\">Sign up</a>"
119:msgid "Account already exists. <a href=\"/signin\">Sign in</a>"
127:msgid "Courtesy of <a href=\"https://www.gravatar.com\">Gravatar</a>"
139:msgid "Account locked. <a href=\"/confirm_account_unlock\">Send unlock email</a>"
335:msgid "Did you mean <span tabindex=\"1\">%(domain)s</span>?"
397:"By proceeding, you agree to the <a id=\"service-tos\" "
398:"href=\"%(termsUri)s\">Terms of Service</a> and<a id=\"service-pp\" "
399:"href=\"%(privacyUri)s\">Privacy Notice</a> of %(serviceName)s "
658:"By proceeding, you agree to the <a id=\"fxa-tos\" "
659:"href=\"/legal/terms\">Terms of Service</a> and <a id=\"fxa-pp\" "
660:"href=\"/legal/privacy\">Privacy Notice</a> of Firefox cloud services."

locale/templates/LC_MESSAGES/server.pot
79:"You are using an <strong>outdated</strong> browser. Please <a "
80:"href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your "
136:"For more information, please visit <a "
137:"href='https://support.mozilla.org'>Mozilla Support</a>"
```

**Comment by shane-tomlinson** [comment]
Thanks @zaach. I can see these being re-written in Markdown to:

```
locale/templates/LC_MESSAGES/client.pot
111:msgid "Unknown account. [Sign up](/signup)"
119:msgid "Account already exists. [Sign in](/signin)"
127:msgid "Courtesy of [Gravatar](https://www.gravatar.com)"
139:msgid "Account locked. [Send unlock email](/confirm_account_unlock)"
335:msgid "Did you mean <span tabindex=\"1\">%(domain)s</span>?"
397:"By proceeding, you agree to the [Terms of Service](%(termsUri)s) and [Privacy Notice](%(privacyUri)s\) of %(serviceName)s "
658:"By proceeding, you agree to the [Terms of Service](/legal/terms) and [Privacy Notice](/legal/privacy) of Firefox cloud services."

locale/templates/LC_MESSAGES/server.pot
79:"You are using an **outdated** browser. Please [upgrade your browser](http://browsehappy.com) to improve your "
136:"For more information, please visit [Mozilla Support](https://support.mozilla.org)"
```

We could re-encode the mailcheck to use an anchor instead of a span:
```
335:msgid "Did you mean [%(domain)s](#)?"
```

We would not have the ability to use IDs in the links, so we'd have to use alternative selectors, perhaps based on the href. We would also have to deal with nested `(`, e.g., `(%(termsUri)s)`, though we could run the interpolation function first, then a markdown translator.

**Comment by pdehaan** [comment]
Plus converting to Markdown would potentially require that we strip out some wrapper `<p>...</p>` tags (or not, depending on our parser).

But if we're concerned about translators using invalid HTML, I'm not sure switching to Markdown would yield less typos or malformed markup. Plus, some Markdown parsers still allow you to mix Markdown and HTML and it just ignores the HTML bits, unless we can somehow limit the markup to sanitize the input from the legal/l10n repos and we only support 3-4 tags and discard the rest.

**Comment by shane-tomlinson** [comment]
> But if we're concerned about translators using invalid HTML, I'm not sure switching to Markdown would yield less typos or malformed markup. Plus, some Markdown parsers still allow you to mix Markdown and HTML and it just ignores the HTML bits, unless we can somehow limit the markup to sanitize the input from the legal/l10n repos and we only support 3-4 tags and discard the rest.

True, a translator could still break the markdown, but my hunch is there is less of a chance because there will simply be less mark(up|down) to deal with. No `id`s, no HTML, the only special chars we would have initially are `[]()*`.  This feels reasonable.

I want to explicitly disable any HTML in the translated files - we would escape any ["special" characters](http://documentcloud.github.io/underscore/#escape) before running the markdown->HTML converter just to be sure. I don't see any `<p>...</p>`s to worry about, if we need that functionality in the future, we can try to accommodate it in another manner, perhaps using a different markdown tag + CSS styling.

**Comment by ckarlof** [comment]
I had a chat with @TDA and he expressed interest in tackling some web security problems, so this might be a good fit.

**Comment by pdehaan** [comment]
Ah good. He can take it.
I was experimenting today with running HTMLLint against a `<a href="foo">bar/a>` snippet, and it was passing without any issues. So either I'm failing to configure it properly, or I'm expecting the wrong output. But basically my sad attempt at converting the PO->JSON->HTML->HTMLLint still wouldn't have caught the malformed translation markup.

Running the same crappy/malformed markup through https://validator.w3.org/nu/ failed pretty fast and hard, which is good.

**Comment by pdehaan** [comment]
I also saw this module on npm the other day: https://www.npmjs.com/package/secure-handlebars

> _To automatically apply context-sensitive XSS output filtering for Handlebars_

Not sure if that would help us, but looked interesting.

**Comment by pdehaan** [comment]
> @shane-tomlinson: but my hunch is there is less of a chance because there will simply be less mark(up|down) to deal with.

As a person who watches the **legal-docs** repo, there have been a fair number of markdown errors that have come through my inbox. Although to be fair, those documents can get pretty complex. The most common errors are people doing links backwards like `()[]` or spaces that appear between the brackets `[] ()`. Those are both pretty hard to catch because Markdown just ignores things it doesn't understand. So generally I was using a Markdown engine to render all *.md files into *.html files and then grepping the *.html for remaining `[` characters.

Thankfully, our HTML markup is pretty simple in our l10n files, although it would mean we'd need to get ~15 of the strings re-translated to their markdown equivalents for each locale (per @zaach's https://github.com/mozilla/fxa-content-server/issues/2659#issuecomment-119273822).
