### ISSUE TITLE
Re-work email opt-in metrics from signup page

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2660]
Currently on the sign-up page, we log `email-optin.visible.[true|false]` events to tell whether the opt-in checkbox is visible, but we don't log an event if the user actually opts in.  Now that it's on general release, we should remove the visibility metrics and add one for the actual checking of the checkbox.

**Comment by shane-tomlinson** [comment]
> Currently on the sign-up page, we log email-optin.visible.[true|false] events to tell whether the opt-in checkbox is visible, but we don't log an event if the user actually opts in. Now that it's on general release, we should remove the visibility metrics and add one for the actual checking of the checkbox.

We have those metrics already:

* signup.checkbox.change.marketing-email-optin.checked
* signup.checkbox.change.marketing-email-optin.unchecked

The divergence in event name prefix is because the checked/unchecked events are handled generically in the [checkbox-mixin](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/checkbox-mixin.js) whereas the "visible" events are handled [as a one off](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/sign_up.js#L86) and we did not do a great job at coordinating.

The lack of knowledge of these events does point out that the [client-metrics doc](https://github.com/mozilla/fxa-content-server/blob/master/docs/client-metrics.md#signup) needs to be updated. Assigning that to me.

**Comment by rfk** [comment]
Oh, awesome!  I spent a least five minutes grepping for various combinations of "email" and "optin" befofe filing this, but I guess the checkbox mixin does it generally and so didn't show up in my search.

I also realized that the "visible" metric is still useful while we've got optin preffed off in other non-english locales, so I'll just close this issue out.
