### ISSUE TITLE
lint: Space after "!" not enforced

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2690]
Looking at a PR to server code:

![image](https://cloud.githubusercontent.com/assets/128755/8524068/c800d810-23c6-11e5-8ac6-e16f340d5b96.png)

We should have eslint or jscs catch this for us. @pdehaan @TDA ideas?

**Comment by pdehaan** [comment]
I can look into this.
It *may* be ESLint's [**space-unary-ops**](http://eslint.org/docs/rules/space-unary-ops) rule, but should be pretty easy to confirm or experiment.

**Comment by pdehaan** [comment]
Meh, will require more investigation... It does indeed look like the correct ESLint rule, but it also seemingly wants me to add spaces around `-` and `++`:

```
$ grunt eslint
Running "eslint:grunt" (eslint) task

grunttasks/connect-fonts.js
  36:75  error  Unary operator "-" must be followed by whitespace  space-unary-ops

grunttasks/l10n-supported-locales.js
  23:8   error  Space is required before unary expressions "++"    space-unary-ops
  28:8   error  Space is required before unary expressions "++"    space-unary-ops
  41:10  error  Unary operator "!" must be followed by whitespace  space-unary-ops
  46:10  error  Unary operator "!" must be followed by whitespace  space-unary-ops

✖ 5 problems (5 errors, 0 warnings)

Warning: Task "eslint:grunt" failed. Use --force to continue.

Aborted due to warnings.
```

So instead of `count++;` it now wants `count ++;`.

Comically, changing those to pass ESLint's quirkly rule logic, causes them to fail JSCS linting. Also, after fixing those 5 ESLint errors, the next subtask gives us 95 more.

**Comment by TDA** [comment]
I can take this @pdehaan

**Comment by pdehaan** [comment]
I think the solution may be to try linting this using JSCS, since it seems to give us a bit more flexibility in specifying operators.
I believe that [**requireSpaceAfterPrefixUnaryOperators**](http://jscs.info/rule/requireSpaceAfterPrefixUnaryOperators.html) is the right rule, and changing our .jscsrc file to this seems to find 7 code style errors in the `jscs:server` task:

```
"requireSpaceAfterPrefixUnaryOperators": ["~", "!"],
```

**Comment by pdehaan** [comment]
It looks like adding the `!` operator to the .jscsrc file gives about 7 errors. After fixing those, I get about 18 more. Should be easy fixes, but may mean that we also need to add spaces around `!! foo` instead of just `!!foo` like we have now.

**Comment by TDA** [comment]
@pdehaan @vladikoff I think Peter's approach of using JSCS instead of ESLint is right. So i am gonna do just that :)
