### ISSUE TITLE
Now that avatars have launched, remove "You are signed in as"

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2761]
Now that avatars have launched, remove "You are signed in as" and just show the email (which could also be the display name in the future).

**Comment by shane-tomlinson** [comment]
@ryanfeeley or @johngruen - could you give some more context?

**Comment by vladikoff** [comment]
basically from 
![image](https://cloud.githubusercontent.com/assets/128755/9064385/3f936228-3a9a-11e5-9a75-da71bf56013e.png)

to 
![image](https://cloud.githubusercontent.com/assets/128755/9064395/4b8e2220-3a9a-11e5-8e69-1f08077da2a4.png)

but this should be automatically fixed in settings 2.0
cc @ryanfeeley

**Comment by pdehaan** [comment]
FWIW: here's the latest UX from https://uxwip.dev.lcip.org/settings, which says:

```html
<p class="signed-in-email-message">{{#t}}Hello, {{/t}} {{email}}</p>
```

![manage_account__account_picturedisplay_namecommunication_preferencespassworddelete_account_and_mozilla_tabzilla_at_v0_3_0](https://cloud.githubusercontent.com/assets/557895/9065749/80dd41d4-3a88-11e5-8497-492a5a03becf.png)

**Comment by ryanfeeley** [comment]
Agreed, no longer relevant.
