### ISSUE TITLE
Automatically remove typographic orphans in our UI copy

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2777]
![orphans](https://cloud.githubusercontent.com/assets/68213/8759140/28241a06-2ca3-11e5-9bfe-9235ebf236bf.gif)

By replacing the last space in any line with a non-breaking space, our copy becomes more quickly readable, and therefore more usable.

Something like:
http://matthewlein.com/widowfix/

**Comment by pdehaan** [comment]
It'd be nice if there was a way to do this without adding a bunch of `&nbsp;` chars to the strings since that would be a pretty big l10n hit on the localizers.

**Comment by TDA** [comment]
@pdehaan @ryanfeeley I dont think there is another *foolproof* way to do it. IIRC widows and orphans in css only apply to lines, not words. We could try using the 'vw' - viewport width to resize the words instead. But that is still not reliable IMO. I favor the nbsp approach over all these. Anything I am missing?

**Comment by shane-tomlinson** [comment]
JavaScript can make this a reality, but I'm not convinced on the need for this other than a "nice to have because it would make things look better."

I'd say if we want to do this, we should look for a library that provides the functionality. If one does not exist, we should create a standalone library and integrate it with the content server.

**Comment by vladikoff** [comment]
Closing until really needed
