### ISSUE TITLE
Improve usability of sync upgrade by presenting users this message on the content server

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2786]
Our current sync upgrade experience could use some messaging on the login and registration form so that users don't just try and log in with their old sync account (got an email that someone did this).

PROPOSED:
<img width="989" alt="migration" src="https://cloud.githubusercontent.com/assets/68213/8785498/0953cae0-2ef6-11e5-9756-a039e5b57924.png">

**Comment by rfk** [comment]
Sync migration is in full swing, if anyone has the bandwidth it'd be great to get this into train-43

**Comment by shane-tomlinson** [comment]
> Sync migration is in full swing, if anyone has the bandwidth it'd be great to get this into train-43

Lots of things are in full swing, we sure could use some of the relative prioritization we've been discussing.

**Comment by vladikoff** [comment]
![](http://v14d.com/i/55b0073edcc68.png)

**Comment by vladikoff** [comment]
is 41.72% in the past week worth adding the note for?

**Comment by ryanfeeley** [comment]
I think so!

**Comment by rfk** [comment]
Do we suspect that people are abandoning the migration because of this, or are they succeeding despite a mildly confusing experience?

It's also important to consider absolute numbers here, which are most easily visible on this tracking dashboard:

  https://metrics.services.mozilla.com/sync-dashboard/

Each of the peaks on the "new migrations per day" graph corresponds to us bumping the percentage migration throttle, and we've just finished bumping it all the way up to 100%.  I expect this means we'll quickly see a dropoff in the number of migrations attempts per day, down to maybe 5k per day or fewer over the coming few months.

That is not a substantial fraction of our daily account signups, and the fraction will only decrease with time.
