### ISSUE TITLE
iframe checking doesn't verify port match?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2855]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1188458

--------------------------

Steps to reproduce:

* Create a trusted FxA client whitelisted for the site http://some.site/
* Using the client lib (https://github.com/mozilla/fxa-relier-client) do a sign-in from the same domain but on a different port like http://some.site:8080/ : 

var fxaRelierClient = new FxaRelierClient(clientId);
fxaRelierClient.auth.signIn({ui: 'lightbox'});

I would expect this to cause an error because the port is different, something like: 

**Error: Firefox Accounts can only be placed into an IFRAME on approved sites**

but it does not. It lets you sign in using the iframe without error.

If an attacker got through on a different port then they could maybe do damage?

**Comment by shane-tomlinson** [comment]
@rfk - I just tried this locally, the iframe checking seems to be working fine here. Do you have more concrete STRs? 

My STRs are create a 2nd 123done instance on port 8081 with everything else about that configuration the same. Same client_id, same hostname, same everything.

Open http://127.0.0.1:8081 instead of http://127.0.0.1:8080

### 123done on the incorrect port
![screen shot 2015-07-30 at 13 31 31](https://cloud.githubusercontent.com/assets/848085/8983116/63f1f938-36bf-11e5-88b0-1c3beeeb850b.png)

### 123done on the correct port

![screen shot 2015-07-30 at 13 34 10](https://cloud.githubusercontent.com/assets/848085/8983149/b4c4c052-36bf-11e5-9d3a-910539943ff7.png)

**Comment by shane-tomlinson** [comment]
The iframe origin check code checks the origin, as reported by the browser in a [postMessage event's origin field](https://github.com/mozilla/fxa-content-server/blob/93f3641eb7c140ea979295cdd9673e8cadf938ed/app/scripts/lib/origin-check.js#L55), against a list of allowed origins. The list of allowed origins for an OAuth relier is a [single origin](https://github.com/mozilla/fxa-content-server/blob/93f3641eb7c140ea979295cdd9673e8cadf938ed/app/scripts/lib/app-start.js#L295-L298) based on [the redirect_uri returned from the oauth server](https://github.com/mozilla/fxa-content-server/blob/93f3641eb7c140ea979295cdd9673e8cadf938ed/app/scripts/models/reliers/oauth.js#L172).

**Comment by kumar303** [comment]
Hi. Thanks for checking. It's very likely I got confused because we do have a legitimate client set up on our dev domain at a different port. I trust your isolated test case better so feel free to close :)
