### ISSUE TITLE
Protocol design and work breakdown to support Device Handshake

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2917]
Web-based logins for sync on Fennec need to land in Firefox 43, per this user-story bug: https://github.com/mozilla/fxa/issues/48

We need to settle on the details of our approach and sketch out a breakdown of the work.  I'm filing this bug so we can explicitly include that in our work for iteration 43.1, feeding into concrete implementation in the 43.2 cycle.

**Comment by shane-tomlinson** [comment]
ref #2916

**Comment by rfk** [comment]
@shane-tomlinson based on the "no inbound requests" from the fennec team, should we just close out this bug?

**Comment by shane-tomlinson** [comment]
@rfk - we are going to have the handshake, once we dig in there. We can open a new bug for that. Closing.

**Comment by shane-tomlinson** [comment]
I'm re-opening this. We *are* going to have work to do here, including the handshake, but also any extra events like those requested in #2731 and #2771

**Comment by shane-tomlinson** [comment]
cc @zaach, @ncalexan.

**Comment by zaach** [comment]
From what I've been able to glean, here's what useful information the client could provide in the handshake:

- Names of commands:
  - CAN_LINK_ACCOUNT
  - CHANGE_PASSWORD
  - DELETE_ACCOUNT
  - LOADED
  - LOGIN
  - (NEW #2731) LOGOUT

- UX configuration:
  - haltAfterResetPasswordConfirmationPoll
  - haltAfterSignin
  - haltBeforeSignUpConfirmationPoll
  - (NEW #2771) show "proceed to settings" button after signup_complete

- Other capabilities
  - (NEW #2303) Choose What to Sync (web_v1)

- type of client

**Comment by rfk** [comment]
IIUC the handshake didn't necessarily block fennec web login.  Do we plan to revisit that in light of the above, or should we treat "device handshake" as a new separate feature milestone?

**Comment by rfk** [comment]
A details-level question from Nick in IRC, capturing here so we don't lose track of it:
"""
Do we care about including the Fennec release channel in Sync/FxA/services user-agent strings?
"""

**Comment by shane-tomlinson** [comment]
Capturing some context from a call with @zaach:

* The initial handshake will be done via message passing over WebChannels. The content server will initiate the handshake by sending a TBD message. Fennec will respond. The content server should timeout if no response is received after some reasonable amount of time. Note, 100ms is [not a reasonable amount of time](https://github.com/mozilla/fxa-content-server/pull/2948/files#diff-122a48e7442733f0d0d2de01769eb9c9L32)
  * In Zach's [note above](https://github.com/mozilla/fxa-content-server/issues/2917#issuecomment-137590716) Fennec will respond with both UX configuration and "other capabilities".
* It is possible the content server should send some notion of a version. I think that since the content server is easy to update whereas Fennec versions can stay around forever, the primary version needed will be from Fennec->content server saying which version of the protocol it understands. The version can be indicated using the `context` query parameter, e.g., `context=fx_fennec_v1`.
* Subsequent messages will be sent from the content server, in @zaach's not above, these are listed as "Names of commands."
* The only command that currently needs to be responded to is `CAN_LINK_ACCOUNT`

**Comment by shane-tomlinson** [comment]
Reference https://bugzilla.mozilla.org/show_bug.cgi?id=1204930.

**Comment by rfk** [comment]
@shane-tomlinson per IRL discussion last week, I created a separate milestone for "device handshake" work.  Since this bug seems to contain pretty much only device-handshake stuff, I'm morphing it into a breakdown bug for that milestone to keep the context around.

**Comment by rfk** [comment]
Also one thing I noticed that's not included in the list in https://github.com/mozilla/fxa-content-server/issues/2917#issuecomment-137590716, is the ability to say whether someone is logged in to the device and to give access to their sessionToken if so.  We may want to punt on implementation of that for a while, but let's keep it in mind while designing the handshake.

**Comment by shane-tomlinson** [comment]
This should be be a feature card in Aha. Closing.

**Comment by shane-tomlinson** [comment]
https://mozilla.aha.io/features/FXA-50
