### ISSUE TITLE
new service to help keep dependencies up to date: greenkeeper.io

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#3124]
I'm surprised @pdehaan hasn't already filed something about this ;). But in case y'all haven't heard there's a new service that helps keep your dependencies up to date: http://greenkeeper.io/

It sends a pull request whenever a dependency is updated so, if the integration tests pass, you can just click merge to upgrade. The PR also includes the changelog of the updated dependency. Neat stuff.

**Comment by vladikoff** [comment]
I doubt greenkeeper will be able to update shrinkwrap the way we want to, but haven't tried it ...
With Grunt we decided to stay away from constant dependency notifications and badges because if the current code is stable why keep trying to get latest updates (unless it is a security related update).

**Comment by zaach** [comment]
Yeah, if we're still keen on updating deps outside of security fixes, as we currently do kind of ad-hoc, this might be nice if it's indeed one-click and not too noisy. Otherwise, meh.
