### ISSUE TITLE
Improve messaging when cookies/localstorage are disabled

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3129]
When cookies or localStorage are disabled, we currently show messages saying things like "please enable cookies" and "cookies are still disabled".  Unfortunately it's not always cookies that are the problem.  As shown in [1], users can find it frustrating if they've apparently enabled cookies but are still seeing this message.

Let's make two tweaks to clarify the situation for users:

1.  Have separate checks and messaging for "cookies are not enabled" and "localstorage is not enabled".
2.  Include a "help" link in the error messaging, going out to a SUMO article with steps to debug, settings to switch on, etc.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1210362

**Comment by shane-tomlinson** [comment]
I'm kinda "meh" on prioritizing dev cycles for this, but it keeps cropping up. Both [disabled localStorage](https://github.com/mozilla/fxa-content-server/issues/738) and [dom.storage.enabled: false](https://github.com/mozilla/fxa-content-server/issues/1140) are known issues that have been discussed. We have no numbers to back up this theory, but we think for the vast majority of people, localStorage is disabled because cookies are disabled. Unfortunately, we keep seeing this report from folks that have `dom.storage.enabled: false`. Currently we *only* check whether [session/localStorage is disabled](https://github.com/mozilla/fxa-content-server/pull/2708), the actual cookie check was removed, because again, for most people, we think localStorage is disabled because cookies are disabled.

Re-adding the cookie check will partially revert #2708 and #2721, and we'll have to fetch config from the server earlier in the startup process, and add a new screen. I'm not sure any value is added on collecting metrics on the % of people that have local/sessionStorage disabled vs % of people that have cookies disabled.

Ref #738, #1140, #2479, #2480, #2677, #2708, #2721

**Comment by rfk** [comment]
Fair.  What if we just do (2) and make a SUMO page for common login errors.  We could re-word this page a little and link to an FxA-specific article rather than general information about cookies:

![screen shot 2015-10-09 at 11 06 10](https://cloud.githubusercontent.com/assets/34695/10383032/cdf3eb6e-6e75-11e5-97aa-605dc9485154.png)

We could also link to it for other login errors that users might like help with, such as:

![screen shot 2015-10-09 at 11 09 44](https://cloud.githubusercontent.com/assets/34695/10383078/4a47f124-6e76-11e5-8c7b-cee3245a177f.png)

Thoughts?  (/cc @ryanfeeley)

**Comment by ryanfeeley** [comment]
What if the message covered both like:

> **Cookies and local storage are required.**
> Please enable cookies and local storage in your browser to access Firefox Accounts. Doing so will enable functionality such as remembering you between sessions and [local storage example].

I don't like example #2 because will misdirect users who have forgotten their password.

**Comment by rfk** [comment]
> What if the message covered both 

:+1:

**Comment by ryanfeeley** [comment]
Removing second example because for us offline is used the way cookies are understood to be used by both. Better copy:
> **Cookies and local storage are required.**
> Please enable cookies and local storage in your browser to access Firefox Accounts. Doing so will enable functionality such as remembering you between sessions.

**Comment by vladikoff** [comment]
:+1:

**Comment by vladikoff** [comment]
This is totally ready, someone please send a PR

**Comment by NothingCanPlayVTT** [comment]
I got my bug merged into this one but my cookies were not disabled.  The site is just broken for Firefox.

**Comment by rfk** [comment]
Hi @NothingCanPlayVTT, have you customized the privacy settings in Firefox in any way?  Do you see the same issue if you create a brand new Firefox profile and try to login to the addons site through there?

**Comment by rfk** [comment]
Oh nevermind, I see you filed https://github.com/mozilla/fxa-content-server/issues/4778, let's follow up in that one.
