### ISSUE TITLE
Password Strength Checker Experiment follow up

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3178]
@shane-tomlinson what should we do with the password experiment? 

should we disable / remove it from the source or keep improving it? 

(the fxa-password-strength-checker.js one)

**Comment by shane-tomlinson** [comment]
@shane-tomlinson to convert graphs from cumsum to %.

**Comment by rfk** [comment]
The top-line open question is: what percentage of signups are using a weak password?  Any decisions about whether or how to follow up on this work will need to come from that metric.

**Comment by TDA** [comment]
@tda Tagging myself so I can get updates :dancer:

**Comment by vladikoff** [comment]
> what percentage of signups are using a weak password? 

Measuring Signup Success vs Weak passwords (In this case AKA our bloom filter HIT!):

 
![image](https://cloud.githubusercontent.com/assets/128755/11073506/eacb3614-87b8-11e5-8aa1-52ca4838f964.png)

Gives us that ~ 3% use a weak password to our bloom filter knowledge (in the 8-12 password length range + other requirements to engage the bloom filter)

**Comment by rfk** [comment]
Thanks @vladikoff!  What about the percentage of users whose password fails *any* of our weakness-filtering criteria?  I ask because I think there are two open questions here:

1. Should we do anything at all about detecting weak passwords?
2. Should we use a bloom filter as an extra layer of checking?

**Comment by shane-tomlinson** [comment]
As @rfk says, checking *only* the bloom filter stats doesn't really provide an answer to the question "is the password weak?" The bloom filter is the last in a series of filters.

The sequence is:

1. Is the password empty? Error.
1. Is the password < 8 chars? Error.
1. Is the password >= 12 characters? Good to use.
1. Is the password between 8 and 11 chars (inclusive)?
  1. Is the password all letters? Error.
  1. Is the password all numbers? Error.
  1. Is the password in the reduced bloom filter? Error.
  1. Password is good to use.

The reduced bloom filter starts with the top 50k passwords. 

1. Remove all entries that are 1-7 characters (inclusive) in length. 
1. Remove all remaining entries that are >= 12 chars. 
1. Remove all remaining entries that are all numbers. 
1. Remove all remaining entries that are all letters.

These entries are removed because we have other checks for those.

So you can see, the bloom filter is only checked if the password is between 8 and 11 characters, not all letters, and not all numbers. Passwords not in this set are considered invalid or automatically accepted.

What I'd like to see is for the library to be used for all password validation so that we can remove the password validation logic from the core content server code.

The results also do not paint a full picture because the password filter library is not actually used, is not catching people, and is not forcing users to re-enter a password if it doesn't meet the above criteria. If the library were used, the percentages would likely change because users entering a letter only password (8-11 chars) would have to try again. Users entering a number only password (8-11 chars) would have to try again. Users caught in the bloom filter would have to try again. We currently allow *any* password >= 8 chars.

**Comment by shane-tomlinson** [comment]
More thoughts -

A more strict password checker may lead to:

1. Lower sign up rate because of increased friction.
1. Higher password reset rate when the user tries to re-authenticate on the same device or sign in on a new device.

The FxA password is asked for on signup, on re-auth on the same device, and when signing in on a new device. Users are probably more likely to forget a strong password that they enter infrequently.

Asking users to enter a strong password on mobile devices is also frustrating. If we force stronger passwords, we may want to add a "verify your password" field. I already find in testing on a desktop with a real keyboard that I sign up with an incorrect password more frequently than I like.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - thoughts?

**Comment by TDA** [comment]
I agree with @shane-tomlinson on the demerits of making the password strength stronger/stricter. We would definitely need a "re-enter/verify your password" field. Wouldn't that actually make people not want to sign up?

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vladikoff So you are saying that ~ 3% are in states 4i–4iii?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - no, 3% are in 4iii

**Comment by vladikoff** [comment]
@shane-tomlinson @vladikoff So you are saying that ~ 3% are in states 4i–4iii?

4i–4iii is ~6-7%

![image](https://cloud.githubusercontent.com/assets/128755/11131729/1c05de4e-895a-11e5-8fb9-95ea5c4b1802.png)

**Comment by ryanfeeley** [comment]
So we think that approximately 6–7% of users have lousy passwords. I would like us to offer these users some help (that they can decline).

**Comment by TDA** [comment]
@ryanfeeley Like a tooltip? or the password playground thing? :D

**Comment by ryanfeeley** [comment]
@TDA Any educational link, though I still think the password playground should be made.

![Password Playground](https://www.lucidchart.com/publicSegments/view/75c0325c-1e0b-4e10-b2b0-6ae53bf521f5/image.png)

**Comment by TDA** [comment]
@ryanfeeley I will be there this summer, and I think the playground is nice too, just saying *wink wink*.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Time to revive? Add something like this?
![45f063e2-ecca-11e3-8436-ff36ac6587b3](https://cloud.githubusercontent.com/assets/68213/14473956/9c58fa28-00c8-11e6-8d0b-cd58fd82d3d8.png)

**Comment by pdehaan** [comment]
@ryanfeeley In your screenshot above, does that mean if the user gets the red "Too predictable, try again." error message, they can't submit the form? Or would they be able to submit anyways and ignore the feedback?

**Comment by ryanfeeley** [comment]
@pdehaan Good question, I should have annotated them. The first one acts like an incorrect password in that the form cannot be submitted. The second lets you dismiss it by submitting (and optionally pressing X).

**Comment by TDA** [comment]
@ryanfeeley @shane-tomlinson If this is indeed being revived, I call dibs on it :)

**Comment by vladikoff** [comment]
seems like this is https://github.com/mozilla/fxa/pull/150 now, closing.
