### ISSUE TITLE
Show the default avatar while the real avatar is loading on the hinted sign up page

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#3277]
Saw this on a dev box...half way through the GIF below I'm logging in to FxA. In the time it takes the avatar to load, we should really be showing the default avatar and not just a big blank disk. 

@ryanfeeley 

![town2](https://cloud.githubusercontent.com/assets/3323249/11076266/be3615fe-87f1-11e5-894b-3a945093696d.gif)

**Comment by vladikoff** [comment]
## Actual

![](http://v14d.com/i/564a14694df7c.jpg)

## Expected

Show default avatar

**Comment by jstrutz** [comment]
This is a good bug to get my feet wet - i'll take a crack at it.

**Comment by rfk** [comment]
@jstrutz sounds good!  I've created an experimental "fxa-community" team and added it to this repo, which should make it easier for us to e.g. @-mention you and mark issues as assigned to you.

**Comment by jstrutz** [comment]
Thanks @rfk!

As for the bug, it looks like this behavior occurs when the user is known to have a ProfileImage, and thus we [explicitly opt](https://github.com/mozilla/fxa-content-server/blob/cd3a97566558561ed2c81aab2fc6b837590249bd/app/scripts/views/mixins/avatar-mixin.js#L33) to not show a default avatar while the ProfileImage is loading, since the ProfileImage may arrive moments later, awkwardly flashing the default avatar.

If we want to tweak this, here are a couple of ideas:
* If the user's ProfileImage has not loaded within X msecs, show the default avatar anyway (can we get X right?)
* Use a CSS transition to make the appearance of the user's profile image after the default avatar less jarring, and then more readily show the default avatar
* Create a purpose-built "loading avatar" spinner/animation, to more explicitly show what is going on

Any thoughts?  I'll /cc @zaach as well, since he has dealt with this some in conjunction with his work on #1804

**Comment by rfk** [comment]
> If the user's ProfileImage has not loaded within X msecs, show the default 
> avatar anyway (can we get X right?)

Yeah, this seems hard to get right in practice.

> Use a CSS transition to make the appearance of the user's profile image
> after the default avatar less jarring, and then more readily show the default avatar

This sounds neat, assuming the default avatar itself will load quickly enough for the effect to be effective.

> Create a purpose-built "loading avatar" spinner/animation, to more explicitly show what is going on

And this could be a good follow-on after the above option, to make it even more obvious what's happening.

**Comment by jstrutz** [comment]
I put together a little mockup of a spinner, visible at http://jstrutz.github.io/fxa-avatar-spinner/ , code at https://github.com/jstrutz/fxa-avatar-spinner .  It is done with css, so we can avoid waiting for another asset to load to show it.  Any feedback?

What is the procedure for contributing slightly "designey" things like this?  Is there someone specific I should show this to?

**Comment by rfk** [comment]
ping @ryanfeeley for "designey" things

**Comment by vladikoff** [comment]
see existing spinners that we use under https://github.com/mozilla/fxa-content-server/tree/master/app/images such as https://github.com/mozilla/fxa-content-server/blob/master/app/images/spinnerlight%402x.png

**Comment by ryanfeeley** [comment]
@jstrutz I'd love to avoid using PNGs for this if we can. I toyed with it a bit until it looked a bit more like this:
<img width="263" alt="screenshot 2015-11-29 22 23 17" src="https://cloud.githubusercontent.com/assets/68213/11462859/d27b99da-96e7-11e5-92b0-1c352ed6a8d0.png">

75% background size on .avatar-loading-spinner::before

The fade in is nice too. Appreciated!!

**Comment by jstrutz** [comment]
Thanks @ryanfeeley ; I'll come back with a proper PR, with your changes included.

**Comment by vladikoff** [comment]
This was fixed!
