### ISSUE TITLE
Keyboard "enter" on the Fx "merge warning" dialog does not continue to next screen

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3340]
#### STR

1. Using an Fx profile set up for local dev, open http://127.0.0.1:3030/signup?service=sync&context=fx_desktop_v2
1. Sign up an verify as user A.
1. Disconnect from Sync.
1. Using the same profile, open http://127.0.0.1:3030/signup?service=sync&context=fx_desktop_v2
1. Sign up as user B.
1. When the Fx "merge warning" appears, use the keyboard to tab to "continue", press enter.
1. Wah wah.

#### Expected
FxA continues to Choose what to Sync

#### Actual
The mouse must be used to continue to Choose what to Sync

![no-keyboard-continue](https://cloud.githubusercontent.com/assets/848085/11931322/9fb123a0-a7e3-11e5-82d2-fb17dd935845.gif)

-----------------------------

I am unsure if this is a browser issue, an FxA issue, or both.

cc @mhammond, @vladikoff

**Comment by philbooth** [comment]
This is where the dialog is initialised:

* https://dxr.mozilla.org/mozilla-central/source/browser/base/content/aboutaccounts/aboutaccounts.js#80-85

The args to `confirmEx` are documented here:

* https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPromptService#confirmEx%28%29
* https://dxr.mozilla.org/mozilla-central/source/embedding/components/windowwatcher/nsIPromptService.idl#173-215

It's very easy to change things so that `Continue` has the initial focus instead of `Cancel`, then pressing `Enter` will do what is requested here. However that won't address the bigger issue of the keyboard not working to switch focus between the `Continue` and `Cancel` buttons, which seems beyond our scope.

With that in mind, I thought I should check that we definitely still want to make this change. Do we?

**Comment by vladikoff** [comment]
>However that won't address the bigger issue of the keyboard not working to switch focus between the Continue and Cancel buttons, which seems beyond our scope.

It is an accessibility setting in OS X, in my case with it enabled i can use TAB and SPACE to confirm selection. See http://superuser.com/questions/473143/how-to-tab-between-buttons-on-an-mac-os-x-dialog-box

Otherwise we can file a bugzilla bug to see if we want the dialog changed, but @mhammond probably knows why this was developed this way.

**Comment by mhammond** [comment]
I believe "cancel" being the default is desired, so we shouldn't change that. OSX keyboard semantics are indeed dumb (eg, try using the "tab" key to navigate in about:preferences without that ally setting @vladikoff mentioned) but I don't know a huge amount about it - if this dialog behaves differently than others in that regard we should work out how to fix that. I believe it works fine on Windows.
