### ISSUE TITLE
app-start.js::initializeAuthenticationBroker is ripe for refactoring

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3375]
This is probably another one of those things that we'll never get round to and end up closing the issue. But I just noticed the amount of repetition in `initializeAuthenticationBroker`. Would it be nicer if we perhaps looped through some data structure that described each of the auth brokers, instead of having that long chain of separate conditions?

**Comment by vladikoff** [comment]
@larissagaulia I think you mentioned this to me ^

**Comment by rfk** [comment]
IIUC this was fixed in https://github.com/mozilla/fxa-content-server/pull/4335

**Comment by shane-tomlinson** [comment]
#4335 was to use object-shorthand, @philbooth's suggestion is different. Instead of using a giant if/else-if/else statement to figure out which auth-broker to use, have a data structure w/ a lookup function that determines which to use. Because #4335 addresses a different problem, I left this open.

Re-opening to let @philbooth make the determination whether he still wants to see this done.

**Comment by philbooth** [comment]
> Re-opening to let @philbooth make the determination whether he still wants to see this done.

Yes, let's leave this open and if nobody else has taken it by the time I've finished the metrics stuff, I promise to do it so it doesn't hang around on the backlog for *another* 10 months.
