### ISSUE TITLE
Delay account creation until after the sync datatype selection screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3481]
![screenshot 2016-02-05 15 10 59](https://cloud.githubusercontent.com/assets/68213/12857902/cd1e3778-cc1a-11e5-9784-b18f02909acb.png)

CURRENT:

1. In Nightly user completes registration form and waits on choose-what-to-sync-page
2. In other client, user verifies their email address
3. Choose-what-to-sync page does not transition to account verified state (prefs remains as anonymous)

EXPECTED:

1. User should be verified and begin syncing based on current sync selections

**Comment by vladikoff** [comment]
Scary!

**Comment by rfk** [comment]
Nice catch @ryanfeeley.  I'm not sure I have my head around the concurrent flows here.  As a user, seeing that blue button there that still says "sign up", I feel like I'd be kinda confused to learn that I'd already successfully signed up and started syncing without having to click that button.

Is the current behaviour an artifact of us sending the verification email before the user completes the choose-that-to-sync screen?  Could it be simplified by waiting until all screens in the flow are completed before we send the verification email?

**Comment by ryanfeeley** [comment]
True, we shouldn't just auto-submit when the user verifies their email.  A very common flow will be the user submitting the registration form, pausing in looking at the screen, feeling that vibration in their pocket, and verifying brother mobile device.  Perhaps if the user has seen, but not submitted the choose what to sync screen, we should show it to them again after they verify their email.  The other option is to delay sending the email until that choose what to sync screen is submitted.

**Comment by shane-tomlinson** [comment]
> Nice catch @ryanfeeley. I'm not sure I have my head around the concurrent flows here. As a user, seeing that blue button there that still says "sign up", I feel like I'd be kinda confused to learn that I'd already successfully signed up and started syncing without having to click that button.
> 
> Is the current behaviour an artifact of us sending the verification email before the user completes the choose-that-to-sync screen? Could it be simplified by waiting until all screens in the flow are completed before we send the verification email?

The current behavior began with the OAuth flow where the user must grant permissions and was then co-opted by the CWTS flow. The auth server provides no way to determine whether an account exists for a given email address; the only way is to submit the form and attempt to sign up the user. 

We needed to know the user's status otherwise we could not show "Already have an account? Sign in". Otherwise, the user only discovers after granting OAuth permissions that they should be signing in instead of signing up.

With #3413, the requirement is to sign users in from the sign up page, [so no more "Already have an account? Sign in" message](https://github.com/mozilla/fxa-content-server/pull/3413/files#diff-a74f50cdf368ca0e8f24665d7488f14dL336). #3413 requires some unnatural hoops to be jumped through that would be greatly simplified if we could just query the auth server for an email's status. So could #3057.

**Comment by shane-tomlinson** [comment]
> Could it be simplified by waiting until all screens in the flow are completed before we send the verification email?

No, not unless we have an alternative mechanism to determine whether the email already is already registered.

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @rfk - I'm putting this in backlog for now. If either of you want this prioritized, bump it up!

**Comment by rfk** [comment]
IIUC, the problem here is the same as the one underlying #3501, and the proposed solution is to avoid sending the verification email until *after* they've completed the CWTS screen.  @shane-tomlinson if that matches your understanding, can you please close this issue and #3501 and replace them with a concrete implementation bug based on your proposal in https://github.com/mozilla/fxa-content-server/issues/3501#issuecomment-183053459 ?

**Comment by rfk** [comment]
>  @shane-tomlinson if that matches your understanding, can you please close this issue and #3501
> and replace them with a concrete implementation bug based on your proposal in #3501 (comment) ?

Assigning to @shane-tomlinson to check if that's the right way to proceed.

**Comment by rfk** [comment]
(I changed the issue title to reflect my understanding of the path forward for this bug)

**Comment by rfk** [comment]
@ryanfeeley I'm trying to get a sense of priority for this by looking at the "% of non-Android CWTS drop-off" graph at [1].  I reconfigured it a bit to present a single percentage figure calculated as follows:

* `a` = count of `fxa.content.screen.choose_what_to_sync`
* `b` = count of `fxa.content.screen.choose_what_to_sync` with `agent_os_family=android`
* `c` = count of `fxa.content.choose_what_to_sync.submit`
* `d` = count of `fxa.content.choose_what_to_sync.submit` with `agent_os_family=android`
* `a - b` = number of desktop users who saw the CWTS screen
* `c - d` = number of desktop users who completed the CWTS screen
* graphed as `(((a - b) - (c - d)) / (a - b)) * 100` to get "percentage of desktop users who failed to complete the CTWS screen

Here's a snapshot of it over the last month:
![screen shot 2016-03-07 at 15 39 28](https://cloud.githubusercontent.com/assets/34695/13560976/d7047e5a-e47a-11e5-869e-932b7e1504f4.png)

It's spiky, I suspect because the overall number of these events is quite small.  But damn, even discarding outliers, those peaks are pretty high in percentage terms.  Can you please check my math here?

It may be worth seeing what we can do about this before switching on CTWS for the first-run flow, unless that happens automatically when we ship the enabling train.  (Also, this sort of thing really *really* makes me want to see our metrics in terms of "devices connected per day" rather than the current "accounts created per day"...)

[1] https://app.datadoghq.com/dash/57926/fxa-content-server---sync

**Comment by rfk** [comment]
So I suspect this is now a dup of https://github.com/mozilla/fxa-content-server/issues/3502#issuecomment-183053661 and Shane's comment in that bug is the way forward.  I'm closing this one, let's do further discussion over there.
