### ISSUE TITLE
Improve "Choose What to Sync" email experience

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3502]
More detail tba

**Comment by vladikoff** [comment]
how to do deal with bounced emails?

**Comment by rfk** [comment]
> how to do deal with bounced emails?

Would it help if we had https://github.com/mozilla/fxa-auth-server/issues/721 on the server side?

**Comment by shane-tomlinson** [comment]
Copying my comment from https://github.com/mozilla/fxa-content-server/issues/3501#issuecomment-183053459:

An alternative, possibly simpler, proposal:

Use the "is this email address registered" API endpoint that @vbudhram is working on. When the user clicks "submit" on the signup page, don't sign up (like we currently do). Instead, check whether the email is registered. The key is we need to know whether the email is registered *and verified*. Just registered is not enough, because a user who has signed up and not verified can sign up again with a new password. If the email is not signed up and verified, send the user to CWTS. When the user completes CWTS, sign up the user and notify the browser.

This proposal fixes multiple problems:

1. Expectations are better met that an email is not sent until the signup flow is completed. Receiving an email midway through the flow feels "off."
1. Users who do not complete CWTS and verify their email addresses are not currently signed in to Sync. Unless the user figures out they need to sign in again from about:preferences#sync, these users receive no value from FxA and probably drop off. If these users are not signed up to begin with, our overall signup numbers may drop but our retention numbers should increase.

**Comment by vbudhram** [comment]
Ref: https://github.com/mozilla/fxa-auth-server/pull/1184 for updated account status

**Comment by vladikoff** [comment]
Talked to @ryanfeeley about this and we can add polling to CWTS screen and submit form for the user if they verified their account somewhere else or in the same browser. 

Not to worry though, when you login to sync to get to about:prefs. That is where you can change your sync options.

**Comment by shane-tomlinson** [comment]
> Talked to @ryanfeeley about this and we can add polling to CWTS screen and submit form for the user if they verified their account somewhere else or in the same browser.
>
> Not to worry though, when you login to sync to get to about:prefs. That is where you can change your sync options.

I have concerns about adding polling to the CWTS screen, it seems like we are going to open a can of worms. Rather than adding more code and edge cases to worry about, I propose we do less - just not send the email until after the CWTS screen has been submit.

**Comment by rfk** [comment]
> just not send the email until after the CWTS screen has been submit.

I also think this would be a better experience overall; I wonder whether it's more or less work to implement this than it would be to add polling.

> Use the "is this email address registered" API endpoint that @vbudhram is working on

Remember that this endpoint is rate-limited; can we profitably use it while providing a sensible fallback experience when rate-limiting kicks in?

**Comment by vladikoff** [comment]
> I have concerns about adding polling to the CWTS screen, it seems like we are going to open a can of worms. Rather than adding more code and edge cases to worry about, I propose we do less - just not send the email until after the CWTS screen has been submit.

Up to @ryanfeeley. Ryan Feeley, what were the issues if we send the email after choose what to sync?

**Comment by shane-tomlinson** [comment]
> Remember that this endpoint is rate-limited; can we profitably use it while providing a sensible fallback experience when rate-limiting kicks in?

Now that we have [signin from signup](https://github.com/mozilla/fxa-content-server/pull/3413), I don't think we should provide a fallback, otherwise the rate limiting provides little value. 

Thinking through the "normal" flows:

1. User fills out form, submits
* Check if email is registered __and__ verified.
  * If email is registered and verified, attempt to sign in the user. 
    * If the password is correct, sign in the user.
    * If the password is incorrect, show the user the error message that allows a transition to the signin screen.
      * The user can attempt to sign in again after modifying the form, re-triggering step 2. (note, rate limiting could occur here in either the check email *or* the signin).
  * If the email is not registered or verified, send them to CWTS.
    * Once CWTS is filled out, send the email, notify the browser, go to the "confirm your email" screen.

Under normal circumstances, a follow on action always occurs, the user is not blocked on whether the email is registered/verified or not.

For users that are already signed up and verified, the rate limiting effects should be similar, or maybe better depending on how user actions are bucketed by the customs server. If a user is already signed up, we first try to re-sign them up, see they are verified, then sign them in. These users already see two hits to customs.

Perhaps the [try again after x minutes](https://github.com/mozilla/fxa-bugzilla-mirror/issues/48) message is sufficient?

**Comment by vladikoff** [comment]
Renamed the issue. @ryanfeeley @shane-tomlinson I think I lost context re: what we want to do here exactly. might need to revisit.

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by vladikoff** [comment]
Not actionable since July, let's revisit this with a fxa-features approach if we still want to make changes to this.
