### ISSUE TITLE
Emit flow.begin event at the start of the index route handler

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3550]
In order to implement the new [time-taken-to-connect-a-device dashboard](https://github.com/mozilla/fxa/blob/master/features/FxA-70-kpi-dashboards/README.md#time-taken-to-connect-a-device), the content server must emit `flow.begin` events ~~when the user submits the forms at `/signup` and `/signin`~~ at the start of the `index` route handler.

As metadata, the events should have the timestamp in epoch-milliseconds, a randomly-generated flow id, `newUser` set to `0` or `1` and appropriately set `userAgentBrowser`, `userAgentVersion`, `userAgentOS`, `service`, `context`, `entrypoint`, `campaign` and `migration` fields. The flow id must be passed to the view, in order that it may be propragated to the auth server as part of #3551.

**Comment by shane-tomlinson** [comment]
> As metadata, the events should have the timestamp in epoch-milliseconds and a randomly-generated sequence id. The sequence id must be propragated to the backend as part of #3551, in order that the auth server can re-use it when emitting its own activity events.

Trusting any sort of timestamp generated client side is ripe for problems with clock skew. User's clocks are all over the place, sometimes days and years off. That's the big reason we use offsets everywhere.

We already have 'signup.submit' and 'signin.submit', will these work for the sequence start event?

**Comment by philbooth** [comment]
> Trusting any sort of timestamp generated client side is ripe for problems with clock skew. User's clocks are all over the place, sometimes days and years off. That's the big reason we use offsets everywhere.

Thanks @shane-tomlinson, you make an excellent point here. I'm wondering whether we should actually emit this event from the auth server instead, when it receives the request. @rfk, how would you feel about that? Or maybe that was what you intended all along and I was barking up the wrong tree when I opened this issue here?

**Comment by philbooth** [comment]
The alternative, suggested by @shane-tomlinson in IRC, is to work out the approximate timestamp using [_calculateQueueTime](https://github.com/mozilla/fxa-content-server/blob/master/server/lib/ga-collector.js#L103-L127). Since the KPIs are based on medians, outliers from slow metrics requests shouldn't affect the dashboard. So maybe ignore my previous question.

**Comment by rfk** [comment]
> emit sequence.begin events when the user submits the forms at /signup and /signin.

Ideally the event would occur much earlier than this.  What I'm hoping we can do here is emit an event at the very first possible instant that we know the user is entering a flow with us.  The time between this initial event and the user ultimately connected their device should encompass as much of the flow as possible - fetching and parsing the javascript for the UI, interacting with the form, submitting requests to the auth-server, messaging the results out to the device, and the device itself actually receiving and acting on those results.

Can we do it server-side in the content-server, at the point where the user first requests the page to start interacting with us?  I recall @shane-tomlinson saying that this initial request always has to hit the nodejs backend rather than the CDN for a variety of reasons.

**Comment by philbooth** [comment]
> Can we do it server-side in the content-server, at the point where the user first requests the page to start interacting with us?

Sorry, if I'd paid closer attention to the definitions in your feature doc, I'd have got this right first time. Anyway, sounds good to me.

**Comment by shane-tomlinson** [comment]
> Can we do it server-side in the content-server, at the point where the user first requests the page to start interacting with us? I recall @shane-tomlinson saying that this initial request always has to hit the nodejs backend rather than the CDN for a variety of reasons.

The user has to request the HTML from the node server. I made a proposal in IRC yesterday, I'll try to capture that here:

Because of clock skew between the server and the client, we can't really trust any timestamps generated by the client. We can however trust offsets. Each sent metrics packet has two client generated timestamps, a `startTime` and a `flushTime`. `startTime` comes from NavigationTiming.navigationStart, which essentially starts as soon as the first request is made to the content server.

The content server knows when the metrics package arrives. If we make a huge assumption and assume the time it takes to transfer the metrics package is negligible, we can calculate the diff between the client's clock and the server's clock.

skew = clientFlushTime - currentServerTime;

We can then calculate when the page was first requested:

pageRequestTime = skew + clientStartTime;

I think.

Or, we could do something much more mundane. When the user requests the page, set a cookie that has the server's time. Scope the cookie to the path `/metrics` to avoid sending the cookie on every request. When metrics packets are reported, the server reads the timestamp from the cookie and makes it's calculations. Not nearly as fun, but practical, assuming all the server clocks are synced to within a second or two.

**Comment by shane-tomlinson** [comment]
Or you can ignore all of this, I'm tired and talking gibberish.

**Comment by philbooth** [comment]
> Or you can ignore all of this, I'm tired and talking gibberish.

I don't think you're talking gibberish, but the approach I've started to take locally is to emit the event [here, in the route handler](https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/get-index.js#L11-L13) and then pass the newly-generated sequence id to the front-end as view data.

Do you think that is okay?

**Comment by philbooth** [comment]
Just to expand on that a bit, I was thinking of sticking something like the following in [here](https://github.com/mozilla/fxa-content-server/blob/master/server/templates/pages/src/index.html#L21), to receive the sequence id:

```html
        {{#if sequenceId}}
        <script>var _FXA_SEQUENCE_ID = {sequenceId};</script>
        {{/if}}
```

Or maybe there is a less hackish way?

**Comment by shane-tomlinson** [comment]
Inline scripts are verboten since they can be used to exfiltrate data by unsavory actors.

**Comment by shane-tomlinson** [comment]
@philbooth - where is the `_FXA_SEQUENCE_ID` consumed? Is that reported in metrics? Can you use a cookie to the same effect?

**Comment by philbooth** [comment]
Me and @shane-tomlinson just had a chat about this and we came to the following conclusions:

1. Emit the `sequence.begin` event from the index route handler.
2. Pass the newly-generate `sequenceId` from the route handler to the front-end as view data for a `data-` attribute.
3. In order to enable track the `sequenceId` through verification in different tabs/browsers, either:
  * Store it on the resume token or;
  * Associate it with the verification code in the back-end.

**Comment by shane-tomlinson** [comment]
@philbooth - we also spoke about sending the sequenceId to the browser in the `fxaccounts:login` message so that the browser can send the id to the auth server on device registration.

**Comment by philbooth** [comment]
Oh yeah, well remembered! :blush:

**Comment by vladikoff** [comment]
Can `uniqueUserId` be used instead of `sequenceId` https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/scripts/models/unique-user-id.js#L72 ?

**Comment by philbooth** [comment]
> Can uniqueUserId be used instead of sequenceId

I don't think so, for two reasons:

1. The `sequence.begin` event is emitted by the server, before a user id has even been created.
2. It's possible that one user id could have multiple concurrent sequence ids, if they are doing things on different devices.

**Comment by rfk** [comment]
IIRC `uniqueUserId` is broadly the same concept as this, a kind of "session identifier" rather than something that tries to stick to the user across multiple sessions.  So it may make sense to try to merge the two.
