### ISSUE TITLE
Remove synchronization of unmasking on change password fields

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3600]
Probably inherited from our reset flow (where the user is repeating the same password) we are synchronizing the unmasking of the password fields on Change Password.
![show](https://cloud.githubusercontent.com/assets/68213/13851184/8cfee71c-ec33-11e5-9fc7-10343a17420b.gif)
Because the old and new passwords have different security concerns, I can't think of a reason why we should be doing this, so we should remove it.

**Comment by larissagaulia** [comment]
Hello! Can I take a look at this issue? Do you have documentation about the decision of synchronizing the unmasking? =) I see there's a [mixin](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/password-mixin.js#L31)  function that targets ALL '.password ' not only the clicked one. 
I see 3 possible solutions: 

1. remove this mixin in [change_password](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings/change_password.js#L62) view and set an event in this class. (not my favorite, because duplicate very similar code)

2. create a parent view to all the views currently using password-mixin (that extends the form view and set the onchange event) and migrate the visibility behavior to this new view. Thus I can let synched unmasking as default and override it in change_password.

3. change the default unmasking behavior in the current mixin to only show the targeted pdw and create another mixin to be included in the view needing the synched behavior.

 Please say what you think about it or just show me how you usually do this. thanks!

**Comment by pdehaan** [comment]
Ref: #311 
Ref: #1120
Ref: https://github.com/mozilla/fxa-bugzilla-mirror/issues/99

**Comment by vladikoff** [comment]
> Can I take a look at this issue?  

:+1: 

> Do you have documentation about the decision of synchronizing the unmasking?

As @ryanfeeley states above this should happen when you type two different passwords, such as "Old password" and "New password". Other cases should reveal both fields.

> I see 3 possible solutions:

Looking at: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/password-mixin.js#L33

Just make the mixin more intelligent, make `setPasswordVisibility` be able to detect if the user wants just one password to show. To help it determine the behaviour update the template here: https://github.com/mozilla/fxa-content-server/blob/932242698f69e7f93f05e6506f3a13b2acdb2f3d/app/scripts/templates/settings/change_password.mustache#L21 and find a way to signal that only this password should be revealed. Perhaps using the `data-` attributes. 

quick example: 
```
<input id="show-old-password" 
type="checkbox" 
class="show-password"
 aria-controls="old_password" 
tabindex="-1" 
data-novalue
data-single-input="true"
 />
```

See if you can come up with a better name than `data-single-input="true"`

**Comment by larissagaulia** [comment]
Could you tell me where should I test it? Unit and functional? =)

**Comment by vladikoff** [comment]
@larissagaulia just unit test is fine, this file could be the place for it: https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/views/mixins/password-mixin.js
