### ISSUE TITLE
"Error: Client has sent too many requests" when running tests against latest

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3613]
![image](https://cloud.githubusercontent.com/assets/128755/13921377/f29bb13c-ef4d-11e5-8d37-0d5bae20dd63.png)

**Comment by vladikoff** [comment]
We need to relax customs on those boxes or something...

**Comment by vladikoff** [comment]
@vbudhram @jrgm @vladikoff to discuss this, not sure what we should do here yet..

**Comment by jrgm** [comment]
So I backed off the MAX_ACCOUNT_STATUS_CHECK limit on fxa-dev, since it's not interesting in a test environment whether `signin0.21327602956444025@restmail.net` has an account or not. I have a patch for stage and production config to back off the value in stage. And dev setups can similarily back off this limit. The real question is what should the value be in production; this api, as I understand it, is a convenience to choose signup v. signin, but it appears, from data, we may be bumping into the limit for normal use cases.

**Comment by shane-tomlinson** [comment]
@jrgm, @vladikoff - was this fixed by https://github.com/mozilla/fxa-dev/pull/238?

**Comment by vladikoff** [comment]
Yeap!
