### ISSUE TITLE
Change the "Sign up" button text to something better

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3623]
It might have to say "Confirm", @ryanfeeley to confirm this .

**Comment by ryanfeeley** [comment]
current experience for reference:
![signup](https://cloud.githubusercontent.com/assets/68213/14191054/e6e453a8-f763-11e5-801e-c17a076c84a6.png)

**Comment by ryanfeeley** [comment]
Current thought process:
![choose-what-to-sync-sign](https://cloud.githubusercontent.com/assets/68213/14219087/39c58dea-f826-11e5-8564-03ee71ca6c82.png)

**Comment by ryanfeeley** [comment]
Thoughts @mozmatej?

**Comment by MozMatej** [comment]
I like "Create Account" on the first one because it's the clearest and, I think, most accurate about what's going to happen in this step. I worry that the other ones could imply the account won't be created until after the next step.

On the second, something with "save" or "update" in it sounds best to me. That at least implies that these settings have already been chosen as the defaults.

**Comment by ryanfeeley** [comment]
@MozMatej You're right that "Create Account" is most accurate because the account does get created then (just not verified until it's verified).

In the second step two things can happen:

1. 93% of users do (or don't) change options and press the submit button and will see the "Confirm your account" screen.
2. 7% verify elsewhere which soon, in mos cases, will cause the screen to auto-submit with the current selections and likely take them directly to Sync prefs (where they can uncheck post-facto).

In either case, while they are on the second screen, their email address is not yet added into Firefox Sync in the browser. So "Save" is good. "Save selection"?

**Comment by MozMatej** [comment]
I worry a bit about the length "Save selection," but otherwise that sounds good. I was thinking "Save settings," but I guess that isn't significantly shorter.

**Comment by ryanfeeley** [comment]
* First button to **Create account**
* Second button to **Save settings**

**Comment by ryanfeeley** [comment]
Once fixed we should be able to flip this one for iframed users too

**Comment by rfk** [comment]
> Once fixed we should be able to flip this one for iframed users too

I don't think we should enable this for iframed users until we've also resolved the "save automatically if the account is verified" issue.

**Comment by rfk** [comment]
@ryanfeeley question: should *all* signup forms receive the new "Create Account" button text on the initial form, or only ones for which we're going to show the choose-what-to-sync screen as a second step?
