### ISSUE TITLE
Add functional tests for "account reset" feature

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3653]
We added the "your account has been reset" feature without functional tests. We should add them.

Ref #3644.

**Comment by vladikoff** [comment]
@rfk let's discuss this feature. @shane-tomlinson and I totally forgot what this does : P

**Comment by rfk** [comment]
IIRC this "feature" was in response to [1], where we did a forced reset of some users passwords as part of the cleanup.  I think it'll be hard to add a functional test for because there's no way to put an account into this state from the client, it's an operation done on the backend by ops.  Is it worth the complexity of mocking that out in order to add a functional test here?

[1] https://blog.mozilla.org/services/2016/04/09/stolen-passwords-used-to-break-into-firefox-accounts/

**Comment by vladikoff** [comment]
from mtg: can we try to add the auth-server functionality for test envs that are NON-stage and NON-prod

**Comment by shane-tomlinson** [comment]
ref #3670

**Comment by vbudhram** [comment]
from mtg: closing
