### ISSUE TITLE
side by side links should convert to stacked links if one link's text grows beyond 50% of width.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3798]
Follow on from https://github.com/mozilla/fxa-content-server/pull/3785

@ryanfeeley's request:

> @shane-tomlinson Is there a way to use CSS media queries for responsiveness so that when the length approaches 50% it becomes the right one above the left one instead of line wrapping? I might be able to code up an example, but am not sure it will be production grade CSS.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/pull/3785#issuecomment-222713521

**Comment by ryanfeeley** [comment]
Could be done easily with white-space: nowrap and min-width: 50%?

**Comment by shane-tomlinson** [comment]
> Could be done easily with white-space: nowrap and min-width: 50%?

Interesting. Seems reasonable. Might need a new container element or else we'll revert the click area being too big problem.

**Comment by TDA** [comment]
I call dibs! MINE!

**Comment by TDA** [comment]
Okay, after having spent about ~8hrs trying everything from `inline-block` to `table-cell` to additional floating `middle` element, I am going to agree with @shane-tomlinson and @vladikoff  that there is no pure css way to do this. The `no-wrap` + `min-width:50%` causes wrong alignment for the links which are _smaller_ than 50%, while the other options each fail for at least one of the 4 scenarios I am testing with:
1. Both short links, normal screensize
2. One short, One long, normal screensize
3. Both short links, small screensize
4. One short, One long, small screensize

The closest css solution that works for all four involves text-align center in all scenarios, instead of the left-align/right-align of the links we have right now.

**Comment by philbooth** [comment]
> ...there is no pure css way to do this.

Can't flexbox do this?

**Comment by TDA** [comment]
@philbooth I am totally willing to switch it up to flexboxes, but I am pretty sure I will be shot down for Browser-support.

**Comment by vladikoff** [comment]
> @philbooth I am totally willing to switch it up to flexboxes, but I am pretty sure I will be shot down for Browser-support.

You just need to apply the flexbox stuff to the stacked links or switch to the element query approach.

**Comment by TDA** [comment]
@vladikoff element query approach requires a javascript library does it not? and do you want me to leave in the existing layout for links, and then add flexboxes on top of that so that browsers that do not understand flexboxes will at least display the current style for links we have?
Also, we do not know which links are stacked right? so did you mean _all_ side-by-side links?

**Comment by vladikoff** [comment]
> element query approach requires a javascript library does it not? 

Yes, there are several choices and one of them might be a small enough library

>  and do you want me to leave in the existing layout for links, and then add flexboxes on top of that so that browsers that do not understand flexboxes will at least display the current style for links we have?

Yeah

> Also, we do not know which links are stacked right? so did you mean all side-by-side links?  

We don't know the size of the string, also all of them are different based on L10N

**Comment by TDA** [comment]
@philbooth turns out flexboxes arent able to do this either :( moving on to element queries.

**Comment by philbooth** [comment]
> @philbooth turns out flexboxes arent able to do this either

Oh, my bad, sorry for the wild goose chase @TDA. 😕

**Comment by philbooth** [comment]
So, apologies in advance, maybe I'm missing something here. But are we saying the following is no good for us?

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Mmm hmm?</title>
    <style>
      .parent {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
      }
      .dawg {
        margin: auto;
      }
    </style>
  </head>
  <body>
    <h1>Yo Dawg I heard you like flexbox</h1>
    <div class="parent">
      <div class="dawg">so I flexboxed your flexbox</div>
      <div class="dawg">to make it more flexbox</div>
    </div>
  </body>
</html>
```

**Comment by TDA** [comment]
@philbooth We need the two `.dawg`s to be centered when they are on their own line, but left-aligned and right-aligned when they are on the same line.

**Comment by TDA** [comment]
To be clear:
### We get:
<img width="656" alt="screenshot 2016-06-02 17 24 28" src="https://cloud.githubusercontent.com/assets/432707/15765275/a2abda5c-28e7-11e6-8193-2cc70e1a36f7.png">
<img width="513" alt="screenshot 2016-06-02 17 24 36" src="https://cloud.githubusercontent.com/assets/432707/15765277/a52752d4-28e7-11e6-8c56-51a9e8c270b3.png">

### We need:
<img width="626" alt="screenshot 2016-06-02 17 31 25" src="https://cloud.githubusercontent.com/assets/432707/15765292/dc6804e6-28e7-11e6-89a2-7669b29acc78.png">

<img width="513" alt="screenshot 2016-06-02 17 24 36" src="https://cloud.githubusercontent.com/assets/432707/15765277/a52752d4-28e7-11e6-8c56-51a9e8c270b3.png">

The child elements wont be left-right completely cuz margin is set to `auto` for the child elements,  but they need to be `auto` otherwise they wouldn't get centered when they are on their own line. A Catch-22 situation :(

**Comment by TDA** [comment]
@vladikoff So I just realized that element-queries cannot help us much here either, because, they allow us to query for links that are more than `x` pixels wide, and then style those, but imagine the scenario where only one link is longer, that would mean we need to style both the links to stack, but only one link would have the element-query class added. So I just thought of writing our own function to do this, and its super simple:
```
(function () {
  window.addEventListener("load", resize);

  function resize(event) {
    var links = $('.links');
    var containerWidth = parseFloat(links.css('width'));
    var halfWidth = (containerWidth) / 2 - 10;
    var resetLinks = false;

    links.children().each(function (i, item) {
      var width = parseFloat($(item).css('width'));
      // we need it to be more than half the width
      if (width > halfWidth) {
        console.log(item, " was found to be very close to half the width");
        resetLinks = true;
      }
    });

    if (resetLinks === true) {
      links.addClass('stacked');
    } else {
      links.removeClass('stacked');
    }
  }
}());
```
and then style them like so,
```
.links.stacked a {
  display: block;
  float: none;
  margin: 5px auto;
  max-width: 100%;
  text-align: center;
  width: 100%;
}
```

If this approach seems ok, then can you please tell me where this script should go? (it needs to be loaded asap to prevent FOUT), and seeing as it uses a bit of jquery, how/when to import jquery? (or rewrite in vanilla JS with `querySelector`?)
