### ISSUE TITLE
Make sure that shown passwords are saved as passwords

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3799]
Make sure that shown passwords are saved as passwords and not form data.

When users show the password field, I'm told it does not save the password, and instead saves it as regular form data (e.g. phone number).

True @shane-tomlinson @vladikoff?

**Comment by vladikoff** [comment]
😨

**Comment by rfk** [comment]
I added a :heart: label because this sounds like the sort of thing that users could find confusing and upsetting.

**Comment by TDA** [comment]
Just saying, I have my eye on this. <3

**Comment by rfk** [comment]
Since I don't see it linked here explicitly, https://bugzilla.mozilla.org/show_bug.cgi?id=1280294 was a related security-sensitive issue for which a client-side fix has been uplifted to Firefox 48.  Is this issue in "blocked" because we're waiting for that to hit release, or for other reasons as well?

https://bugzilla.mozilla.org/show_bug.cgi?id=1288721 is another related issue, which I think argues for us pushing ahead with the original proposal in #3832, where we morph the field back into a type=password before submitting the form.

**Comment by shane-tomlinson** [comment]
Closing as fixed with #3978.
