### ISSUE TITLE
Unlocalized string in emails footer

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#3851]
<img width="523" alt="capture d ecran 2016-06-19 a 17 38 42" src="https://cloud.githubusercontent.com/assets/1294206/16178338/4e56dbc6-3645-11e6-8d1c-a567ba999fce.png">

The string “For more information, please visit <a %(supportLinkAttributes)s>Mozilla Support</a>.” appears untranslated in emails. I think it’s because of the missing period in https://github.com/mozilla/fxa-content-server/blob/6120f1ebf7d1913b4976d935235e558edb8f9d97/app/scripts/lib/strings.js#L35 while the string currently localized has one https://pontoon.mozilla.org/fr/firefox-accounts/LC_MESSAGES/server.po/?search=For+more+information%2C+please+visit+%3C&string=152495

**Comment by shane-tomlinson** [comment]
Thanks @TheoChevalier - Instead of the content server, that string should come from [the 2nd string on this line in the fxa-auth-mailer](https://github.com/mozilla/fxa-auth-mailer/blob/4f1e2717316b0ed38f09e6298f9a35aefee35cd4/templates/new_device_login.html#L31) which contains the period. That makes me confused why it's not being translated, because as you point out, a translation is available.

**Comment by shane-tomlinson** [comment]
This is very strange, the problem also manifests on the sign up email, the signup complete email, and in both French and Spanish. The string is translated using the l10n sha used by production - https://github.com/mozilla/fxa-content-server-l10n/blob/1f86d6d650161bed24057f351aa3e58d2a30f0cf/locale/es/LC_MESSAGES/server.po.

@jrgm - any ideas?
