### ISSUE TITLE
Sign-in confirmation fails during a slow confirmation in Firefox Desktop

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3880]
## STR

1. Get a clean firefox profile  
1. Trigger Sign-in confirmation and wait in the browser 
1. Wait >30 seconds before verifying the email link

## Expected

![image](https://cloud.githubusercontent.com/assets/128755/16395973/91a77192-3c8a-11e6-8de2-6d9e67364488.png)

## Actual 

![image](https://cloud.githubusercontent.com/assets/128755/16396190/91d5cb18-3c8b-11e6-8fbf-fe12f47eea0c.png)

## Log

```
foxfire
1467062258496	FirefoxAccounts	ERROR	Error updating FxA account info: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11
1467062258496	FirefoxAccounts	ERROR	Error updating FxA account info: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11
1467062258510	browserwindow.syncui	ERROR	updateUI failed: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11
1467062258516	browserwindow.syncui	ERROR	updateUI failed: Error: A different user signed in (resource://gre/modules/FxAccounts.jsm:162:29) JS Stack trace: AccountState.prototype.resolve@FxAccounts.jsm:162:29 < getUserAccountData/<@FxAccounts.jsm:146:14 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11 1467062402412	FirefoxAccountERROR	error POSTing /account/device: {"code":400,"errno":124,"error":"Bad Request","message":"Session already registered by another device","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402412	FirefoxAccounts	ERROR	error POSTing /account/device: {"code":400,"errno":124,"error":"Bad Request","message":"Session already registered by another device","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402917	FirefoxAccounts	ERROR	error GETing /account/keys: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402917	FirefoxAccounts	ERROR	error GETing /account/keys: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1467062402919	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062402920	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403397	Sync.BrowserIDManager	ERROR	Could not authenticate: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403717	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403718	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1467062403839	Sync.ErrorHandler	ERROR	Some engines did not sync correctly.
1467062403872	Sync.ErrorHandler	ERROR	Sync encountered a login error
```

**Comment by vbudhram** [comment]
@vladikoff What version of FF did you use for this? Can't replicate with Fx Latest.

**Comment by rfk** [comment]
FWIW I've also seen this behaviour sprodacially, using Release Firefox.

> 1467062402917   FirefoxAccounts ERROR   error GETing /account/keys: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}

IME, this error is most often caused by trying to re-use a keyFetchToken.  They're single-use, so any attempts to re-use one will produce an "invalid token" error.

**Comment by vladikoff** [comment]
Firefox 47.0

**Comment by vladikoff** [comment]
Here's a log with full debug on: https://gist.github.com/vladikoff/1919c9a1e636709e739db019e82f774d

**Comment by vbudhram** [comment]
I am able to replicate this sporadically when using the first-run page and FF47. I noticed that once sign-in is confirmed, the user gets redirected to https://accounts.firefox.com/settings, verses the sync preferences page. Could there be some weirdness associated with this?

**Comment by shane-tomlinson** [comment]
> I am able to replicate this sporadically when using the first-run page and FF47. I noticed that once sign-in is confirmed, the user gets redirected to https://accounts.firefox.com/settings, verses the sync preferences page. Could there be some weirdness associated with this?

Redirecting to /settings is expected for signin from the firstrun page (see https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA). From the firstrun page, there is no way to redirect to the sync preferences pane, only about:accounts has that power.

**Comment by rfk** [comment]
Thanks for the debug log @vladikoff;

The log shows the browser correctly polling for account status, backing off to a longer polling interval after waiting for a while, and eventually discovering that the account is ready to go.  It then *successfully* fetches the keys and starts doing a sync, which you can see starting from this line:

```
1467120264324 Hawk DEBUG (Response) /account/keys: code: 200 - Status text: OK
```

After doing so, it apparently receives another webchannel message telling it a user logged in:

```
1467120266051 FirefoxAccounts DEBUG FxAccountsWebChannel message received: fxaccounts:login
1467120266052 FirefoxAccounts DEBUG setSignedInUser - aborting any existing flows
```

However, this message clearly contains the same `sessionToken` and `keyFetchToken` that the browser was already using, because the device registration fails with a "this session is already owned" error:

```
1467120266193 FirefoxAccounts ERROR error POSTing /account/device: {"code":400,"errno":124,"error":"Bad Request","message":"Session already registered by another device","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
```

And the attempt to fetch keys fails with invalid token, indicating that the keyFetchToken was already consumed:

```
1467120266753 FirefoxAccounts ERROR error GETing /account/keys: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
```

I can only conclude that we're accidentally sending a duplicate `fxaccounts:login` webchannel message to the browser.

What's weird is that they seem to be quite far apart.  IIRC the timestamps in the log are millisecond timestamps, and here's the time difference between the two `fxaccounts:login` messages:

```
>>> (1467120266051 - 1467120126038) / 1000
140
```

That's a little over two minutes.

**Comment by rfk** [comment]
> What's weird is that they seem to be quite far apart.

So perhaps we're sending a second `fxaccounts:login` message when we e.g. transition to the /settings page.

**Comment by rfk** [comment]
@shane-tomlinson I'm taking the liberty of assigning you for the next action here, can you suggest any reason why we might be sending a duplicate `fxaccounts:login` message?  If you're able to dig into it yourself that would be awesome, but if you don't have bandwidth for it, any pointers you can suggest would be very valuable.

**Comment by philbooth** [comment]
Just commenting to highlight @rfk's point about 140 seconds.

Yesterday I tried unsuccessfully to reproduce this in 47 maybe five or six times, each time I was waiting for 30-something seconds as per the issue description. I just tried again now, leaving it more than 140 seconds and boom, failed first time.

**Comment by shane-tomlinson** [comment]
In the signin flow with signin confirmation enabled, we send two `fxaccounts:login` messages. The first is in [models/auth_brokers/fx-sync.js->beforeSignUpConfirmationPoll](https://github.com/mozilla/fxa-content-server/blob/a2ff648d43af4ad0157d887610568691c7075bd0/app/scripts/models/auth_brokers/fx-sync.js#L131) and the second after the user confirms the email address from [afterSignIn](https://github.com/mozilla/fxa-content-server/blob/a2ff648d43af4ad0157d887610568691c7075bd0/app/scripts/models/auth_brokers/fx-sync.js#L111).

Not sure what the solution is yet.

**Comment by shane-tomlinson** [comment]
The problem is limited to the firstrun flow because the firstrun flow is the only flow that actually polls to check whether the user has confirmed their signin confirmation. All other flows assume the user is accessing FxA from within about:accounts, and that the browser will do its own polling.

I have not verified, but this problem will also exist with signin confirmation disabled and a user that signs up but never verifies their email, and then signs in to FxA/Sync on another device from the firstrun page, because the same logic is used.

**Comment by shane-tomlinson** [comment]
More background, the firstrun flow does its own polling because we know that about:accounts will not take over when it determines the account has been verified. Instead of letting the user sit there w/ out feedback once they verify, we poll until the user has verified and then transition to the signin_complete screen.

Thinking via GitHub issue diarrhea. 

We need the `fxaccounts:login` message to be sent before the signin confirmation poll begins.
We do not want the `fxaccounts:login` message to be sent after the poll completes. We only want to transition to the `/signin_complete` page.

For the signin confirmation flow, I re-used the [`afterSignIn` broker method](https://github.com/mozilla/fxa-content-server/blob/a2ff648d43af4ad0157d887610568691c7075bd0/app/scripts/views/confirm.js#L128) method from views->confirm.js because we always want to finish the same place as `afterSignIn`. I took the easy route, and now see its shortcomings. confirm.js only used to delegate to `afterSignUpConfirmationPoll.` Perhaps instead of calling `afterSignIn`, we should create a new broker method `afterSignInConfirmationPoll`. `afterSignInConfirmationPoll` won't be called by most brokers, because we know beforehand the flow will halt before the confirmation poll starts. For the firstrun flow, the broker will not send the `fxaccounts:login` message, but will redirect to the signin_complete page.

-----------------

w.r.t. [this comment above](https://github.com/mozilla/fxa-content-server/issues/3880#issuecomment-229108725):
> Redirecting to /settings is expected for signin from the firstrun page (see https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA). From the firstrun page, there is no way to redirect to the sync preferences pane, only about:accounts has that power.

This is wrong, the user should be redirected to /signin_complete. I need to update that doc.

**Comment by shane-tomlinson** [comment]
FWIW, I also re-use the [beforeSignUpConfirmationPoll](https://github.com/mozilla/fxa-content-server/blob/a2ff648d43af4ad0157d887610568691c7075bd0/app/scripts/views/confirm.js#L112) method to determine whether polling should occur for the current broker. This too was a lazy decision that hasn't *yet* shot us in the foot.
