### ISSUE TITLE
Sort devices by most recently active

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3899]
Noticed that the forced devices view seems to list devices in an arbitrary order.
<img width="148" alt="screenshot 2016-06-30 10 31 46" src="https://cloud.githubusercontent.com/assets/68213/16491972/008c59e0-3eae-11e6-868c-fbf34b635013.png">
Possible to sort by most recently active @philbooth?

**Comment by philbooth** [comment]
Yep, definitely, good point.

**Comment by shane-tomlinson** [comment]
I realize most people won't care, but seemingly random order changes are going to make my OCD want to yell. I do not like this idea. Devices are sorted with the current device first, then alphabetically afterwards. They will always be in the same order on the same device, unless the user changes the name of a device at which point the list will update on the next refresh.

**Comment by ryanfeeley** [comment]
@shane-tomlinson You are right about the current device being first, but alphabetical is not terribly useful in this context. Mobile devices cannot be renamed and are often truncated. What users are doing in this state is reviewing what's connected and I think it makes sense to have the old stuff, most likely to be disconnected at the bottom.

The order was actually designed into the original spec: https://github.com/mozilla/fxa/tree/rfeeley/device-controller/features/FxA-16-devices-view#minimal-view-no-rename

**Comment by shane-tomlinson** [comment]
> most likely to be disconnected at the bottom.

I see what you are trying to do here. 

> The order was actually designed into the original spec: https://github.com/mozilla/fxa/tree/rfeeley/device-controller/features/FxA-16-devices-view#minimal-view-no-rename

After looking at the image, I now see there are two possible interpretations of the sort order:

1. How you meant it - increasing last connected time
1. How I interpreted it - [the first one is current, the rest are in alphabetic order](https://github.com/mozilla/fxa-content-server/issues/3251).

While putting together the original PR, I thought we discussed the sort order and decided to go with alphabetical, mostly because of the seemingly random change to sort order and because the date isn't really connected to the last time the user's device synced, or maybe I discussed that with myself and went forward.

**Comment by ryanfeeley** [comment]
@shane-tomlinson How likely are last synced and last authenticated times to differ? We are only listing clients that can Sync, no?

**Comment by shane-tomlinson** [comment]
> How likely are last synced and last authenticated times to differ? We are only listing clients that can Sync, no?

They can differ by up to 12 hours.

**Comment by ryanfeeley** [comment]
Users are likely to look at the bottom of the list to disconnect old devices, so sorting by order still makes sense. I'm going to file another issue so that we present by last synced rather than last authenticated. I'm told everything is possible in software with time. :)

**Comment by shane-tomlinson** [comment]
ref #3908
