### ISSUE TITLE
Upgrade the "Devices" view to "Devices & Apps" view

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3921]
This is an early issue that is tracking the merge of front-end code required for the "connected apps" view. 
The settings view would be hidden by default at first (just like the devices view) 

Prior Art:

<img src=https://cloud.githubusercontent.com/assets/128755/16741074/b8278cfe-476f-11e6-980d-ac8595dd7a2f.png width=200 />

Ref: https://security.google.com/settings/security/permissions?pli=1

(Feature doc pending...)

**Comment by vladikoff** [comment]
@rfk this is related to https://github.com/mozilla/fxa-features/issues/20 is that correct?

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/16744807/cc8e4636-4780-11e6-8b22-16c55da3775b.png)

**Comment by ryanfeeley** [comment]
This is what I had two years ago, using the old design. I think we can probably use the device manager view now. ![screenshot 2016-07-12 10 56 00](https://cloud.githubusercontent.com/assets/68213/16771657/4bc942d6-481f-11e6-8cc9-afb7d328f2b8.png)

**Comment by rfk** [comment]
> @rfk this is related to mozilla/fxa-features#20 is that correct?

Yes, and I wonder if we should do this design/discussion in that issue in order to keep the feature-level work all in one place.

> I think we can probably use the device manager view now.

One of the long-standing issues we've had with the UX for this feature, is that the connected services are not really per-device.  Or at least, we can't really control them on a per-device basis, so I don't think we can usefully combine this with the device manager.

The best concrete example here is Pocket.  If a user uses FxA to log in to pocket, the following happens:

1. The user does an OAuth flow between FxA and Pocket
2. Pocket's servers receive an OAuth token that they can use to access the user's profile data.  This token is held by the servers, it's not tied to the user's browser in any way.
3. Pocket sets a cookie on the user's browser, giving them an active login session to Pocket on that device.

The OAuth token at (2) means that even if the user puts their device through a shredder, Pocket still has access to their account data, using a token held on the Pocket servers.  We need a way for the user to see and revoke this access, which is why I had in mind with this feature.

On the other hand, as FxA, we don't really have any control over the session cookie from (3) since it is entirely managed by Pocket.  We can't "log the user out of Pocket" in any meaningful sense.  So we have to be careful that we're not implying to the user that revoking access here, would log them out of Pocket.
