### ISSUE TITLE
Allow Fx Desktop Sync users to sign out from the settings page

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4017]
Follow on from https://github.com/mozilla/fxa-content-server/issues/3687#issuecomment-237457272

The "Sign out" button was originally hidden from Sync users because we had no way of messaging out to the browser that the user signed out if the user opened FxA just by browsing to https://accounts.firefox.com/settings. With WebChannel messages, this is no longer a problem - we can just send a WebChannel [fxaccounts:logout](https://dxr.mozilla.org/mozilla-central/rev/1576e7bc1bec7232e9e4ba78cce62526b1a6380b/services/fxaccounts/FxAccountsWebChannel.jsm#33) message. Note this message is only handled by Fx Desktop, not Fennec.

**Comment by vladikoff** [comment]
@rfk @ryanfeeley do we want users to sign out of sync and add this feature? or should we only rely on browser about:prefs ux? 

I think before we didn't want to disconnect from sync this way.

**Comment by ryanfeeley** [comment]
@vladikoff  What would happen to a relier (e.g. AMO) session?

FWIW, disconnecting Chrome keeps the user signed in to web properties. If they attempt to sign in again to Chrome, their username is cached, but not the password.

This is the same way I had imagined we should handle it.

**Comment by rfk** [comment]
> I think before we didn't want to disconnect from sync this way.

IIRC one of the reasons we didn't allow this before, is that we didn't have a clean way to tell the browser about it.  We could destroy the sessionToken, but the browser would only discover this hours later when it went to refresh its certificate, failed, and entered the "needs reauth" state.

We now have an explicit "logout" webchannel message that we can send to the browser, which should make that cleaner.

The user problem we'd be addressing here is, if I'm logged in to sync in my browser and I visit https://accounts.firefox.com, I can see that I'm logged in but there's no clue about how I should log out.  I wonder if we could at the very least, have a "logout" button that somehow directs the user to about:preferences?

>  What would happen to a relier (e.g. AMO) session?

Nothing, they would stay logged in to AMO since AMO manages its own session cookie.

**Comment by vladikoff** [comment]
from mtg: check how "Device and apps does this", see if we can just do the same...

**Comment by shane-tomlinson** [comment]
I've changed my mind on this, it now seems to me that users that click a standalone "Sign out" button from within the settings page probably wouln't expect that to cause the user to disconnect from Sync.

**Comment by shane-tomlinson** [comment]
I'm closing this. We aren't going to do this.
