### ISSUE TITLE
Measure if user can successfully log in after being rate limited/blocked

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4022]
Users who receive the [114 errno (THROTTLED )](https://github.com/mozilla/fxa-content-server/blob/83f0da21fd724956cdf576529c3d7c0083af0ac4/app/scripts/lib/auth-errors.js#L87) from the auth server are able to try again after a blackout period has elapsed. 

A [125 errno (REQUEST_BLOCKED)](https://github.com/mozilla/fxa-content-server/blob/83f0da21fd724956cdf576529c3d7c0083af0ac4/app/scripts/lib/auth-errors.js#L101) is similar, though the user may be blocked for a much longer duration.

If the user receives either of these errors, we should know whether they can successfully login on the same device after the ban has expired.

**Comment by vladikoff** [comment]
This might be easier to do on the auth-server unless you want some content server info in this.

**Comment by vladikoff** [comment]
need to talk @rfk about this.

**Comment by vladikoff** [comment]
@rfk should we just log all auth-server errors and we will have data for this?

**Comment by vladikoff** [comment]
... and then write a re:dash sql query to get "account.login" after "account.rate-limited" query

**Comment by rfk** [comment]
I don't think they can be activity events, because:

* We won't know the associated UID when we block the login attempt; we could look it up but we don't have any reason to believe the login attempt is legitimate at that stage.
* Just because someone was rate-limited and then later succeeded, doesn't mean those events were related to a single login attempt.  They might have been rate-limited on one device and then succeeded at logging in on another device.

I think these would make great "flow events" to emit on the auth server, cf https://github.com/mozilla/fxa-features/issues/13.  If we have the flow-id at the point where these events are occurring, then we could:

* Log them on the auth-server, including the flow-id
* Export them to redash
* Run a query there to look for "flow ids that have account.login after account.rate-limited".

/cc @philbooth who has been working through what flow-based metrics might look like in more detail.

**Comment by vladikoff** [comment]
> I think these would make great "flow events" to emit on the auth server

Yeap that's correct, I got confused it a bit because flow_id is currently included in the activityEvents

opened https://github.com/mozilla/fxa-auth-server/issues/1403 

We should be able to close this issue on the content server if we are on the same page.

**Comment by vladikoff** [comment]
@rfk do we have enough flow events to build this funnel or should we add the login attempt to the auth server?

https://github.com/mozilla/fxa-auth-server/blob/8d36f00ca0f725b1f21b16a3aaf4dcba03e445f4/lib/customs.js#L51

![image](https://cloud.githubusercontent.com/assets/128755/18279565/fc688e8c-7423-11e6-89d3-31008608510a.png)

cc @philbooth

**Comment by philbooth** [comment]
> do we have enough flow events to build this funnel or should we add the login attempt to the auth server?

@vladikoff, your `Login attempt` here is currently specced as `login.submit` in the [draft feature doc](https://docs.google.com/document/d/1et1zy1f4qimYqpm6a3YGNinvLbFoRjOX8OqooPGg3O8/edit?ts=57a035a0#). Fwiw, I was seeing it as a content server flow event rather than an auth server one.

You're welcome to implement it first if you need it right away (obviously).

**Comment by rfk** [comment]
Yeah you're right, we should have a `login.submit` of some sort.  The `flow.begin` event is too broad, no way to tell whether it was a login or a signup.

I think as a first approximation though, it would be fine to just look for all flowids that have a `customs.blocked` followed by a successful `account.login`, and compare those to flows that terminate after `customs.blocked`.  You might get a few that were blocked sign-up attempts, but I think the majority would be blocked login attempts.

**Comment by vladikoff** [comment]
We should have all the flow events with train-70 to build the thing in https://github.com/mozilla/fxa-content-server/issues/4022#issuecomment-244986275
