### ISSUE TITLE
Investigate Registration Drop

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4130]
Understand why registration dropped by 10%. See context here (although likely unrelated):  https://github.com/mozilla/fxa/blob/1e01ca7d370dd5dd8bf37f3d88ac3aaa72630e25/features/FxA-97-password-strength/README.md

**Comment by rfk** [comment]
Relevant snippets of context:

"""
Since July 2016 and introducing new password prompts the following changed:

*  Successful signups as a % of submissions decreased by 10%.

The decrease in signups may be attributed to having more users login rather than signup.
"""

**Comment by rfk** [comment]
Here's a link to one of the relevant graphs:

  https://app.datadoghq.com/dash/67511/fxa-content-server---password-strength?live=false&page=0&is_auto=false&from_ts=1469368800000&to_ts=1471874399000&tile_size=m&fullscreen=81759578

This is `fxa.content.signup.success` as a percentage of `fxa.content.signup.submit`.  The change does appear to be driven by a decrease in `signup.success`, the rate of submissions stays fairly consistent over the period in question.

**Comment by rfk** [comment]
Here's an interesting point: if I change the graph to be `fxa.content.signup.signup.success` rather than `fxa.content.signup.success`, the drop more-or-less disappears.  Could it have something to do with a change in the signin-from-signup flow and the way it's reporting its metrics?

**Comment by shane-tomlinson** [comment]
> Here's an interesting point: if I change the graph to be fxa.content.signup.signup.success rather than fxa.content.signup.success, the drop more-or-less disappears. Could it have something to do with a change in the signin-from-signup flow and the way it's reporting its metrics?

Yes, this is one of the problems that came out of signin from signup. `fxa.content.signup.success` is triggered if the user either successfully signs-UP OR signs-*IN*. 

> This is fxa.content.signup.success as a percentage of fxa.content.signup.submit

As a percentage of `fxa.content.signup.submit` probably isn't what you really want to measure, but it's the best we have right now. `fxa.content.signup.submit` is triggered if the user is signing up or signing in. We log the event as soon as the user submits the form, but we have no way to differentiate between `this user is trying to sign up` vs `this user is trying to sign in` until we check whether the account exists. We could do something like log a different submit event once we know whether the account is registered. If the account is registered log an `fxa.content.signup.signin.submit`, if the account doesn't exist, `fxa.content.signup.signup.submit`. 

The oddness of `signup.signin` and `signup.signup` is necessary because the initial `signup` is the view name, of which we do not want to change.

Signin from signup and force_auth are also why to count the total signin successes, we need to count `fxa.content.signup.signin.success`, `fxa.content.force_auth.signin.success` and `fxa.content.signin.signin.success`.

Unfortunately datadog doesn't let us do wildcard matching to get around these problems. We could either ditch the screen names as part of the event name, losing that information, or log additional events not tied to a screen, e.g., instead of 3 *signin.success events, one for each screen, log an additional `fxa.content.*.signin.success`, or perhaps some other scheme that says "for all screens".

**Comment by shane-tomlinson** [comment]
Here's the part of the explanation I didn't make explicit earlier.

fxa.content.signup.success is the sum of two component metrics: fxa.content.signup.signup.success and fxa.content.signup.signin.success.

The vast majority of our users are for Sync, these users must go through signin confirmation. Users who go through signin confirmation cannot contribute to fxa.content.signup.signin.success, they have to go verify their email. If ~ 10% of users sign-in from the sign-up screen, and these 10% of users are all forced through signin confirmation, the 10% drop makes perfect sense.

**Comment by rfk** [comment]
>  log additional events not tied to a screen

+1; logging an explicit "you finishing signing in, good job!" event sounds like a good idea to me, will help us avoid having this conversation again the next time we change the sequence of screens in the login flow.

**Comment by rfk** [comment]
Closing this out, but here's a follow-up bug for the non-screen-related success events: https://github.com/mozilla/fxa-content-server/issues/4163
