### ISSUE TITLE
Discuss devices view ux suggestions

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4170]
Ref: https://github.com/mozilla/fxa-content-server/pull/4131#pullrequestreview-624743
- change password link
- close button?
- new select style?

**Comment by philbooth** [comment]
From meeting: just to clarify, these relate to the disconnect device dialog.

**Comment by philbooth** [comment]
From meeting: @shane-tomlinson to chat with @ryanfeeley.

**Comment by shane-tomlinson** [comment]
From IRL conversation with @ryanfeeley: 

* Change password link - We can test, but interaction might be a bit weird because it would close the modal and open part of the accordion further down. (TLDR - probably not)
* Close button - Let's hook up an escape  key shortcut before adding a close button for keyboard a11y.
* New select style - There's a bug open to convert these to radio buttons (#4303).

**Comment by vladikoff** [comment]
from mtg: `close this issue, open separate bugs`

**Comment by vladikoff** [comment]
Follow up issues: 

* https://github.com/mozilla/fxa-content-server/issues/4169
* https://github.com/mozilla/fxa-content-server/issues/4303
