### ISSUE TITLE
Handle blank device names, call then "Firefox" in the list

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4205]
![image](https://cloud.githubusercontent.com/assets/128755/18891597/f813174c-84d3-11e6-99d3-3c8b76495df4.png)

@davismtl reported that he saw a device with an empty name. Not clear how that happened yet. He suspects it was iOS Beta that did this.

**Comment by philbooth** [comment]
One way this could have happened is if we failed to parse the user agent string and the device record was created after https://github.com/mozilla/fxa-auth-server/pull/1399 was deployed to production but before https://github.com/mozilla/fxa-auth-server/pull/1422 made it in.

The first of these changes implemented placeholder devices, the second one added a fallback name in the event that UA parsing failed. I think it was only one train that the discrepancy existed for and it doesn't address the root cause of why UA parsing failed if that was the case, so maybe no related to this.

But thought it worth mentioning just in case.

**Comment by vladikoff** [comment]
from mtg: 

1. should we run an update query in DB? ❎

2. should we fix the presentation? 👍  + localization

It is possible for a user to set a blank device name via the API.

@ryanfeeley what should this say: `Unnamed device` ?

**Comment by ryanfeeley** [comment]
This is Sync, so it can only be Firefox right? How about just "Firefox"… and follow-up with a geo-location issue?

**Comment by vladikoff** [comment]
>  How about just "Firefox"… 

👍
