### ISSUE TITLE
"Looking for Firefox Sync? Get started here" link goes off into bla-bla-bla land

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4336]
If I'm in a new user profile and go to https://accounts.firefox.com/signup, I'm present a signin form for non-sync with a link saying "Looking for Firefox Sync? Get started here". If I want to signin to sync, I click the link. 

This in no way gets me closer to signing in to sync. Try it.

**Comment by jrgm** [comment]
Ugh. Maybe this depends on some partial state in the browser that /clear doesn't clear. Still, it now takes me two clicks in web ui.

**Comment by rfk** [comment]
Thanks @jrgm - I'm curious what it showed you on the time it didn't work.  But the page it links to does have a fair bit of magic sauce on it, so I'm not terribly surprised to here it went wrong :-(

Unfortunately the current https://accounts.firefox.com/signup page doesn't know enough about the browser to sign you into sync directly.  You need to wind up on https://accounts.firefox.com/signup?context=BLAH but the value of "BLAH" depends on what browser you're using.

The page that we link to, https://www.mozilla.org/en-US/firefox/sync/, has magic powers that enable it to directly open "about:accounts".  We could make a better experience by granting those same powers to accounts.firefox.com, so that "Get started here" can link directly to "about:accounts" rather than bouncing through the product page.

@davismtl, the link referred to above has utm tracking params in it:

  https://www.mozilla.org/en-US/firefox/sync/?utm_campaign=fx-signup&utm_content=fx-sync-get-started&utm_medium=fx-accounts&utm_source=fx-website

Can we see in GA how often it's used, how it converts, etc?

**Comment by davismtl** [comment]
Traffic from utm_campaign=fx-signup is really low. Only about 2K users per month land on /sync with that parameter. (vs a MUCH greater population thats see that page, @rfk CC'd you on an email to Gareth)

Remind me: which screen sends to /sync with those UTM params?

**Comment by rfk** [comment]
> Remind me: which screen sends to /sync with those UTM params?

Visiting https://accounts.firefox.com/ directly on the web, when you're not already logged in.  I'm surprised *anyone* managed to do that on purpose, 2K users actually clicking through to set up sync is pretty high compared to my expectations :-)

**Comment by shane-tomlinson** [comment]
We could initiate a web channel flow if the user clicks the link if the user is on Fx > 40. @jrgm says "close it"

**Comment by shane-tomlinson** [comment]
Ref #4605
