### ISSUE TITLE
FxA Settings says I have no Android connected when I do

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4412]
FxA Settings says I have no Android connected when I do

![screenshot 2016-11-15 09 53 33](https://cloud.githubusercontent.com/assets/68213/20310295/62de709c-ab19-11e6-8dbb-a54df58f8a76.png)

**Comment by vladikoff** [comment]
Yea because it is a tablet, we can fix that. But you should still connect a `mobile phone` ;)

**Comment by ryanfeeley** [comment]
@vladikoff You'll notice that I also have an iPhone connected but the app store button appears there as well.

**Comment by vladikoff** [comment]
@ryanfeeley ah yea tha looks like an old placeholder device, I think new placeholders should be detected automatically

**Comment by ryanfeeley** [comment]
@davismtl We should not have shipped this feature. Clearly it was not ready.

**Comment by vladikoff** [comment]
> @davismtl We should not have shipped this feature. Clearly it was not ready.

😞

**Comment by davismtl** [comment]
@vladikoff @rfk 
What do you propose we do?

e.g.
- Can we quickly land a patch?
- Should we roll-back that feature?

Also, QA double checked phase 1 of this feature, it might be worth having them test phase 2 of this feature too.

**Comment by rfk** [comment]
> We should not have shipped this feature. Clearly it was not ready.

As a partial counter-point, there are certain types of bug that tend to only show up when things hit the production servers - such as the apparent issue here with a placeholder iOS device that is incorrectly recorded as desktop rather than mobile.

My interpretation is, this feature seemed too small and self-contained to benefit from a feature-flagged rollout, but in retrospect, we could have done so in order to make time for review and QA on production data.

>  What do you propose we do?

Let's include Vlad's fix above in a point release for train-74.

We could also consider retroactively wrapping it in a feature flag and only preffing it on for e.g. mozilla and softvision accounts, to let is bake in production for a while.  My naive impression from a glance at the code, was this would require too much surgery to the structure that's already in place.

**Comment by rfk** [comment]
> such as the apparent issue here with a placeholder iOS device that is
> incorrectly recorded as desktop rather than mobile

Although, I'm sorry to say I just tried this with a fresh iOS device connection, and it still showed up as a desktop device rather than mobile :-(

We may need to look at our placeholder device logic here to see if we can fix.

**Comment by vladikoff** [comment]
Debugged it with @vbudhram 

Basically the current stable Firefox for iOS version is 5.3 on the AppStore. It has no device registration. Version 6 with device registration should ship on Nov 28 and the icons should show up properly. Here's an example:

1. First device made on the iPod touch with version 6
2. Second device made in the simulator with version 6
3. Third is current stable. 

![](http://v14d.com/i/582c7d7812244.jpg)

**Comment by davismtl** [comment]
You can see from my screenshot that Firefox 6 for iOS is displayed as a phone and 5.3 is displayed as a laptop.

![image](https://cloud.githubusercontent.com/assets/19537086/20357599/745f97b4-abdd-11e6-8caa-5047817314e2.png)

The questions that this screenshot raises for me are:
- what is "Firefox ? on Friday". Normally I only have release and Beta on my iOS device (named Friday). What is the 3rd?
- Since they are all on the same device, why does only 1 of them have the device name?
- Is Firefox iOS 6 confusing? Should it be Firefox 6 on iOS?
-

**Comment by ryanfeeley** [comment]
> Is Firefox iOS 6 confusing? Should it be Firefox 6 on iOS?

I think on "Firefox on iOS 10.1" is enough. I'm not sure introducing a second version number there can be done without being confusing.

**Comment by rfk** [comment]
> you can see from my screenshot that Firefox 6 for iOS is displayed as
> a phone and 5.3 is displayed as a laptop.

Also why do you still have the "Get app" button despite having several phones in that screenshot?

**Comment by davismtl** [comment]
> Also why do you still have the "Get app" button despite having several phones in that screenshot?

Oh yeah, I didn't mention that because I thought it was a known problem. :-/

**Comment by rfk** [comment]
I filed a separate for the case where we report an iOS phone as a desktop device:

  https://github.com/mozilla/fxa-auth-server/issues/1555

**Comment by rfk** [comment]
> I didn't mention that because I thought it was a known problem

@vladikoff is the issue @davismtl sees above, fixed by e.g. the negation changes in your PR here?  https://github.com/mozilla/fxa-content-server/pull/4417/files#diff-4dec8580c2098f72c2775f75068b178cR101

**Comment by rfk** [comment]
This turned into a pretty sprawling conversation, let's see if I can summarize all the pieces.  The following issues were identified:

1) The "get app" buttons should not appear if you have a tablet device connected; fixed in https://github.com/mozilla/fxa-content-server/issues/4417
2) The "get app" buttons should not appear in @davismtl's screenshot above; is this also fixed in the above PR?
3) Firefox for iOS v5.3 appears as a desktop device (and hence causes "get app" buttons to still be shown; filed as https://github.com/mozilla/fxa-auth-server/issues/1555
4) The device name "Firefox iOS 6, iOS 10.1" is confusing; I filed https://github.com/mozilla/fxa-auth-server/issues/1556
5) Questions about extra devices in @davismtl's screenshot; I suspect that these are duplicates caused by Firefox for iOS failing to destroy its sessionToken when you sign out of the browser, but we should try to confirm this.

Did I miss anything?

> > > We should not have shipped this feature.

> > What do you propose we do?

> We could also consider retroactively wrapping it in a feature flag 

ISTM that only the first two points are problems with the "get app" feature itself; the others are quality bugs in the devices view that we could have caught while QA'ing that feature.  Unfortunately the new "get app" buttons have made them easier to spot, but they'll still be there even if we pref off the feature.

I think shipping fixes to (1) through (3) should be high priority, and if we can do this then the user experience will be at an acceptable level to leave the "get app" feature on for general release.  @davismtl thoughts?

**Comment by davismtl** [comment]
This sounds great to me @rfk

**Comment by rfk** [comment]
Whoops, it looks like we made a v0.74.1 point release with a fix for this, but then didn't update the deploy bug to note it https://bugzilla.mozilla.org/show_bug.cgi?id=1317538

The fix for this is not yet in production.
