### ISSUE TITLE
Reduce confusion about email address on Choose What to Sync screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4515]
In user testing, we have observed that some have been confused by the presence of the email address (e.g. "sync with my email address?"). By styling it as a success message, we hope that this will provide some context around what the email is there for.
![current-proposed-email](https://cloud.githubusercontent.com/assets/68213/21241104/2d4b4f88-c2dc-11e6-8109-a31fcecf5875.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - will the confusion be mitigated with your new Onboarding experience? Is a status message needed here at all? Can that information be displayed in another way? I'm asking because `saved` seems like a strange verb to me in this context. It's correct, but it seems strange. The location of the status message also seems strange, it breaks the "choose what to sync" flow - I see the title which tells me to choose what to sync, then I'm taking in a different direction with the status message, then I have to go back a thought, delete the status message from my mind, and tie together the check boxes with the title.

What if the verb was `created` and the location of the status message was moved above the graphic so the CWTS flow is not interrupted, the email/status message is visually distinct from Sync and users have less of a reason to believe they are syncing to their email?

<img width="444" alt="screen shot 2016-12-19 at 14 42 46" src="https://cloud.githubusercontent.com/assets/848085/21316652/ac8b0a16-c5f9-11e6-893c-98d36742a7c1.png">

**Comment by ryanfeeley** [comment]
@stomlinson, I had thought about "created" but went with save. I do like the positioning. Here is an updated graphic but with the Firefox logo removed (which I think is what the very original design called for).
![choose](https://cloud.githubusercontent.com/assets/68213/21318094/d39800c4-c5d5-11e6-90cc-2c04732827dd.png)
