### ISSUE TITLE
Reduce line height of newsletter checkbox label

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4707]
I noticed while reviewing the first run iframe with @ericawright the newsletter checkbox has a 24px line-height. It probably doesn't need to be set at all, but if is should be line-height 18px maximum.

<img width="287" alt="screenshot 2017-02-07 14 24 21" src="https://cloud.githubusercontent.com/assets/68213/22707862/27f2f85c-ed42-11e6-9c2b-92794c34384c.png">

**Comment by TDA** [comment]
@ryanfeeley I might be totally wrong on this, but was the line height set for aligning the checkbox with the text?

**Comment by ryanfeeley** [comment]
@TDA It was, probably my idea too, but only a good idea when there is no line-wrap

**Comment by TDA** [comment]
@ryanfeeley This might be an interesting problem, and might be a chance to try out elemental-queries (copying a page out of @pdehaan 's book)

**Comment by heatherbooker** [comment]
Hi! I'm interested in working on this issue but have a few qs! @ryanfeeley @TDA 
- Did we want to use elemental queries? It seems like a lot of external code to add in atm in order to get support. 
- Secondly, I'm guessing this is the only checkbox for which you would like to see a decrease in line height, is that correct? Not every checkbox with the class `.fxa-checkbox` ?  

Thanks!

**Comment by vladikoff** [comment]
Hello @heatherbooker ,

> Did we want to use elemental queries? It seems like a lot of external code to add in atm in order to get support.

Probably no need for that

>Secondly, I'm guessing this is the only checkbox for which you would like to see a decrease in line height, is that correct? Not every checkbox with the class .fxa-checkbox ?

just the .marketing-email-optin-row field, correct  👍
