### ISSUE TITLE
New device syncing notification sent before sign-in confirmed

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4709]
STEPS TO REPRODUCE
1. Sign in to Sync in Desktop Nightly with an existing Firefox Account
2. Sign in to the same account from another device, ensuring that you have triggered the sign-in confirmation (and are not IP profiled through).

EXPECTED RESULTS
* Nightly does nothing until the sign-in is confirmed by email

ACTUAL RESULTS
* Nightly shows the potentially anxiety-causing sign-in confirmation below
![screen shot 2017-02-07 at 10 21 18 am](https://cloud.githubusercontent.com/assets/68213/22708466/53495814-ed44-11e6-8c60-14a4e40e8e09.png)

**Comment by rfk** [comment]
Ah, interesting, this might be a tricky one.  The "is now syncing with X" notification is sent by our server when the new device registers its device record.  For desktop, the device registration happens *before* the session is confirmed, so that it can receive a push notification when the confirmation is complete.  The sequence goes like this:

1. You sign in on the new device.
2. The new device registers its device record, and listens for the push notification telling it that its session is verified.
3. We send a push notification about the new device to any other devices connected to the account.
4. You confirm the login and the new device starts syncing.

We could try to delay (3) until after (4), but it could get pretty ugly in code.  Or, we could add an additional notification after (4) to say that the new device was confirmed.

**Comment by eoger** [comment]
I think we might want to go with the ugly solution (not sure we have a way to say "this is the first call to /signin from this device"), because if we go on with the verification using "send tabs to device" feature, the user will get a "This computer is now syncing with..." before getting the sent verification tab, which could be confusing to the user.

**Comment by rfk** [comment]
It might not be too bad, we could try doing something like:

* During device registration, only send the "new device connected" message if the device's session is verified
* When a session gets verified, check whether that session has an existing device record, and if so send the "new device connected" message at that point.

It's kinda yuck in that we're managing the details of a user-facing flow down deep in the bowels of a backend server, but doable.

**Comment by ryanfeeley** [comment]
@eoger @rfk Seeing as we're planning to send sign-in confirmation requests by push notifications, if this feature is not easily done I would lower the priority.

**Comment by shane-tomlinson** [comment]
@eoger - is there a bugzilla tracking bug for this?

**Comment by shane-tomlinson** [comment]
This should be re-opened on the auth-server

**Comment by vladikoff** [comment]
Continued here: https://github.com/mozilla/fxa-auth-server/issues/1651
