### ISSUE TITLE
Try to move the HeightObserver from app-start to fx-firstrun auth_broker

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4719]
Ref: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/app-start.js has the heightobserver, which we might be able to clean up a bit.

**Comment by alisha17** [comment]
Hi,
Can I work on resolving this?
If I can. could you please give an idea what exactly I have to do?

**Comment by seanmonstar** [comment]
@alisha17 Hi! So, it sounds like this is suggesting to move the `HeightObserver` code from out of [app-start](https://github.com/mozilla/fxa-content-server/blob/v1.82.0/app/scripts/lib/app-start.js#L332-L345) (and related code in that file), and move it into the [fx-firstrun](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/fx-firstrun-v1.js) file.

This is because the only time Firefox Accounts appears inside an iframe is during the First Run flow (https://www.mozilla.org/en-US/firefox/52.0/firstrun/), so may as well move the iframe specific code into there.

You could probably have the height observer start watching the iframe in the constructor.

**Comment by pooyaX14** [comment]
Hi @seanmonstar ,
I was also looking into this issue to begin contributing to this project and would like to work if nobody has been assigned this issue. I have also set up the development environment for this and am able to see the sign-up page on 127.0.0.1:3030

I don't know where to find the corresponding path for the page https://www.mozilla.org/en-US/firefox/52.0/firstrun/ on my local server to see the changes on files app-start.js and fx-firstrun-v1.js

**Comment by alisha17** [comment]
Hi @pooyaX14, I have already resolved it. just writing the test now. You can probably look at the other bugs to take up:)

**Comment by alisha17** [comment]
After using pm2 tool, I am not able to get Mozilla Accounts running on the localhost. What possibly could have went wrong?

**Comment by seanmonstar** [comment]
@alisha17 Without some output from the commands or logs, it's hard to know what exactly went wrong. If you find getting the full fxa-local-dev to work is difficult, it's possible to just update code in the fxa-content-server repository, write some tests, and push your code up in a Pull Request. The test runners will run your tests for you.

**Comment by himanish-star** [comment]
@seanmonstar , Can I file a PR for this issue ?

**Comment by himanish-star** [comment]
@seanmonstar , could you help me please in my PR. I am a first time contributor so I will need some help.

**Comment by shane-tomlinson** [comment]
Are we ever going to do this? No. Closing.
