### ISSUE TITLE
OAuth permissions are not translated

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#4758]
Signing up to Pocket from their website, using the “Sign up with Firefox Accounts” button, I get this screen with two hardcoded strings:

<img width="449" alt="capture d ecran 2017-02-27 a 20 29 08" src="https://cloud.githubusercontent.com/assets/1294206/23376379/26ace8a0-fd2c-11e6-8d11-05384738a400.png">

**Comment by vladikoff** [comment]
Hm the code sets the strings for translation correctly here: https://github.com/mozilla/fxa-content-server/blob/b3237e022b5b62e22ce522119c43ad66cb267faa/app/scripts/views/permissions.js#L37 i guess something else is at play here : /

**Comment by shane-tomlinson** [comment]
Pulling into next for investigation, hopefully doesn't occur in all locales.

**Comment by rfk** [comment]
I dug into this a little bit.  As @vladikoff notes, the strings do appear to be extracted correctly for localization.  However, it's not clear whether the code that builds them into a HTML fragment here:

  https://github.com/mozilla/fxa-content-server/blob/b3237e022b5b62e22ce522119c43ad66cb267faa/app/scripts/views/permissions.js#L187

actually passes them through the translation layer at runtime.  I don't know this code well, but should e.g. the partial template here:

  https://github.com/mozilla/fxa-content-server/blob/b3237e022b5b62e22ce522119c43ad66cb267faa/app/scripts/templates/partial/permission.mustache

be using some sort of `{{#t}}` translation helper rather than directly including the values with `{{x}}`?
