### ISSUE TITLE
[stage] Content server verify_code request is 404 on auth server

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4846]
`"POST /v1/v1/recovery_email/verify_code HTTP/1.1" 404 165 "-" "got/6.6.3...`

Ah, the good old `/v1/v1` version.

**Comment by vladikoff** [comment]
Seems like that extra v1 needs to removed from puppet config https://github.com/mozilla-services/puppet-config/blob/120f829bc7dec153f56e51ce3c1b1ff6f58acd2f/fxa/modules/fxa/templates/data/fxa-content-server/config/default.json.erb#L2

js-client auto adds the v1 ref: https://github.com/mozilla/fxa-js-client/commit/07c0f8977fec5e71817f27bb7da5e707f8aa7947

Otherwise we use the auth server url without the v1 everywhere. We even had to strip it here: https://github.com/mozilla/fxa-content-server/blob/f9006d4e0042002c3f5624e6c626130601c8da22/server/lib/routes/get-fxa-client-configuration.js#L27

**Comment by vladikoff** [comment]
from meetings I think was resolved. @jrgm please reopen if there are issues

**Comment by jrgm** [comment]
Yeah, I checked on stage auth and 404's are gone (with the config change to drop /v1 in stage content configs).
