### ISSUE TITLE
Report on validity of Gravatar

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4931]
We have some metrics in place to measure Gravatar. To me it looks like it produces more errors and 404s than returns real Gravatars. Should we simplify our UI and remove Gravatar altogether? Please report back with a solid analysis of the data.

**Comment by vladikoff** [comment]
Sorry, what exactly do we need to do here?

cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
> Sorry, what exactly do we need to do here?

We are going to have to figure that out. :D I think @ryanfeeley is asking/saying "is gravatar really causing so much confusion? Does it really have so many problems? If so, rip it out."

**Comment by shane-tomlinson** [comment]
@ryanfeeley [this graph might make your eyes pop](https://app.datadoghq.com/dash/59141/fxa-content---avatars). That is # of "Gravatar not found" errors vs # of gravatar/change screen views. The user's Gravatar is fetched as soon as the view renders, and ~ 90% of attempts fail. I opened #5010 to see if it could be a sizing issue like we saw while testing. Instead of using one size to check for existence, and another for display, I use the size we use for display universally.

If that doesn't improve the numbers, I'd say RIP IT OUT!

**Comment by vladikoff** [comment]
@jrgm could we run these queries and give us results in an email (private):

> SELECT COUNT(*) FROM fxa_profile.avatars WHERE providerId='2';

> SELECT COUNT(*) FROM fxa_profile.avatars WHERE providerId='1';

Need to check that 1 and 2 are correct where 1 is gravatar and 2 is fxa 

![image](https://cloud.githubusercontent.com/assets/128755/25487984/ce18ae5a-2b33-11e7-9b85-d988ce047252.png)
