### ISSUE TITLE
Web sessions appearing in large numbers in device manager

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4938]
It looks like my old sessions are lingering a long time. I think this amount very rapidly makes the device manager pointless. Is there a better way to do this?
<img width="375" alt="screenshot 2017-04-11 14 27 22" src="https://cloud.githubusercontent.com/assets/68213/24924514/0bcfaed8-1ec3-11e7-93eb-19c67b647f90.png">
Google seems to only log meaningful actions and not simply sign-ins to Settings: https://myaccount.google.com/notifications

**Comment by rfk** [comment]
That Google link is more akin to the "security event history" feature that @vbudhram was pitching: https://github.com/mozilla/fxa-features/issues/59

**Comment by rfk** [comment]
@ryanfeeley how on earth did you get so many? :-P

I wonder if this is due to e.g. using https://accounts.firefox.com/clear or other tricks to login on the web multiple times without destroying the previous session.

Anyways, I agree this long list makes the view much less useful.  Things we might consider:

* Timing out web login sessions after some period of inactivity
* Collapsing them in the view, e.g. saying "13 Web Sessions" and then allowing the user to expand the list if interested.

**Comment by ryanfeeley** [comment]
@rfk I rarely use "clear", but am definitely logging in a lot (remember my browser still has the bug where I have to sign in every time I go to /settings)

**Comment by shane-tomlinson** [comment]
I found that every time I log into an OAuth site, a new web session is created, which could add to the problem.

<img width="560" alt="screen shot 2017-04-20 at 21 20 52" src="https://cloud.githubusercontent.com/assets/848085/25252263/367e2292-2614-11e7-9a3f-6e0931c889a8.png">

**Comment by rfk** [comment]
> I found that every time I log into an OAuth site, a new web session is created,
> which could add to the problem.

Are we making you re-enter your FxA password every time this happens?

**Comment by shane-tomlinson** [comment]
> Are we making you re-enter your FxA password every time this happens?

Yes, this happens with the [oauth_settings_clients functional test](https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/oauth_settings_clients.js#L45). The original session is not Sync based, so the user must enter their password every time.

**Comment by ryanfeeley** [comment]
@vladikoff Should this be assigned to me or anyone at this point?

**Comment by vladikoff** [comment]
@ryanfeeley what is the action / TODO here?

**Comment by ryanfeeley** [comment]
@vladikoff Make it stop, for the love of all that's holy.

**Comment by vladikoff** [comment]
@ryanfeeley what do you want to do with the session list? hide old sessions? make font-size: 9px ?

**Comment by ryanfeeley** [comment]
@vladikoff Replace sessions from the same browser?

**Comment by ryanfeeley** [comment]
@vladikoff Meaning kill the previous session when I sign in from the same browser.

**Comment by vladikoff** [comment]
@ryanfeeley "same browser" do you mean "same device"? (I can have 10 devices with the "same browser"  Firefox 53)

**Comment by ryanfeeley** [comment]
@vladikoff Same browser on the same device. e.g. Nightly and Release can have separate sessions.

**Comment by rfk** [comment]
> kill the previous session when I sign in from the same browser.

We should definitely try to do a more thorough job of this; this view makes it very clear that we're currently quite liberal about leaving orphaned session tokens lying around in the db.

Sadly I'm not sure we can do that reliably in all cases, e.g. the bug where you have to sign in again after going to "manage account" happens because the browser "forgets" that it already had a session token, so it can't destroy it before generating a new one.

> Make it stop, for the love of all that's holy

We also have the option of feature-flagging this back off in the short term, if we think it's going to be more confusing then helpful to users overall.  We could e.g.:

  * feature-flag it back down to only a limited handful of accounts
  * add metrics on the number and types of devices that users *would* be seeing in this view in the wild, if we don't have that already
  * try some things to reduce the likelihood of old orphaned session tokens lying around and then resume the feature rollout

@ryanfeeley thoughts?

**Comment by vbudhram** [comment]
from uno: not shown, closing for now
