### ISSUE TITLE
Display name returned an invalid parameter on 🍤

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5046]
Adding a 🍤 to the display name after the screen was expanded for a few minutes returned this error.
<img width="529" alt="screenshot 2017-05-09 11 35 18" src="https://cloud.githubusercontent.com/assets/68213/25866165/886dc856-34c3-11e7-91c1-8230580464dc.png">

**Comment by rfk** [comment]
> after the screen was expanded for a few minutes

FWIW this part doesn't seem necessary, I reproduces this by just attempting to enter the suggested name without any waiting period.

I assume the underlying issue here is the MySQL-unicode-handling weirdness from https://github.com/mozilla/fxa-profile-server/issues/186, but there's a secondary issue with the formatting of the error message.

**Comment by vladikoff** [comment]
fixed in https://github.com/mozilla/fxa-profile-server/pull/248
