### ISSUE TITLE
tests: node.js response headers are always lowercase.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5086]
This is more a question, than an issue, but I've never understood this bit of code here: https://github.com/mozilla/fxa-content-server/blob/master/tests/server/routes.js#L288-L292

In the client http response object, the `headers` keys are **always** lowercase, no matter what capitalization was returned from the server over the wire. ref: http://nodejs.org/dist/latest-v4.x/docs/doc/api/http.html#http_message_headers

Can I just remove the uppercase check? I don't see how that is ever true.

**Comment by shane-tomlinson** [comment]
> Can I just remove the uppercase check? I don't see how that is ever true.

I wrote the original check, I remember seeing two different casings. Maybe I was looking at the response source code from the server's point of view instead of the response object from the client's. Maybe I didn't realize they were normalized. At any rate, if the tests still pass, rip out the uppercase check.
