### ISSUE TITLE
Can't log in on Nightly 55

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla/fxa-content-server#5171]
Hi, for some reason I cannot get the login page to load on NIghtly 55. I think it was working a few weeks ago and I haven't changed my version for a while. I tried it with 3 separate accounts and two just get a spinning wheel and another a blank page. It works with Nightly 56 but for other reasons I am not ready to switch to that version. Is there any way to fix this for this version? It is also affecting sync. In the sync log since June 17 I see an issue with token.services.mozilla.com. When I try to load the page with my main profile I get and inspect element I see the error "Response not received for: fxaccounts:fxa_status."

**Comment by shane-tomlinson** [comment]
@newsjunkie247 - Thanks for the report - It is likely that the version of Firefox 55 Nightly that you are using does not yet have support for responding to the `fxaccounts:fxa_status` message that you mention.

Firefox 55 is now in Beta, it is no longer on the Nightly channel. Nightly has moved on to Firefox 56. Since Nightly is a test bed for landing new features, old versions of Nightly are not supported. To get around this issue, you can either use Firefox 55 Beta, or a newer version of Firefox Nightly.

If you still have problems after updating, can you let me know? Thanks again for the report!
