### ISSUE TITLE
Make Login/Registration iFrame on FirstRun Appear to Load Faster

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5180]
For Photon/Quantum, we want to make sure that our iFrame appears to load quickly. It does not necessarily need to have a faster load time but should be perceived as loading faster.

Important considerations:
- A new first run page will be launched with Firefox 56
- We plan to ask for email only first on first run to remove debate of login/registration.

**Comment by philbooth** [comment]
Having had a look with WebPageTest, it seems like the clearest way to make noticeable changes here is via some form of server-side rendering so that we can get markup onto the screen quicker without waiting for all of the JS to download first.

@shane-tomlinson I know we've talked vaguely about this topic in the past, what do you think about me trying to dig into it properly?

* [Results](https://www.webpagetest.org/result/170724_S1_14VY/) (traffic-shaped as 3G)
* [Median waterfall](https://www.webpagetest.org/result/170724_S1_14VY/3/details/#waterfall_view_step1)
* [Median video](https://www.webpagetest.org/video/view.php?id=170724_S1_14VY.3.0)

**Comment by philbooth** [comment]
Whoops, came up in the meeting is already working on this, taking my face off it.

**Comment by rfk** [comment]
> It does not necessarily need to have a faster load time but should be perceived as loading faster

From conversation with @shane-tomlinson, it's not obvious what metric we actually want to use to measure this, or whether we're already collecting it.

**Comment by philbooth** [comment]
> ...it's not obvious what metric we actually want to use to measure this, or whether we're already collecting it.

Speed index! It's the best (only?) measure for the visual impression of performance.

Although it can be inferred using resource timing (which we're not doing), it's best measured synthetically rather than with RUM imho. I took some baseline timings with WebPageTest at the start of the quarter (demoed in Show & Tell a few weeks back), we should be able to compare against those?

**Comment by rfk** [comment]
Thanks @philbooth, that works for me if we're all on board with it.  It's not specific to perception of the iframe, but I guess that's OK.

**Comment by rfk** [comment]
Assigning this to @davismtl to have a kickoff and escalate this into a feature card.  I'm not sure what the means for it being in the Crouton milestone.

**Comment by davismtl** [comment]
Feature card here:
https://projects-beta.growthhackers.com/cards/make-login-registration-iframe-feel-faster/A_hRzvy5pPyOaJ1NAGNkag

Kick-off scheduled for Thursday 8:30 am (PST). Leif, Feeley and Shane are on the invite. Shane expressed interest in the meetings yesterday to work on this since he feels like he'll wrap up the CAD on login pretty soon.

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/5466

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/5483
