### ISSUE TITLE
Sign-up flow: Add a “confirm password” field to minimize errors entering password, minimizing password reset.

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#5193]
This would be adding a second password text field, to make sure the user doesn't incorrectly type their password when signing up.

**Comment by aayushis12** [comment]
Hi,
I would like to get this assigned to me as my first bug.I am a beginner.
Thanks.

**Comment by rfk** [comment]
Hi @aayushis12, thanks for reaching out!  Unfortunately I think the status of this bug is not clear, and @seanmonstar already has a working PR for this issue.  I'm going to go ahead and remove the "good-first-bug" label from this since it's already in progress, sorry for the confusion.

Taking a look at some other bugs, I think this one would be a good starter if you're interested:

  https://github.com/mozilla/fxa-content-server/issues/4928

It should be fairly approachable and self-contained, but is also an important security enhancement.  Let me know if you're interested and I can add more details over in that bug.
