### ISSUE TITLE
Device Manager: Make device icons accurate 

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#5203]
(e.g. Pixel is not a Tablet, Amazon Fire is not a phone)

**Comment by seanmonstar** [comment]
It appears that if the browser is syncing, the [user agent looks like](https://dxr.mozilla.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/FxAccountConstants.java#40) this: `Firefox-Android-FxAccounts/56.0 (Firefox)`

It wouldn't seem that there is a way to differentiate on form factor. Does my investigation seem correct?

If so, is the action here to get a form factor back into the user agent sent during calls to `/certificate/sign`? Thus, an update to the fennec android code?

**Comment by rfk** [comment]
I have this vague recollection that we changed that to start sending more info; @philbooth can you add any context about the plan here, or possibly even dup this to an existing bug that we can put into the "Q3 Quality" milestone?

**Comment by philbooth** [comment]
On the client side, there is a bug to improve the Android user-agent string here:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1350768

An equivalent iOS bug was completed some time ago.

On our side, we recently made an abortive attempt to add a `uaFormFactor` column to the `sessionTokens` table in mozilla/fxa-auth-db-mysql#259, which got rolled back in mozilla/fxa-auth-db-mysql#262. Now that we have redis, we can just add it there instead.

I confess that I didn't realise this was on a Q3 backlog, otherwise I would have done it already, sorry.

**Comment by philbooth** [comment]
In an effort to be exhaustive, I collated a bunch of user agent strings from my own devices and the internet, then connected them to FxA to see which icon we assigned to each one.

Results:

Browser|Expected icon|Correct?|Full user agent string
-------|-------------|--------|---------------------
Firefox desktop (Mac)|MacBook|yes|Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:57.0) Gecko/20100101 Firefox/57.0
Firefox desktop (Windows)|Windows laptop|yes|Mozilla/5.0 (Windows NT 10.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Firefox desktop (Linux)|Linux laptop|yes|Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
Fennec (mobile)|Android phone|yes|Mozilla/5.0 (Android; Mobile; rv:40.0) Gecko/40.0 Firefox/40.0
Fennec (tablet)|Android tablet|yes|Mozilla/5.0 (Android; Tablet; rv:40.0) Gecko/40.0 Firefox/40.0
Fennec (mobile)|Android phone|yes|Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0
Fennec (tablet)|Android tablet|yes|Mozilla/5.0 (Android 4.4; Tablet; rv:42.0) Gecko/42.0 Firefox/42.0
Fennec (mobile)|Android phone|yes|Mozilla/5.0 (Android 7.1.2; Mobile; rv:56.0) Gecko/56.0 Firefox/56.0
Fennec (tablet)|Android tablet|yes|Mozilla/5.0 (Android 7.1.2; Tablet; rv:56.0) Gecko/57.0 Firefox/57.0
Fennec (mobile)|Generic phone|yes|Mozilla/5.0 (Maemo; Linux armv7l; rv:10.0) Gecko/20100101 Firefox/10.0 Fennec/10.0
Fennec (mobile)|Generic phone|yes|Mozilla/5.0 (Maemo; Linux armv7l; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 Fennec/10.0.1
Firefox iOS (iPod)|iPhone|yes|Mozilla/5.0 (iPod touch; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4
Firefox iOS (iPhone)|iPhone|yes|Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4
Firefox iOS (iPad)|iPad|yes|Mozilla/5.0 (iPad; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4
Safari iOS (iPhone)|iPhone|**NO**|Mozilla/5.0 (iPhone; CPU iPhone OS9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143
Safari iOS (iPhone)|iPhone|yes|Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1
Safari iOS (iPhone)|iPhone|yes|Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1
Safari iOS (iPad)|iPad|yes|Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25
Safari iOS (iPad)|iPad|yes|Mozilla/5.0(iPad; U; CPU iPhone OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B314 Safari/531.21.10
Safari iOS (iPad)|iPad|yes|Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A406 Safari/8536.25
Safari desktop|MacBook|yes|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
Chrome Android|Android phone|yes|Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19
Chrome iOS|iPhone|yes|Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1
Chrome iOS|iPhone|yes|Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; en-gb) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3
Chromium Webview|Android tablet|yes|Mozilla/5.0 (Linux; U; Android 4.1.1; en-gb; Build/KLP) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Chromium Webview|Android phone|yes|Mozilla/5.0 (Linux; Android 4.4; Nexus 5 Build/_BuildID_) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
Chromium Webview|Android phone|yes|Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.65 Mobile Safari/537.36
Edge desktop|Windows laptop|yes|Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42..2311.135 Safari/537.36 Edge/12.10136
Camino|MacBook|yes|Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:2.0.1) Gecko/20100101 Firefox/4.0.1 Camino/2.2.1
SeaMonkey|Windows laptop|yes|Mozilla/5.0 (Windows NT 5.2; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 SeaMonkey/2.7.1
SeaMonkey|MacBook|yes|Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 SeaMonkey/2.7.1
SeaMonkey|Linux laptop|yes|Mozilla/5.0 (X11; Linux i686; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 SeaMonkey/2.7.1
FirefoxOS (mobile)|Generic mobile|yes|Mozilla/5.0 (Mobile; rv:26.0) Gecko/26.0 Firefox/26.0
FirefoxOS (tablet)|Generic tablet|**NO**|Mozilla/5.0 (Tablet; rv:26.0) Gecko/26.0 Firefox/26.0
FirefoxOS (TV)| Generic laptop|yes|Mozilla/5.0 (TV; rv:44.0) Gecko/44.0 Firefox/44.0

So from that, two user agent strings produced the wrong icon. One of them, a FirefoxOS tablet that shows up as a phone, I presume we're not too bothered about. The other one, a Safari WebView on an iPhone, shows a generic phone icon rather than an iPhone icon. This is the offending user agent string:

```
Mozilla/5.0 (iPhone; CPU iPhone OS9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143
```

@ryanfeeley, do you have some other concrete examples of the wrong icon showing up? Can you provide the user agent string for the offending browser?

**Comment by philbooth** [comment]
> The other one, Safari on an iPhone, shows a generic phone icon rather than an iPhone icon. This is the offending user agent string:
>
> ```
> Mozilla/5.0 (iPhone; CPU iPhone OS9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143
> ```

This originates from `node-uap` in the auth server. It returns the following OS information for that user agent string:

```js
{
  family: "Other",
  major: null,
  minor: null,
  patch: null,
  patchMinor: null
}
```

I can open an issue over there but in the meantime we'd have to special case the user agent string in our own code, or make our own fork of `node-uap` that returns appropriate information. Neither of those options appeal to me tbh, it seems like a hack that could unravel quickly for only limited gains.

**Comment by philbooth** [comment]
> ...we'd have to special case the user agent string in our own code, or make our own fork of node-uap that returns appropriate information.

Or find another user agent string parser, of course. I'll have a look around now, see what's about.

**Comment by philbooth** [comment]
> Or find another user agent string parser, of course. I'll have a look around now, see what's about.

With the user agent strings from https://github.com/mozilla/fxa-content-server/issues/5203#issuecomment-321535010 as a test suite, I compared the results from 3 different user agent parsers. I don't think we'll find better results elsewhere. Full results:

https://gist.github.com/philbooth/c836ed182b03c12afb2de66e637eea11

**Comment by philbooth** [comment]
I forgot about Sync user agent strings in https://github.com/mozilla/fxa-content-server/issues/5203#issuecomment-321535010. Here's more results driven by some Sync user agent strings copied from various bugzilla issues:

Expected icon|Correct?|Full user agent string
-------------|--------|---------------------
Generic laptop|yes|Firefox/49.0a1 FxSync/1.51.0.20160524173017.desktop
Windows laptop|yes|Firefox/49.0a1 (Windows NT 6.1; WOW64) FxSync/1.51.0.20160524173017.desktop
Android phone|**NO**|Firefox AndroidSync 1.51.0.0 (Firefox)
Android phone|yes|Firefox-Android-FxAccounts/34.0a1 (Nightly)
iPhone|yes|Firefox-iOS-FxA/5.3 (Firefox)

https://github.com/mozilla/fxa-content-server/issues/5203#issue-240289340 also mentions the Kindle Fire specifically (it mentions the Pixel too but I have one of those and it appears correctly). Here are some results driven by Kindle user agent strings copied from the internet:

Expected icon|Correct?|Full user agent string
-------------|--------|---------------------
Generic tablet|**NO**|Mozilla/5.0 (Linux; U; en-US) AppleWebKit/528.5+ (KHTML, like Gecko, Safari/528.5+) Version/4.0 Kindle/3.0 (screen 600×800; rotate)
Android tablet|**NO**|Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Kindle Fire Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Android tablet|yes|Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.1.0-80) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=true

Digging into the bad ones now...
