### ISSUE TITLE
Nightly does not get the "use-logged-in" experience for OAuth reliers

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5209]
The "Sign in" blue button is gone in Nightly. in stable there is no form, just a sign in button 
## Expected

![](http://v14d.com/i/595cf365c28bd.jpg)

## Actual

![](https://i.imgur.com/PJ5PVZb.gif)

cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
I believe the problem is the way Firefox checks whether the user is in private browsing mode when E10s is enabled:


<img width="700" alt="screen shot 2017-07-06 at 13 38 16" src="https://user-images.githubusercontent.com/848085/27911445-fbb5765a-6250-11e7-8c37-a41190e9bcf7.png">

The relevant portion of Firefox code is: https://dxr.mozilla.org/mozilla-central/rev/211d4dd61025c0a40caea7a54c9066e051bdde8c/services/fxaccounts/FxAccountsWebChannel.jsm#350

With E10s disabled, everything works as expected.

cc @mhammond - I suspect we need a new way to check for the existence of PB mode w/ E10s enabled.

**Comment by shane-tomlinson** [comment]
Opened an issue against Firefox in bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1378766

**Comment by shane-tomlinson** [comment]
I have filed a Firefox patch here: https://reviewboard.mozilla.org/r/156572/diff/1#index_header

**Comment by vladikoff** [comment]
Fixed, tested via https://github.com/mozilla-services/fxa-testing-e2e/pull/22 on Nightly
