### ISSUE TITLE
Edits to FxA form for testing in /firstrun

### ISSUE THREAD

**Issue by ejregithub** [mozilla/fxa-content-server#5362]
We would like to make the following changes in order to run a test with the FxA form on /firstrun.

- Remove copy at top of form "Create a Firefox Account to continue to Firefox Sync"
- Create two version of the form, with two tabs  
Version A - Tab 1 - sign up tab (on top), Tab 2 log in tab (subordinate)
Version B - Tab 2 - log in tab (on top), Tab 1 sign up tab (subordinate)

Mockups of these may be seen in the document [here](https://docs.google.com/document/d/19u0GtvRpnZMbM6l3YrxYsuN1JugV0U_pnB8L5bhMQQs/edit#)  along with the hypotheses we want to test requiring this work.

**Comment by rfk** [comment]
Assigning to @davismtl in the first instance to help us triage this request, since I know there's been a lot of discussion about first-run-related changes recently.

> Create two version of the form, with two tabs

From the linked mockups, it's not clear whether these tabs live in the FxA login form itself, or are part of the containing page.

**Comment by davismtl** [comment]
I think the simplest thing for us to do is to remove the copy at the top and have the Moz org team create the tabs that toggle between a sign-in form and the registration form. The important thing will be to load the default visible one first for performance reasons. The hidden one can take a bit longer to load.

If this works for @ejregithub and @rfk then all that is needed from FxA is to remove copy and we can do that really quickly since it is currently blocking them from running their tests.

**Comment by rfk** [comment]
>  all that is needed from FxA is to remove copy

Do we want it removed for *every* instance of the form on the firstrun page, or only for forms loaded as part of this experiment.

**Comment by davismtl** [comment]
Certainly only for forms that are loaded as part of this experiment.

I expect there to be a couple more requests like this in the near future (to support firstrun tests) so we should try to follow that principal until we're sure of the results.

**Comment by rfk** [comment]
OK.  Currently the first-run page opts in to its minimalist styling by loading the page with a special `"?style=chromeless"` query parameter, so one option may be to add additional `?style=blah` options to support these different variants.  We'll need @shane-tomlinson's input here on the right way to manage this while avoiding a combinatorial explosion of styling options.

**Comment by ejregithub** [comment]
@jpetto - adding Jon, who can provide better insight as to what is feasible/preferred for implementing that tab structure.

**Comment by jpetto** [comment]
One important thing to note is that mozilla.org currently is not set up to handle two FxA iframes loaded on a single page. For example, we may need to re-think our `postMessage` approach, as we currently have no way of knowing which iframe sent the message (as they would have the same `origin`). Additionally, some events should impact *all* iframes, e.g. when a user resizes their browser.

I'm sure there are things I'm missing here, but point is we'll need to do some investigation and testing to get two iframes running simultaneously.

Just brainstorming, but would it be feasible/better to have the "log in/sign up" tabs exist on the mozilla.org side that interact with a single iframe, changing views within the iframe when each tab is clicked? This could potentially be done with a postMessage in to the iframe, or changing the `src` of the iframe altogether...

> The important thing will be to load the default visible one first for performance reasons. The hidden one can take a bit longer to load.

Can you expand on this a bit?

**Comment by vladikoff** [comment]
@davismtl @ryanfeeley could you help us prioritize this work?

**Comment by rfk** [comment]
> or changing the src of the iframe altogether

This sounds like the simplest approach, can we try this out and see whether it performs acceptably before taking on any larger refactor within either FxA or moz.org?

**Comment by shane-tomlinson** [comment]
> This sounds like the simplest approach, can we try this out and see whether it performs acceptably before taking on any larger refactor within either FxA or moz.org?

@jpetto - This seems like a reasonable first step to me. The static resources should be cached, the HTML will need to be re-downloaded, though I don't think that should be terrible in practice.

@ejregithub - Out of curiosity, is this toggle between signin/signup even needed with the email-first flow? Seems like a lot of effort that could potentially be avoided with a new flow that only asks the user for their email address and redirects them to the right page. You can try it now at:

https://accounts.firefox.com/?action=email&service=sync

@jpetto - you can test within the firstrun iframe using:

https://accounts.firefox.com/?action=email&service=sync&context=fx_firstrun_v2

**Comment by jpetto** [comment]
> Out of curiosity, is this toggle between signin/signup even needed with the email-first flow? Seems like a lot of effort that could potentially be avoided with a new flow that only asks the user for their email address and redirects them to the right page.

I was just talking with @ejregithub about this yesterday. Had I known this was in the works, I would have suggested we go this route first.

@shane-tomlinson How close is that new flow to being production ready?

**Comment by ryanfeeley** [comment]
I know we have:
https://accounts.firefox.com/signin?email=thinghere@someemail.com
and
https://accounts.firefox.com/signup?email=thinghere@someemail.com

But what we need is something generic and throttled that precedes the above, and directs the user to the appropriate one.

**Comment by shane-tomlinson** [comment]
> I was just talking with @ejregithub about this yesterday. Had I known this was in the works, I would have suggested we go this route first.
>
> @shane-tomlinson How close is that new flow to being production ready?

Pretty close....  it's in prod now behind a feature flag with dual explicit goals:

* Have your team play with it and give us feedback.
* Have QA do their best to break it (which they will).

Assuming a green-light from QA, starting the week of Aug 28th, we are going to start A/B testing on users that open FxA from about:preferences#sync. Note, this test won't affect the firstrun page, you'll have to opt-in to the behavior.

**Comment by davismtl** [comment]
@jpetto The retention marketing team is aware that the email first flow is under way and ready for production soon. However, they still wanted to test both since they are popular login/registration flows.

If you think that this current test may be too much work, we should have a discussion with them.

Also, it was brought to my attention that they haven't been collaborating with the onboarding team much so we should make sure they have sign off on this test.

**Comment by ryanfeeley** [comment]
A question for @jpetto. Which pages were you planning on making the toggle bar appear? I think it makes sense for the bar to appear when the user is on login or registration, but should not appear otherwise as there are dozens of other screens that users land on, even in the iframe. Is it possible to only show it on registration form or login form?

**Comment by ryanfeeley** [comment]
BTW, here are the top browser window sizes for current first run users.

Browser Width | Browser Height | %
-- | -- | --
1350 | 660 | 17.69%
1250 | 680 | 5.43%
1250 | 850 | 5.25%
1010 | 660 | 4.01%
1250 | 840 | 3.89%
1260 | 920 | 3.13%
1250 | 650 | 2.46%
1350 | 630 | 1.60%
1250 | 820 | 1.58%
1350 | 600 | 1.56%
1010 | 640 | 1.55%

**Comment by jpetto** [comment]
> A question for @jpetto. Which pages were you planning on making the toggle bar appear? I think it makes sense for the bar to appear when the user is on login or registration, but should not appear otherwise as there are dozens of other screens that users land on, even in the iframe. Is it possible to only show it on registration form or login form?

Yes, the plan is to only show this new version on `/firstrun`. Other pages with the FxA form would/should remain unchanged.

**Comment by jpetto** [comment]
> If you think that this current test may be too much work, we should have a discussion with them.

I'm not really sure how to answer this one. We can do the tabbed test, the question is whether is it worth the time and effort. IMO, the email first flow is the obvious way to go - guided process, adaptive functionality, and fewer competing UI elements. I'm all for testing assumptions, but we also can't be afraid to make decisions. If it were up to me, we would switch to the email first flow, drop the sunrise animation, and test different copy.

If we wanted to be more methodical about it, we could test the current page as-is against the email first flow.

I'm not sure who the decision makers are for this experiment, but it seems we need to re-declare the intended hypothesis before moving forward.

**Comment by rfk** [comment]
> I'm not sure who the decision makers are for this experiment

@davismtl per [1], can you please take the action to ensure that the onboarding team and retention marketing team are in alignment on this test and the intended hypothesis?

>  is this toggle between signin/signup even needed with the email-first flow?

From the FxA side of things, I think the ask will actually be the same regardless of whether we do a toggle or use the email-first flow: can we remove the "[Do Action] to continue to Firefox Sync" heading from the content in the iframe, and allow the surrounding page to provide its own heading instead?  @shane-tomlinson any thoughts on how we could most easily manage this, either as in [2] or otherwise?

> > Which pages were you planning on making the toggle bar appear? 
> Yes, the plan is to only show this new version on /firstrun. 

Without wanting to put words in his mouth, I think what @ryanfeeley was asking in [3] is whether we can avoid showing the toggles when the iframe contains something other than the signup/signin form, so we can avoid ending up in confusing UI states.

I did a super quick mockup of the tabs-outside-the-iframe approach, and it's pretty easy to get into weird states.  Here's the starting point, assuming that we hide the header in the iframe as described above:

<img width="280" alt="capture" src="https://user-images.githubusercontent.com/34695/29548882-d2302b60-8747-11e7-8a42-db7d6ef63e84.PNG">

Right away there's the potential for confusion: if I want to create an account, do I click "sign up" in the tabs or the "create an account" link below the form?  If I choose the later I get this:

<img width="273" alt="capture" src="https://user-images.githubusercontent.com/34695/29548933-26b6e1a6-8748-11e7-8658-dcdd3c2df82f.PNG">

In which the form is out of sync with the tabs at the top.  Do we also need to hide the "create account" link?  It's hidden in the linked google doc, but I didn't notice that until after I tried this out.

Conversely, I might have forgotten my password and find myself going through states such as these:

<img width="274" alt="capture" src="https://user-images.githubusercontent.com/34695/29548989-975727b8-8748-11e7-9a87-0b0dd4977759.PNG"> <img width="268" alt="capture" src="https://user-images.githubusercontent.com/34695/29549004-b434df74-8748-11e7-8751-b989941ae48e.PNG">

Which don't seem too bad, but maybe not ideal?

Fortunately a successful signin causes the iframe to be hidden, but you can imagine a scenario where we might accidentally wind up showing the FxA settings page in that iframe after login, which could get quite confusing if it still says "log in | sign up" at the top of the page.

I believe it's possible for the containing page to listen for a "navigated" message from the iframe [4] and show/hide/change the toggles based on what's being shown in the form.  But is it as simple as hiding the toggles after any navigation event inside the iframe?

[1] https://github.com/mozilla/fxa-content-server/issues/5362#issuecomment-323426201
[2] https://github.com/mozilla/fxa-content-server/issues/5362#issuecomment-322647439
[3] https://github.com/mozilla/fxa-content-server/issues/5362#issuecomment-323433370
[4] https://github.com/mozilla/fxa-content-server/blob/master/docs/relier-communication-protocols/firstrun.md#navigated

**Comment by davismtl** [comment]
I have asked PDol to review this test and return to us with a final sign off once he's spoken to Marketing, Moz org and rest of onboarding team.

He seems to agree with the hypothesis of the test but there might be some new feedback that needs to be taken in account. He should get back to us by tomorrow.

**Comment by jpetto** [comment]
@ejregithub Can you comment here on the experiment that agibson has started on? Want to make sure we don't have duplicated/poorly-timed effort going on.

**Comment by pdolanjski** [comment]
I'm fine with the experiment.  We just wanted the copy (outside this form) reviewed by Michelle H. if we were planning to ship the successful branch.  I'll leave it to you guys if you want to run this in advance of testing a unified email field for sign-in/up.

**Comment by davismtl** [comment]
According to Michelle Warther, the 2 tabs test will not be done. They believe that the email first flow is probably the most beneficial all around.

They will be performing a copy test instead which they might want to review with @ryanfeeley 

I will close this issue since it is no longer relevant.
