### ISSUE TITLE
"Account no longer exists" after changing a password after switching primary email

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5394]
STRs, I think:
- get two devices - A and B (i'm trying this with Android)
- login on both of them
- on device A, switch primary email
- on device A (or desktop, not device B) change account password
- device B is now in a "sync not connected" state. Tapping "cannot connect, sign in" button in sync prefs opens an accounts page which displays a "Create a Firefox Account" dialog. Sometimes it has a red banner "account no longer exists, recreate it?" at the top - but often that banner slides away as the page loads.

What I think roughly happens is that account information (email) is obtained by the content page via Accounts:Exist interface. Android doesn't yet update account's email internally when a primary email switchover happens, and so it will send a secondary email.
The content page then does the wrong thing - it should recognize that the email is a secondary one for an existing account.

Even once Android supports primary email changeover properly, it seems it will still be possible that it might miss that event in some situations, and provide the now-secondary when asked about Firefox Account info. about:accounts pages should ideally handle these corner cases.

**Comment by rfk** [comment]
I tried this on two desktop devices and it also gave me a bad, although not catastophic, user experience.  After tapping "reconnect to sync", it:

* Opened a new tab for the sign-in form
* Briefly showed a "500 server error" page of some kind, I didn't catch it entirely
* Flickered and transitioned to an empty "sign in" form

**Comment by rfk** [comment]
> Flickered and transitioned to an empty "sign in" form

Also, after signing back in, desktop firefox still says I'm logged in with my *old* primary email address, not the new one.

**Comment by rfk** [comment]
From "network" tab in devtools, the sequence of events here seems to be:

* Content-server is loaded with https://accounts.firefox.com/force_auth?service=sync&context=fx_desktop_v3&uid=foobar&email=old-email@example.com i.e. specifying both the email and uid.
* It passes the old email to https://api.accounts.firefox.com/v1/account/status and gets back "exists: false".  Should this return `true` since it exists as a secondary email?
* It does a `GET https://api.accounts.firefox.com/v1/account/status?uid=foobar` but doesn't receive a response...maybe it navigates away from the page before the request completes?
* It reloads the page to https://accounts.firefox.com/signin?service=sync&context=fx_desktop_v3 without all the other query parameters, showing the blank signin form

Somewhere in there it also logged an "Unexpected error" but I can't clean any useful info from the minified traceback.

**Comment by shane-tomlinson** [comment]
Ref #4316

**Comment by shane-tomlinson** [comment]
@vbudhram - can you triage this?

**Comment by vladikoff** [comment]
from mtg: cc @vbudhram
