### ISSUE TITLE
email_type property is missing on amplitude click events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5541]
Reported by @davismtl:

> we don't track the email_type property for the fxa_email - click event

Which is weird. We have [code](https://github.com/mozilla/fxa-content-server/blob/d3b00a1a7d487cd394d2614961efaad49dee12a9/server/lib/amplitude.js#L201-L206) for it:

```js
function mapEmailType (eventCategory) {
  const email_type = EMAIL_TYPES[eventCategory];
  if (email_type) {
    return { email_type };
  }
}
```

And tests:

* https://github.com/mozilla/fxa-content-server/blob/d3b00a1a7d487cd394d2614961efaad49dee12a9/tests/server/amplitude.js#L503-L520

* https://github.com/mozilla/fxa-content-server/blob/d3b00a1a7d487cd394d2614961efaad49dee12a9/tests/server/amplitude.js#L535

* https://github.com/mozilla/fxa-content-server/blob/d3b00a1a7d487cd394d2614961efaad49dee12a9/tests/server/amplitude.js#L550

And I can even see it in the logs when I run `fxa-local-dev`:

```
{"op":"amplitudeEvent","time":1506661031804,"device_id":"779bc9148bf24476a0d700759d637f75","event_type":"fxa_email - click","session_id":1506660995749,"event_properties":{"device_id":"779bc9148bf24476a0d700759d637f75","email_type":"registration"},"user_properties":{"flow_id":"b75a1ddc288abba3ad635afec0df1d0ac94351ed588c1f35db23b64129c9853b"},"app_version":"96","language":"en"}
```

**Comment by philbooth** [comment]
I also see it showing up fine in Amplitude itself:

<img width="672" alt="Screen shot showing `fxa_email - click` events grouped by `email_type` in Amplitude" src="https://user-images.githubusercontent.com/64367/31128025-6b25f59a-a848-11e7-8acf-8c28d9bb98f5.png" />

@davismtl, did I get the wrong end of the stick here? Any idea what the problem is?

**Comment by davismtl** [comment]
They are showing up but they are missing properties so they are not mapping to any other event.

Here is a link to a click event, you can see it is isolated and not associated to any other event:
https://analytics.amplitude.com/org/31251/project/178231/search/32606536482?sessionHandle=V7jCZGY_V7jDRqh_eXgEMi_rg3_91ee35bd234145caade4a88d68148dbe&eventId=750e1ed4-a857-11e7-a0d2-06b9186137b2

Here is a funnel of emails sent to click. It says that we have a 2.9% clickrate because the clicks don't map to the sent events:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/19537086/31136946-7f5786fc-a81e-11e7-85c7-cd3eb1ad43f4.png">


In contrast, if we look at the raw counts of emails sent vs email clicks, we have roughly a 50% clickrate:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/19537086/31136836-25dd7a8c-a81e-11e7-81a8-5437264f5213.png">

**Comment by philbooth** [comment]
Thanks @davismtl, I'll close this issue then and open one for the problem you descibe.

**Comment by davismtl** [comment]
I could have sworn that the clicks were also missing the email_type when @jbuck and I tested together but while double checking now, that's not the problem I was running into.

**Comment by philbooth** [comment]
> ...and open one for the problem you describe.

#5549
