### ISSUE TITLE
Implement experiment and experiment_variation properties on amplitude events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5542]
`experiment` and ~~`experiment_version`~~ `experiment_variation` should be added to `user_properties` when they're available.

**Comment by philbooth** [comment]
Correction: `experiment_variation`

**Comment by philbooth** [comment]
I just realised that the proposal from the taxonomy makes it impossible to avoid the same problem that existed in DataDog for #5443: when multiple experiments apply to a user and they use one or more duplicate group names, it is impossible to know which group relates to which experiment.

One alternative would be to lean on Amplitude's `groups` property, which is designed for this kind of problem. For this issue, `experiment` would map to the keys and `experiment_variation` would map to the values. So concretely the event data might look something like this:

```
"groups": {
  "q3_form_changes": "disabled_button_state",
  "disabled_button_state": "control",
  "send_sms": "treatment"
}
```

That's all fine and dandy, except Amplitude has a hard limit of 5 groups, so we'd burn through them pretty quickly.

Instead of that, we could take the same approach within `user_properties`, by applying a common prefix like `experiment_`:

```
"user_properties": {
  "experiment_q3_form_changes": "disabled_button_state",
  "experiment_disabled_button_state": "control",
  "experiment_send_sms": "treatment"
}
```

**Comment by rfk** [comment]
If you haven't already, this is definitely the sort of thing we should ask about in the amplitude slack; we're paying good money for their advice on getting our event taxonomy right :-)

**Comment by davismtl** [comment]
@philbooth and I re-scoped this to keep things super simple.

We will not have experiment and experiment_variation properties, and we'll avoid groups since it will pollute our list of user properties.

Instead, we're going to keep things simple and just have **experiment** where we'll have values as such:
emailfirst_control
emailfirst_treatment

This way, we are sure that the variations are always mapped back to the right experiment. We can also segment on *experiment contains emailfirst* if we want to group that way for whatever reason.
