### ISSUE TITLE
Ensure that temporary settings messages are always visible

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5552]
If you perform an action in Settings, like adding a secondary email, often the message is out of view.

We should keep the message where it is when the user is scrolled to the top, but fix the messages to the top of the window when they are not.

Like this:
![omnipresent](https://user-images.githubusercontent.com/68213/31150013-0ef97662-a860-11e7-8807-d67c0dfe0310.gif)

**Comment by ryanfeeley** [comment]
Related: http://polarblau.github.io/stickySectionHeaders/

**Comment by TDA** [comment]
@ryanfeeley Would a toast message satisfy the same use-case? Albeit with more control to the user to dismiss the notification.

**Comment by anweshknayak** [comment]
@ryanfeeley could you provide me some pointers on how to implement this feature? do I create a new file in mixins folder for the same or what?

**Comment by vladikoff** [comment]
@anweshknayak what might work is - you can find the css for the green message and use something like `position:fixed` or `position:sticky` for it.

**Comment by vladikoff** [comment]
cc @shikhar-scs @himanish-star @anweshknayak

**Comment by anweshknayak** [comment]
Hey @vladikoff I tried this one using both properties as you mentioned. But it doesn't seem to work.

**Comment by himanish-star** [comment]
@anweshknayak, If you don't manage to solve this do ping me. I'll do it :smiley:

**Comment by anweshknayak** [comment]
Sure go ahead @himanish-star

**Comment by himanish-star** [comment]
Ok

**Comment by vladikoff** [comment]
@himanish-star I looked a this a bit and you will probably need to use JavaScript / jQuery to solve this issue. Due to the way the divs are nested `position: sticky` is not gonna work out. 

When the success notification is displayed you need to detect if the user scrolled the window.
If that is true **and** we are in the 500px view (not mobile media query view) only then we need to add `position:fixed` to the success message. Let me know if I need to clarify something.

We also need to add a higher z-index to the success bar because sometimes the avatar placeholder overlaps it.

**Comment by himanish-star** [comment]
yes @vladikoff. Even I had thought for the same.
