### ISSUE TITLE
Changing iOS device name isn't possible

### ISSUE THREAD

**Issue by past** [mozilla/fxa-content-server#5579]
On desktop Firefox it is possible to change the device name in about:preferences#sync. On iOS (android too?) there is no way to do that. I assume this isn't an issue for mozilla/firefox-ios as the fxa page in Firefox for iOS seems to be remote.

**Comment by shane-tomlinson** [comment]
> I assume this isn't an issue for mozilla/firefox-ios as the fxa page in Firefox for iOS seems to be remote.

Thanks for the report! I'm trying to dig in further, but FxA does not provide a way for *anybody* to change the device name. Both Firefox on both desktop and Android provide the functionality from within their own settings rather than ours. We then take that device name. I'm trying to find out whether there are any plans to add similar functionality to Fx for iOS, the nearest thing I can find in Bugzilla is https://bugzilla.mozilla.org/show_bug.cgi?id=1401386 where it hints at using the device name from iOS' system preferences.

My intuition is that this is not actionable on our side unless we add the functionality for all devices, a bugzilla bug may be appropriate.

**Comment by philbooth** [comment]
Discussed in meeting, this needs to be fixed in the iOS client, closing.

**Comment by past** [comment]
Thanks, I'll comment in that bug.
