### ISSUE TITLE
Kill the Maybe Later link until we have a decent destination

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5610]
The Maybe Later link on the SMS page goes to the CAD page which is the same, but without the SMS field. Let's drop that link like a hot potato until it goes somewhere fantastic.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/68213/31737576-ffceb17c-b415-11e7-8e98-818e138b6532.png">

**Comment by rfk** [comment]
I have a vague recollection of us needing some sort of "maybe later" link so that users will understand they don't *have* to put their mobile number in there.  @davismtl do you recall, or did I make that up?

**Comment by davismtl** [comment]
Oh, this experience certainly needs to be fixed.

So... the growth side of me is like "Yes, let's drop it!" because more people will send sms and pair devices. (go growth!)

The "Mozillian" in me think we should keep the "Maybe Later" (or rename it to something else) but send people somewhere relevant like a page that gives them more details on why they should pair their device (Send Tab, Improved Awesome Bar, etc). 

Or heck, maybe we just send them to New Tab with Activity Stream which is probably not a bad thing if you registered on First Run.

Options:
- Remove it now till we come up with something (too aggressive?)
- Send to new tab which should be easy (bad for getting best sync experience)
- Design a basic page with more value prop (more time consuming

@ryanfeeley Small ask in the interim can we make the call to action "Send Firefox directly to your smartphone and sign in to complete set-up *of sync*"

**Comment by ryanfeeley** [comment]
@davismtl For now remove it because it's a glaring bug. We'll add it back in when we have something worth maybe latering.
