### ISSUE TITLE
Replace our password advice with responsive message

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5750]
Re-enable the password strength filters and replace "A strong, unique password will keep your Firefox data safe from intruders." with:
![password-tips-empty](https://user-images.githubusercontent.com/68213/33151557-8f0b7950-cfa6-11e7-862f-e98f5b822f09.png)

**Comment by shane-tomlinson** [comment]
I totally love this idea. Would the firstrun page just use the mobile view?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yeah, that's all that would fit unfortunately.

**Comment by vladikoff** [comment]
Related to https://github.com/mozilla/fxa-bugzilla-mirror/issues/425

**Comment by shikhar-scs** [comment]
If this issue is still up, can I take this up ?

**Comment by shikhar-scs** [comment]
@vladikoff @ryanfeeley @shane-tomlinson

**Comment by vladikoff** [comment]
@shikhar-scs yeap feel free to send a PR for this one!

**Comment by shikhar-scs** [comment]
Thank you @vladikoff . I'm on it and will post a PR soon :grinning:

**Comment by shikhar-scs** [comment]
@vladikoff 

I had a doubt. As I am not well-versed with how the `locales` files are formed, I wanted to know whether I just have to make the changes required in the `fxa-content-server-l10n/locale/en_US/LC_messages/client.po`  file, alongwith the respective changes in `app/scripts/templates/sign_up.mustache` OR all the locales files need to be altered with. Also, how are the locales files formed ? (I'm curious as none of the locales files reflect in the repo on github at all )

**Comment by philbooth** [comment]
@shikhar-scs, don't change the l10n files. If you just make your changes to the templates, there is a separate localisation process to ensure they get translated into all the different languages.

**Comment by shikhar-scs** [comment]
That's a lot of help already :+1: Thank you @philbooth

**Comment by shikhar-scs** [comment]
@vladikoff @philbooth 
Replacing the string was an easy task to perform. However, I spent ample time on the `popover` feature, not to much avail. The real reason being that `main.css` doesn't contain any support for `popovers` and so bootstrap popovers are failing. So in order to make the popover work, I'll have to introduce some custom css, which I guess is not advisable. Is there anything I am missing.

Another question is, there is a bootstrap-popover file in the test folders, but why don't any of the bootstrap popover properties I used work with it ?

My current work has been pushed here, please have a look at https://github.com/mozilla/fxa-content-server/compare/master...shikhar-scs:replace-password-advice

**Comment by vladikoff** [comment]
@shikhar-scs yes you need to introduce new CSS (SCSS in this case). 

> , there is a bootstrap-popover file in the test folders

Could you link to that? if we have something already we can try using it.

**Comment by shikhar-scs** [comment]
@vladikoff Actually it doesn't exist on the main repo here, it is managed by `bower`. In my local directory it exists at `fxa-content-server/app/bower_components/blanket/test/bootstrap/tests/unit/bootstrap-popover.js`

> yes you need to introduce new CSS (SCSS in this case).

ok i'll start with that :+1:
