### ISSUE TITLE
Lockbox login makes you enter your password twice if you open the confirmation link in the lockbox tab

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5891]
From @rbillings in https://github.com/mozilla-lockbox/lockbox-extension/issues/464#issuecomment-363831327:

--------

During testing I got into the create/confirm email loop and have narrowed down the repro steps:

    npm run run > new browser opens w/lockbox extension
    create new account > new window opens
    fill out new account data, submit > confirmation screen displays explaining email has been sent
    open email > COPY the activate link
    return to the new window with the email sent message > PASTE activate link into urlbar

expected: account confirmed
actual: url routes user to create account/signup page, account is never confirmed

** I initially found this as my email lives in a separate browser than the testing browser. I confirmed that if the user has their email in the lockbox original browser window, clicking 'Activate' will confirm the account. However pasting the link into the create account browser window will create the loop.

**Comment by rbillings** [comment]
Doing some more follow-up:
- I cannot repro this with FxA. I was able to sign up, get the email and confirm without a loop - so this does seem to be lockbox specific in some way.
- With FxA account creation, a new browser window isn't opened with the confirm email message.
- Testing FxA I was able to paste in the verify email URL into the FxA original window, or just a new browser window that I opened - and it immediately verified my account without a redirect.

**Comment by vladikoff** [comment]
@rfk the popup url bar is a "disabled" field: 

![image](https://user-images.githubusercontent.com/128755/35994261-dcee2090-0cdd-11e8-9e21-427f46c25764.png)

**Comment by rfk** [comment]
> the popup url bar is a "disabled" field:

Oh.  Hrm, so maybe I totally misinterpreted @rbillings steps to reproduce then...

**Comment by rbillings** [comment]
When I paste the url into the lockbox popup window it redirects to the account sign up page.  When I paste the url into the original browser window the popup gets the checkbox and disappears correctly. 

This may be the source of the issue. When you sign up, the popup window gets the focus - and that's what encouraged me to paste the url there in the first place. I'd have to manually dismiss it or switch back to the original browser in order to get the account to verify correctly.

**Comment by rfk** [comment]
> When I paste the url into the lockbox popup window it redirects to the account sign up page.
> When I paste the url into the original browser window the popup gets the checkbox and
> disappears correctly.

I'm not able to reproduce as you describe it here - any chance you can make a screencast to show what's happening?  Or if it's simpler, let's catch up briefly on Vidyo sometime tomorrow.

> the popup url bar is a "disabled" field

This prevents me from copy-pasting the confirmation URL into the popup, but I am able to navigate it by e.g. dragging-and-dropping the confirmation URL from my email into the popup.  As expected this causes the lockbox login flow to fail, but it doesn't seem to match the symptoms that @rbillings describes above.

**Comment by rbillings** [comment]
Aha! the field IS disabled, but I did a quick copy & paste - and without an error showing and the page redirecting to the sign up it wasn't clear that the field is disabled. It seemed like it took the url and did a redirect, when in fact it just did a redirect.  

A couple of things stand out:
- the lockbox popup retains focus
- no error or message appears outside of the standard confirm your email
- it appeared to redirect based on my input, when it wasn't
- users who don't understand that they need to only copy the URL into the original browser will likely remain confused 
* I did capture a video of this, but it seems unlikely to provide additional info- lmk if you'd like it.
* drag and drop did give a "PKCE parameters missing" verification error

**Comment by rfk** [comment]
> I did capture a video of this, but it seems unlikely to provide additional info- lmk if you'd like it.

Yes please @rbillings, for completeness.

**Comment by rfk** [comment]
> When I paste the url into the lockbox popup window it redirects to the account sign up page.

From the vidyo, this was the piece I misunderstood - at this step you're pasting the FxA confirmation link to the tab with Lockbox in it (the one with a `moz-extension://` URL).  That's the tab that had called `browser.identity.launchWebAuthFlow` and is waiting for the popup window to close and return the OAuth state.  When you replace that tab, the OAuth flow in the popup completes successfully, but there's nothing waiting on the Lockbox side to receive the result.

I'm not sure if there's much we can really do in this case, since it's equivalent to closing Lockbox before the login completes.  The best bet might be to try to avoid the ability navigate the Lockbox tab away, but I'm not sure what's possible there.  @linuxwolf thoughts?

**Comment by linuxwolf** [comment]
@rbillings @rfk 

I might need my own vidyo session, but I am assuming "lockbox popup" refers to the popup window with the FxA signin/signup content, that is launched when clicking a button in a definitely Lockbox-branded page.  This is a correct assumption?

The Lockbox-managed tab doesn't perform any of the OAuth flows; instead it sends a message to a background process to perform them.  It shouldn't matter if the Lockbox-managed tab is open or closed at that point, because the logic is performed in a difference context and/or process.

However, the popup opened by `browser.identity.launchWebAuthFlow()` is not managed by Lockbox, but by Firefox.  If that method returns a URL that does not match our expectations for an OAuth `authz` resposne, Lockbox fails signin (but doesn't surface that to the user in any way).  It's possible the checks are not robust enough, but then I would have expected different internal failures but the same visible result -- the user ends up needing to signin again.

**Comment by rfk** [comment]
From mtg, what this boils down to is that there are some unexpected ways that the user can navigate the OAuth popup and derail the login flow:

* Drag-and-drop a URL into the popup window, e.g. from a confirmation email.  This will navigate the popup to the dropped URL, derailing the OAuth flow.
* Click into the (disabled) urlbar of the popup window, and hit enter.  This reloads the page in the popup, which can throw away in-progress state from the OAuth flow.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1441405 to investigate what we can do about this on the webextension API side.  We *might* be able to figure out some mitigations on our side, but I feel like they'll probably be pretty hairy and maybe not worth it in practice.

**Comment by rbillings** [comment]
I tried to replicate the original issue with race condition scenarios but was unable to repro the bug.

**Comment by rfk** [comment]
from meeting: we fix this by moving away from links and towards codes, WONTFIXing it here.
