### ISSUE TITLE
Webmail-launched FxA popup does not close automatically

### ISSUE THREAD

**Issue by linuxwolf** [mozilla/fxa-content-server#5938]
\[_Related to mozilla-lockbox/lockbox-extension#581_]

When signing into (or signing up for) a Firefox Account and using a webmail service (e.g., Gmail), clicking the "Activate Now" (or "Confirm sign-in") from the received email launches a new browser window.  This page eventually (usually very quickly) displays a "Account Verified" message.  However, this window never closes, nor does it obviously indicate that it is safe to close.

## PREREQUISITES

* signed in with a webmail application (e.g., gmail)

## STEPS

1. Create a new Firefox Account
2. go to webmail, and click "Activate Now"

## EXPECTED

"Account Verified" window closes, or indicates it can be closed.

## ACTUAL

The "Account Verified" window stays open indefinitely.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/757401/36755501-a8ccf8a4-1bc9-11e8-84a2-b7755724fa2e.png">

**Comment by rfk** [comment]
The more I see of the lockbox login flow, the more I want to use codes rather than links for these email loops...

I think having this window close automatically would create a jarring experience for the user.  Is there content we could put in here that would improve the situation?  I can't think of anything *good* but perhaps even just some sort of "OK" button that closes the window would be an improvement.

For sync, we use this landing page as an opportunity to show "connect another device" messaging, but that doesn't seem appropriate for lockbox.

/cc @ryanfeeley

**Comment by vladikoff** [comment]
> I think having this window close automatically would create a jarring experience for the user.

**Comment by vladikoff** [comment]
> I think having this window close automatically would create a jarring experience for the user.

Plus we cannot really close it automatically, unless we opened it. (Which even "Open Gmail" button doesn't do via js)

> indicates it can be closed

We can probably do that

**Comment by linuxwolf** [comment]
I should have added a comment that I agree automatically closing it seems like a bad idea.

Naively, it would seem to me some text -- while far from ideal -- is a stopgap that can actually help users.  Using confirmation codes would seem to fit _this_ flow better yet, but I appreciate that I've not been involved in FxA through all the iterations.

**Comment by vladikoff** [comment]
cc @ryanfeeley , comments?

**Comment by vladikoff** [comment]
from mtg:

* should we tweak the text  

OR

* use verifications codes and not worry about the text / window?

**Comment by rfk** [comment]
>  use verifications codes and not worry about the text / window?

FWIW this is my current favorite option, but tweaking the wording is probably the *smaller* of the two changes, if we want something out quickly.

**Comment by vbudhram** [comment]
> use verifications codes and not worry about the text / window?

I like using verification codes as well, however, they would only work on login. Since it is currently an experiment, we would have to add the `clientId` to the [rollout configuration](https://github.com/mozilla/fxa-content-server/blob/c99b5ca042f9fc3b97f93a5612692a0303f9db2d/app/scripts/lib/experiments/grouping-rules/token-code.js#L10) and put all users in the `treatment-code` group.

**Comment by ryanfeeley** [comment]
I have noticed that when in a pop-up Facebook's OAuth flow closes itself. Perhaps if we know it is a pop-up, it's okay to close, but that we should not do that in a tab. Any way to tell the difference?

**Comment by rfk** [comment]
> I have noticed that when in a pop-up Facebook's OAuth flow closes itself.

IIUC this is not the OAuth popup itself (which does close correctly) but rather a new window opened as a result of clicking the verification link in the email.

**Comment by vladikoff** [comment]
from mtg: we should explore using codes for Lockbox, @rfk will open a new issue for that. Otherwise we cannot close tabs
