### ISSUE TITLE
Send SMS view does not display in some situations

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa-content-server#5965]
When analyzing the results of adding the SMS option on registration, I noticed that a substantial portion of USA registrants don't actually emit an event indicating that they viewed the SMS form. Since SMS should have rolled out to 100% to the USA, I figured I'd file something.

https://analytics.amplitude.com/org/31251/chart/we3j0qs

To investigate, I went through the registration flow a few times, each with a new profile, and in different ways. Here's a summary of what I tried (all on mac os / android):

1. On 58.0.2 (release) registered through first run, verified through email on my phone. After verification, I got redirected to a new tab without seeing the sms. ❌ 
<details>
  <summary>console log</summary>
this._recipeManager is null  
LoginManagerParent.jsm:86
receiveMessage resource://gre/modules/LoginManagerParent.jsm:86:9
receiveMessage jar:file:///Applications/Firefox.app/Contents/Resources/browser/omni.ja!/components/nsBrowserGlue.js:185:15
receiveMessage self-hosted:994:17
</details>

2. On 58.0.2 (release) registered through first run, verified through email in a different tab. After verification, I got the app store buttons without the sms option. ❌ 

3. On 58.0.2 (release) registered through first run, verified through email in the same (parent) tab. After verification, I DID get the SMS. ✅ 

4. On 58.0.2 (release) registered through link in settings via menupanel, verified on phone and DID get the SMS (on the desktop). ✅ 

5. Same as 4, but through send-tab (same result as 3) ✅ 

6. On 60 (nightly) same as 4, same result. ✅ 

(nightly doesn't show the fxa login on firstrun)

Apologies if this is all known behavior, but I couldn't find an issue on it anywhere.

**Comment by philbooth** [comment]
Drive-by comment as I came to this bug from the OKR doc.

It seems like we might have good reason for these two:

> 1. On 58.0.2 (release) registered through first run, verified through email on my phone. After verification, I got redirected to a new tab without seeing the sms. ❌ 

Here we choose not to display the SMS screen because they're already on a mobile device. The app store button makes more sense then doesn't it?

> 2. On 58.0.2 (release) registered through first run, verified through email in a different tab. After verification, I got the app store buttons without the sms option. ❌ 

From the described behaviour, I'm assuming that "different tab" here really means "different browser/profile/container tab". In that case, we can't show the SMS screen because the auth server needs a session token on `POST /sms`. (although if not, it's a bug)

The code for both conditions is in `views/mixins/connect-another-device-mixin.js` fwiw:

https://github.com/mozilla/fxa-content-server/blob/f19eddf96483a618510c89d1bb23c396463440e7/app/scripts/views/mixins/connect-another-device-mixin.js#L148-L176

**Comment by philbooth** [comment]
I think we can close this. If anyone disagrees, feel free to re-open.
