### ISSUE TITLE
"Unexpected error" when trying to show 2fa screen in production

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5991]
Visiting https://accounts.firefox.com/settings?showTwoStepAuthentication=true with a signed-in account, I get a blank screen and the following traceback:

<img width="884" alt="capture" src="https://user-images.githubusercontent.com/34695/37632824-1ee4005c-2c44-11e8-8f60-1d39e59818e1.PNG">

**Comment by vbudhram** [comment]
I was able to reproduce this locally if signing in with an unverified session. The auth-server appears to reject the `/totp/exists` request with this error:

```
fxa-auth-server.ERROR: request.summary {"op":"request.summary","code":500,"errno":999,"rid":"1521516033649:vbudhram-23693:18090:jez2xk4q:10169","path":"/v1/totp/exists","lang":"en-US,en;q=0.9","agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Mobile Safari/537.36","remoteAddressChain":["127.0.0.1"],"t":6,"uid":"d69f562e730e4634a42f0c9e6fa2cd63","stack":"Error: Uncaught error\n    at _error (/Users/vijaybudhram/Desktop/working/fxa-local-dev/fxa-auth-server/node_modules/hapi/lib/protect.js:56:32)\n    at internals.Protect._onError (/Users/vijaybudhram/Desktop/working/fxa-local-dev/fxa-auth-server/node_modules/hapi/lib/protect.js:38:16)\n    at emitOne (events.js:96:13)\n    at Domain.emit (events.js:188:7)\n    at Domain._errorHandler (domain.js:113:21)\n    at process._fatalException (bootstrap_node.js:293:33)"}
```

This is confusing since the auth-server should have rejected the request with a 401 instead of 500, https://github.com/mozilla/fxa-auth-server/blob/012f23fa098f256f594df62151aca528680e8094/lib/routes/totp.js#L170.
