### ISSUE TITLE
TOTP: Suggest adding Refresh messaging

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa-content-server#6043]
It is not entirely clear what the Refresh button does within the MFA Settings. It would be helpful to add a tooltip, or some sort of visible messaging after a user clicks it.

**Comment by vladikoff** [comment]
cc @ryanfeeley  ^

**Comment by ryanfeeley** [comment]
@rbillings Good find!

It refreshes the contents of the section in the event that is has been updated in a different tab/device/session.

It also appears in sections like **Secondary email** and is probably used more there as users commonly verify their email on a different device.

We could do one or two things to *all of the Refresh buttons* to improve this:
1. Rename the button to say **Refresh Status**
2. Add a **Last update** timestamp to the button on hover.

Thoughts?
![image](https://user-images.githubusercontent.com/68213/38639252-9b6ef846-3d9e-11e8-9890-eddc60ece5c8.png)

**Comment by vbudhram** [comment]
> Add a Last update timestamp to the button on hover.

Is `Last update` the same as the last time button was clicked?

**Comment by rbillings** [comment]
I think Refresh Status adds a lot of clarity - across the board. Good idea! 👍

**Comment by ryanfeeley** [comment]
> Is Last update the same as the last time button was clicked?

Good catch @vbudhram. This tooltip is problematic copy.

How about ``Last checked: 11:53 PM`` which represent the last time the button was pressed OR when the section was opened?

**Comment by vladikoff** [comment]
@vbudhram @ryanfeeley confirm next steps?

**Comment by vbudhram** [comment]
I propose the following from https://github.com/mozilla/fxa-content-server/issues/6043#issuecomment-380572279:

* Update all panels that use `Refresh` to `Refresh Status`
* Show a tooltip with a synthesized Last update time.
* Tooltip shows `none` when panel is first opened
* Tooltip shows `none` when page is refreshed
* Tooltip shows `time` when refreshed button was clicked (only locally)

I can see the tooltip being problematic since the value is not return from the auth-server and will not be the same across multiple clients.
