### ISSUE TITLE
Make Chrome for Android work with OAuth and Notes

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6089]
## Chrome refuses to authenticate Sign up OR Sign in if there is any email polling involved. 

> The policy on the Chrome side for triggering redirects to an app, whether through a custom scheme or an https App Link, is that this action must be triggered by the user, not Javascript.

ref: https://stackoverflow.com/a/41882732

Rough demo of a fix:

<img src=https://user-images.githubusercontent.com/128755/39031242-03369596-4435-11e8-9acb-1ea292cc5d36.gif width=300 />

**Comment by vladikoff** [comment]
ignore the crashing in the GIF, if the app crashes it is good , means it was able to follow the redirect flow :P

**Comment by rfk** [comment]
(just adding some words based on IRC discussion)

> The policy on the Chrome side for triggering redirects to an app, whether through a custom scheme or 
> an https App Link, is that this action must be triggered by the user, not Javascript.

A useful analogy I think, is that redirecting to an applink on Android is kind of like opening up popup - fine to do as a result of user interaction, but easy to abuse if it's allowed from javascript at any random time.  For the notes login flow to work properly on Android, we need to introduce some explicit user action before triggering the final redirect, such as a button click.  Otherwise the browser will silently prevent the redirect from opening the target application.

**Comment by shane-tomlinson** [comment]
Can this be closed with #6090?

**Comment by vladikoff** [comment]
@shane-tomlinson Yes, thanks Shane!
