### ISSUE TITLE
OAuth tests failing on teamcity against latest

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6106]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=37639&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog

from https://screencap.co.uk/images/173039b3a12594bcd32a135487bb050c979ba06f.png

```
name: JWTVerificationError
message: malformed
```

@vladikoff - any ideas where this is coming from?

**Comment by rfk** [comment]
Might be a result of the new OIDC stuff in https://github.com/mozilla/123done/pull/165, I can try to dig in some tomorrow.

**Comment by rfk** [comment]
A quick theory, 123done expects to receive an id_token here:

  https://github.com/mozilla/123done/blob/oauth/oauth.js#L174

And passes it through to fxa-jwtool, which throws this "malformed" error if it's given a falsy id_token here:

  https://github.com/mozilla/fxa-jwtool/blob/master/index.js#L203

So my guess is that 123done is not requesting the "openid" scope for these tests, hence not receiving an id_token, hence triggering the error.  Do these tests do anything to customize the scopes requeted by 123done?

A quick fix may be to update 123done so that it doesn't try to check the id_token if one is not provided.

**Comment by rfk** [comment]
>So my guess is that 123done is not requesting the "openid" scope for these tests,
> hence not receiving an id_token, hence triggering the error

This was close - it looks like 321done is requesting the "openid" scope, but content-server filters it out because it's an untrusted relier.  I'm hopeful it'll be fixed by https://github.com/mozilla/fxa-content-server/pull/6111
