### ISSUE TITLE
Safari/Chrome: background stays grey after pressing the "eye"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6196]
child of https://github.com/mozilla/fxa-content-server/issues/6261

Found by @vladikoff in https://github.com/mozilla/fxa-content-server/pull/6195#issuecomment-389209645

> Unrelated I guess I noticed in Safari and Chrome, after we press show the button stays "focused" grey:
> ![aaa](https://user-images.githubusercontent.com/128755/40066904-228a8102-5833-11e8-861e-099a462c53f8.gif)

This is because the "show-password" label becomes focused. Perhaps after releasing it, we should blur the element?

**Comment by brizental** [comment]
Hey guys, I was taking a look at this and I don't understand why we have these three selectors: https://github.com/mozilla/fxa-content-server/blob/master/app/styles/modules/_password-row.scss#L205-L207 . Is there are a reason for them? 

They are  about the state of the input, but the state of the input doesn't matter for us here, since we are only going to change the background color of the eye button when we hover or click it, not the input.

By removing these three selectors everything works as expected. I'll send in a PR for review.

**Comment by vladikoff** [comment]
@brizental That CSS is from 3 years ago and the design changed ~3 times so it is totally possible that this is one of those CSS leftovers :)
