### ISSUE TITLE
Feature request: if the Firefox account was compromised, find a way to inform the user

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6582]
This was a request from a user, you can follow the discussions here: https://twitter.com/Minkovsky/status/1044584458395901952.

**Comment by shane-tomlinson** [comment]
We can [send this email to users](https://github.com/mozilla/fxa-auth-server/blob/c50acaff75c2be2e7dd07796cff2ee200aed5761/lib/senders/templates/password_reset_required.txt#L1) if we detected their account was compromised. 
We need to [ensure the flow still works](https://github.com/mozilla/fxa-auth-server/issues/2408)
because we haven't had to use it in a while.

It sounds like what the user is asking for is subtly different. IIUC, they are asking 
for Lockbox to automatically redirect the user to a site's password reset page if
Monitor detects the user's creds for that site were found elsewhere. I think
that might already be in the cards, @linuxwolf should be able to verify.

**Comment by shane-tomlinson** [comment]
Closing as Lockbox and Monitor are already talking about doing this within their products and we have an account notification system already.
