### ISSUE TITLE
Difficulty to run it without Docker

### ISSUE THREAD

**Issue by mirabellette** [mozilla/fxa-content-server#6601]
Hello everyone,

In order to manage by my own the Firefox Authentication, I am installing the four micro services required to do it.:
- fxa-auth-db-mysql -> authdb.example.com
- fxa-auth-server -> auth.example.com
- fxa-content-server -> content.example.com
- fxa-oauth-server -> oauth.example.com
- fxa-profile-server -> profile.example.com

Moreover, I do not want to use Docker because I really want to understand how it works. I was able to configure most of them except fxa-content-server.

This is the process I followed:

- git clone https://github.com/mozilla/fxa-content-server.git
- chown firefox:firefox -R fxa-content-server
- cd /opt/fxa-content-server
- sudo -u firefox npm install --production
- sudo -u firefox npm install bluebird
- sudo -u firefox npm run build-production
- sudo -u firefox NODE_ENV=production npm start

However, I got two errors I was not able to solve when I connect to content.example.com. 

**The first one** is about static css. Even if I specificy in server/config/production.json to load   "static_directory": "dist" and  "page_template_subdirectory": "dist" ; it is loaded from app directory.
That means some css and bundle.js is missing. How to fix that?

**The second error I** got is about geodb, I do not understand why but I got no fetch data. I replaced 
- "public_url": 
- "oauth_url":
- "profile_url":
- "profile_images_url": "I let the original one for this one"

Do you have some idea about that?

Thank you for your help,
Best regards,
Mirabellette

**Comment by shane-tomlinson** [comment]
Hi @Mirabellette, in the last step where you do `NODE_ENV=production npm start`, try running `npm run start-production`. The [start-production](https://github.com/mozilla/fxa-content-server/blob/9312cc9a5f6e9ff5c2993cb4aded54b053aed2ed/package.json#L13) points to the correct config files to load the JS & CSS from dist.

The geodb error happens often if you are connecting to a local server or from a private IP address, e.g., localhost, 127.0.0.1, 192.168.*.*, etc. Since those are private IP addresses the DB won't have geo information about them.

**Comment by vladikoff** [comment]
` NODE_ENV=production npm start` 👍
