### ISSUE TITLE
Change email and Force Auth have a bad interaction

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6745]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1509108, if a user has a Desktop and Android device connected and changes their primary email on Desktop, the Android device is signed out and not given the ability to change email at force auth screen.

Similar to iOS, we should give them an option to switch emails when in force auth.

**Comment by vladikoff** [comment]
@vbudhram `switch emails when in force auth.` The point of force auth is to force a particular email. It seems otherwise there is no point of forcing.  Do you want to somehow let the user pick from a list of secondary email?

**Comment by vbudhram** [comment]
> Do you want to somehow let the user pick from a list of secondary email?

That seems like it would be a little more complicated than I would like. I was thinking of adding a button at the bottom `Switch email` (something along those lines) that would redirect to sign-in page.

I am not familiar with all of the use cases when force auth is imposed but it seems reasonable to me to give an option when there is an existing session or a session has expired/destroyed. Which would hopefully avoid any strange user states.

**Comment by foursixnine** [comment]
@vladikoff if the user changes the password, and then changes the email, user won't be allowed to log in, as the system will ask the user to re-auth with the first email (on a second system). At least that's my use-case

**Comment by rfk** [comment]
I agree with @vladikoff that we need to be careful about unintended consequences here, as the existing semantics of `force_auth` are that you auth as the specified user or not at all.  We should know the `uid` as well as the `email` on this view, i wonder if there's a way to ensure that the user signs in as the specified `uid` even if they need to change the `email`.

We may need to add a fifth state to the little matrix at [1] for "the uid exists but its primary email doesn't match the one given in the URL".

[1] https://github.com/mozilla/fxa-content-server/blob/881efbc/app/scripts/views/force_auth.js#L82

**Comment by shane-tomlinson** [comment]
> We may need to add a fifth state to the little matrix at [1] for "the uid exists but its primary email doesn't match the one given in the URL".

I am uncomfortable modifying the semantics of force_auth w/o understanding how the various clients will react. For example, we are able to support a change of uid in the force auth flow for new Firefox Desktops. We are unable to support this on old Firefox desktops.

A similar question applies here - if browsers receive a `login` message for an email address that differs from the currently signed in address, what happens? I imagine when the `can_link_account` message comes in with the new email address, the browser will ask the user "Are you sure you want to merge these accounts?" Assuming the user clicks "yes", do browser's Sync clients depend on the user's email address in on other ways that are problematic with an email change? If so, do users need sign out of the browser before signing in with the new email?

Since we are moving to an OAuth only world, we have to consider the repercussions of a change fo semantics there too.

**Comment by foursixnine** [comment]
I'm not sure if changing emails for me triggered a merge or simply a new login?... If I try to login, what happens behind the scenes? is there a check that can reply "Hey this is an email address that's linked to that $user". Merging is one thing and logging in with a secondary email is another thing... isn't it?.

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-bugzilla-mirror/issues/558
