### ISSUE TITLE
Show a loading indicator while waiting for session status

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6877]
From https://github.com/mozilla/fxa-content-server/pull/6754#issuecomment-452072880, we should show a loading indicator similar to how the "Devices & apps" section shows when it is opened. Currently, we show the `unverified panel` while we wait for the browser to determine if the session is verified or not. This causes a slight jank when the section is opened.

**Comment by algomaster99** [comment]
Hello! I would like to work on this issue. Please assign it to me.

**Comment by shane-tomlinson** [comment]
Hi @algomaster99 - You are welcome to work on this bug! Unfortunately we are only able to assign bugs to people in the mozilla/fxa-devs team, though none of us have any immediate plans to work on this so you should be safe to continue. 

If you run into any issues, let any of us know. @vbudhram might have some tips on other places the loading spinner is used within settings that you could use as a model for here.

**Comment by shane-tomlinson** [comment]
@vbudhram to follow up.

**Comment by algomaster99** [comment]
I am having difficulty in setup. The setup fails at npm install  when setting up fxa-local-dev. `fxa-local-dev@1.0.2 postinstall: `_scripts/postinstall.sh``. This is the error being thrown.

**Comment by shane-tomlinson** [comment]
@algomaster99 - Since you are going to only be working in the content-server, you might have better luck only installing the content server and running `npm run start-remote`.

See https://github.com/shane-tomlinson/fxa-content-server/blob/68ac159efce4659a324e412d5b77f24ff0d34deb/README.md#quick-start.

Ensure you are using node 8x and npm 6x, and have all the prerequisites installed that are specified in https://github.com/mozilla/fxa-local-dev#dependencies.

If that doesn't work, maybe we can walk you through the install step in irc, connect to irc.mozilla.org and join the #fxa channel.

**Comment by shreya99oak** [comment]
May I work on this?

**Comment by vbudhram** [comment]
@shreya99oak Sure!

@algomaster99 @shreya99oak After you have gotten your local environment setup and running. I would replicate how the current client and devices section work.

It currently applies a loading class and gets toggled when the button is clicked. Ref [link1](https://github.com/mozilla/fxa-content-server/blob/b4d82d97a9bbd00a08bb739bbdf1d08b4ede7c1a/app/scripts/templates/settings/clients.mustache#L6), [link2](https://github.com/mozilla/fxa-content-server/blob/881efbc9a626a167aaa4d76291ef0cdd3db99d78/app/scripts/views/settings/clients.js#L24).

**Comment by karansapolia** [comment]
Hey @vbudhram @shane-tomlinson, I would like to work on this issue. May I take it up?

**Comment by bini11** [comment]
Hey @shreya99oak are you still working on this issue?

**Comment by AlbionaHoti** [comment]
Hi @shane-tomlinson - I am an outreachy applicant - I wanted to work on this - if possible?

I see there are a lot of people who would like to work on this issue, I tried myself because I had another small issue on this part - I tested it and made the loading spinner work before the QR code is shown - 

If @shreya99oak didn't work on this - and is not available to work on the task - I can create a PR.

**Comment by vbudhram** [comment]
Hey @karansapolia, I haven't heard back from @shreya99oak so I think it is ok for you to work on this if you choose.

If you are not able to, @bini11 you can, if you can't think @AlbionaHoti maybe.

Thanks for the interest!

**Comment by karansapolia** [comment]
Sure, I'll start working on this, if I am not able to, I will let you all know at the earliest so others can have a go at it.

**Comment by shreya99oak** [comment]
Hey, couldn't find time to solve this one..if it's open would like to work on it...but if @karansapolia has started working on it, wouldn't want to intervene.

**Comment by karansapolia** [comment]
I am halfway through this issue at this point. But yes, if I am not able to finish it, won't be keeping anyone waiting.
