### ISSUE TITLE
App store badges not showing up

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6942]
STEPS TO REPRODUCE
1. In my personal browser profile I went to: https://accounts.firefox.com/sms

EXPECTED RESULTS
* App and Play Store badges appear

ACTUAL RESULTS
* They don't
<img width="455" alt="image" src="https://user-images.githubusercontent.com/68213/52349568-dabba380-29f4-11e9-8963-156913e59daf.png">

**Comment by shane-tomlinson** [comment]
They were never added to this page, only on the "enter your phone number" page. IIRC, this was an explicit decision,users have already sent the SMS and we want them to open the SMS rather get distracted and click on an app store link.

**Comment by shane-tomlinson** [comment]
Looking at that photo more closely, there's the "If you are not receiving the text message" message, which implies buttons should be there.

And the [feature doc](https://github.com/mozilla/fxa/tree/master/features/FxA-53-send-sms) has this:

<img width="455" alt="image" src="https://github.com/mozilla/fxa/raw/master/features/FxA-53-send-sms/image_20.png">

**Comment by shane-tomlinson** [comment]
@ryanfeeley I've figured out the problem. It's because you browsed directly to the `/sms` page, which we don't expect. If you add the `?service=sync` query parameter, then the buttons are displayed as expected:

<img width="469" alt="screenshot 2019-02-07 at 06 48 14" src="https://user-images.githubusercontent.com/848085/52394996-5f192f80-2aa4-11e9-9d2d-22e65c439834.png">

**Comment by shane-tomlinson** [comment]
WONTFIX until SMS is exposed to non-sync reliers.
