### ISSUE TITLE
Avatar preview not horizontally centered on tablets in landscape

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#7019]
## Description

The avatar preview is not centered when using a "tablet" resolution (wide but not tall) in landscape mode.

### Steps to reproduce

1. On a tablet, open https://accounts.firefox.com/settings/avatar
2. Put the tablet into landscape mode

<img width="1152" alt="screenshot 2019-03-06 at 10 18 52" src="https://user-images.githubusercontent.com/848085/53874051-8c9cbe80-3ff9-11e9-9cf2-4e87d3da6be2.png">

### Expected result

The avatar preview should be centered, and possibly taking up more of the screen.

### Actual result

The avatar preview is at the far left.

ref #6984, #6594, #6261, #5313, #3485

**Comment by hritvi** [comment]
May I work on this @shane-tomlinson ?

**Comment by shane-tomlinson** [comment]
You sure can @hritvi!

**Comment by sv-sdeiac** [comment]
Hi, I tried to reproduce this issue on the production but I wasn't able. Also, The issue is not reproducible on stage server [Train 133].
Device: Samsung Galaxy Tab S3 (Android 8.0).
@shane-tomlinson Can you check if this issue is fixed on stage server?
Screenshot with my findings:
![Screenshot_5](https://user-images.githubusercontent.com/40264165/54761581-07212d00-4bfb-11e9-8a65-759182808547.png)
