### ISSUE TITLE
User is able to sign up even if the account already exists

### ISSUE THREAD

**Issue by farhan787** [mozilla/fxa-content-server#7055]
### Steps to reproduce
1. Make an account
2. Sign up with the same existing account

### Expected behaviour
The user should be redirected to sign in page

### Result
The user is signed in via the sign up page

**Comment by shane-tomlinson** [comment]
This is [expected behavior](https://github.com/mozilla/fxa-content-server/pull/3413), and [intentional](https://github.com/mozilla/fxa-content-server/issues/2778). We are deprecating this flow to avoid this and other confusion, instead preferring the ["email-first" flow](https://github.com/mozilla/fxa-content-server/issues/6125).

Closing since this is expected behavior.

**Comment by farhan787** [comment]
@shane-tomlinson I got it!
