### ISSUE TITLE
change some images to data-uris in the css?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#932]
I'm staring at my Network tab in the FF Dev Tools and was wondering if we should try converting a few of the small images to data URIs in the long-cached CSS since they aren't locale specific or anything and it would reduce our number of requests by 3.

I was thinking the prime candidates would be:
- mozilla.png (3.44kb)
- ddarrow_inactive.png (0.23kb)
- ddarrow_active.png (0.22kb)

Currently we make 9-10 requests on the /signup page, so this would reduce it nicely, at the expense of a slightly more bloated initial CSS payload. I think Sass may even have a method of embedding an image into the CSS, but I don't know if that is only via Compass or if it is supported by our grunt-sass package (which is C based and not Ruby based).

Just a thought.

**Comment by vladikoff** [comment]
ideas: 

use sprites?
use this for the logo?

**Comment by eoger** [comment]
Maybe this will not be relevant in the near future since HTTP2 is starting to get some traction.
As a reminder HTTP2 adds multiplexing and server push which are both really great for CSS/JS/Image files.

**Comment by shane-tomlinson** [comment]
@jedp - ah, come on man, are you sure you don't want to tackle this? I'd be nice to have you back!

**Comment by shane-tomlinson** [comment]
> Maybe this will not be relevant in the near future since HTTP2 is starting to get some traction.
As a reminder HTTP2 adds multiplexing and server push which are both really great for CSS/JS/Image files.

Right, performance is an area where we are going to have to do a lot of testing, measuring, and tuning. We can use SPDY right now in nginx. We'll have to [wait for HTTP/2](http://nginx.com/blog/how-nginx-plans-to-support-http2/).

Multiplexing assumes we serve everything from accounts.firefox.com. Unfortunately, accounts.firefox.com is not currently geolocated all around the world, meaning, even if we use push/multi-plexing, latency exists just because of distance from the server to a user. I'd like to explore pushing all static resources out to the Mozilla CDN to see if that gives us any wins that HTTP/2 from servers in only a handful of regions doesn't.

**Comment by issues-bouncer** [comment]
Hey @johngruen, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.
